### PR TITLE
[Jetty-Client] fix: don't add host automaticaly on http2 request.

### PR DESCRIPTION
**Pull request by stephanemartin**
All google server answer bad request when Host field is filled in h2 protocol.

Change-Id: I9e16f8c9f56bc26df0b0a933cee0b3a3d6c31921

### CODE REVIEW

**Comment by stephanemartin** [comment]
Hum I've signed the CLA. With my both address. stephane.martin@neotys.com and stephane@stephanemartin.fr

**Comment by joakime** [comment]
Using https://projects.eclipse.org/user/cla/validate to verify your CLA ...

 * stephane.martin@neotys.com is not registered
 * stephane@stephanemartin.fr **is** valid, use that.

Don't forget to use the `-s` option (sign-off) on your commits `git -s commit` too.

**Comment by sbordet** [comment]
@stephanemartin, I have verified that this is indeed a problem, so your patch is welcome.

You must re-issue the patch adding the sign-off, so please also modify the patch to check for:

```java
if (version.getVersion() == 11)
```

rather than your initial patch.

Thanks !

**Comment by stephanemartin** [comment]
@sbordet Thanks for your comment. I'm thinking too that http/1.2 is dead :)

**Comment by stephanemartin** [comment]
Could-I cherry to master branch ?

**Comment by sbordet** [comment]
@stephanemartin we will merge to master.

**Pull request merged**
