### PR TITLE
Removing jetty-maven-plugin IT test javax-annotation-api

### PR DESCRIPTION
**Pull request by joakime**
Fixing `jetty-9.4.x` branch build.

The javax.annotation-api 1.3 dependency conflicts with the maven built-in jsr250-api 1.0 dependency.
Removing the jsr dependency from `<extensions>` fixes this build issue.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Review by olamy — DISMISSED** [review]

**Comment by olamy** [comment]
due to upgrade to maven 3.8.3 see https://issues.apache.org/jira/browse/MNG-7045

**Comment by olamy** [comment]
this will still fail with maven 3.8.2-
We need to add a selector  `invoker.maven.version = 3.8.3+`
see a3d0c13802646d1d2201a8d0957520fb73a4a399

**Review by olamy — DISMISSED** [review]

**Comment by janbartel** [comment]
Do we even need this test any more if we have upgraded the jetty build to a suitably recent version that doesn't use the old jsr annotations jar?

**Review by janbartel — CHANGES_REQUESTED** [review]
See my comment - why do we even need this test any more?

**Comment by olamy** [comment]
Yup I agree we can get rid of it it was just an example of workaround for Java 1.8 and maven 3.8.2-

**Comment by joakime** [comment]
@janbartel @olamy just removed that test entirely in this PR.

**Review by olamy — APPROVED** [review]

**Review by janbartel — APPROVED** [review]

**Pull request merged**
