### PR TITLE
Fix log class name in ArrayByteBufferPool

### PR DESCRIPTION
**Pull request by slovdahl**

### CODE REVIEW

**Comment by sbordet** [comment]
@slovdahl the PR looks good, but you need to sign the Eclipse Contribution Agreement for us to accept this PR.
Please see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md. Thanks!

**Comment by slovdahl** [comment]
@sbordet Thanks, signed it. :+1:

**Comment by sbordet** [comment]
@slovdahl seems you did not sign-off your commit as required?
Please see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md. Thanks!

**Comment by slovdahl** [comment]
Oh, I'm sorry, I completely missed that part. Should be fixed now. Thanks for the patience! :bow:

**Review by sbordet — APPROVED** [review]

**Pull request merged**
