### PR TITLE
Issue #856 Add server/port and auth configuration for mongo sessions

### PR DESCRIPTION
**Pull request by jin-z**
Signed-off-by: Jin Zhang <jin.zhang@epicgames.com>

### CODE REVIEW

**Comment by janbartel** [comment]
@jin-z  I'm trying to test this, but with no luck. Could be my mongo security setup. 

I've got a user defined like this in the "admin" database:
```
db.getUser("janb")
{
	"_id" : "admin.janb",
	"user" : "janb",
	"db" : "admin",
	"roles" : [
		{
			"role" : "dbAdmin",
			"db" : "HttpSessions"
		},
		{
			"role" : "readWrite",
			"db" : "HttpSessions"
		}
	]
}
```

And I'm using this connection string:  
```
jetty.session.mongo.connectionString=mongodb://janb:janb@127.0.0.1/admin
```

When I run jetty with mongo, I always get this error:

```
com.mongodb.MongoException: not authorized to create index on HttpSessions.jettySessions
	at com.mongodb.CommandResult.getException(CommandResult.java:82)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:116)
	at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:126)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:148)
	at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:132)
	at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:255)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:347)
	at org.eclipse.jetty.nosql.mongodb.MongoSessionDataStore.ensureIndexes(MongoSessionDataStore.java:538)
	at org.eclipse.jetty.nosql.mongodb.MongoSessionDataStore.doStart(MongoSessionDataStore.java:523)
```

Is there some setup I'm missing?

thanks
Jan

**Comment by jin-z** [comment]
Are you missing the password for that user? I tried to set this up locally myself and querying the users I actually see the hashed password in the DB. Also, I am not sure about the roles. I manually created the user via "Robomongo" and entered the roles "read" and "readWrite"

image

And then for the connection string I used:
`mongodb://kensou:kensou@localhost/HttpSessions`

And that worked fine for me

**Comment by janbartel** [comment]
@jin-z  are you sure you're using the same mongo java driver as in the jetty distribution? I can't get authentication to work at all, so I took a look at the MongoURI class, and found this:

```
    public DB connectDB( Mongo m ){
        // TODO auth
        return m.getDB( _database );
```
That is mongo-java-driver-2.6.1.  Can you double-check your version, and have a look into the code in your version of MongoURI please?

**Comment by jin-z** [comment]
Oops! You are correct. I'm sorry, I have a "frankenbuild" version running (I couldn't get the vanilla one to compile as-is). The driver I have is mongo-java-driver-2.13.2.jar

**Comment by janbartel** [comment]
Ah, that makes sense. Can I get you to update your pull request to modify the pom.xml to use 2.13.2, and also the src/main/config/modules/session-store-mongo.mod file to also refer to the updated version?
I think we will also need to do more work on the session-store-mongo module to be able to use either the connection string or the server/port string, but I can do that.

**Comment by jin-z** [comment]
I've updated the pom file and the reference to the right jar file in the mod file.

**Pull request merged**
