### PR TITLE
Certificates Alias checks

### PR DESCRIPTION
**Pull request by openconcerto**

### CODE REVIEW

**Comment by gregw** [comment]
I had a bit more of a look at this, apart from the IO issue, this change breaks the unit test: testNoTsSetKs
I'm also a bit unsure what exactly it is trying to do, so some code comments or discussion as line notes against the commit would be helpful

**Comment by openconcerto** [comment]
Aren't the log and exception clear enough? :)

When setting a certificate alias, the code checks that the certificate exists.
If the certificate is found and is not trusted, a warning is logged.
The code checks is there is certificates in the keystore. How can we init SSL without that...
if there is no trusted certificate in the keystore, a warning is displayed.

It will save hour**s** of debugging, see all the posts in forum about SSL ;)

**Comment by gregw** [comment]
Sure I agree that better warnings/errors are a really good idea.    But the testNoTsSetKs test is failing when it previously failed... so I'm trying to get my head around that (on very limited time).     It is not clear to me why the absence of the Ts is causing no certificate to be found... however it does look like it is errorring because there are no aliases.... could it be that the keystore was previously acceptable because it had one certificate but without an alias?

**Comment by gregw** [comment]
Closing as I don't fully understand.   Please reopen if you can address my concerns above.

**Pull request closed without merging**
