### PR TITLE
Remove Lock from ManagedSelector

### PR DESCRIPTION
**Pull request by tom-smalls**
Remove the lock used in ManagedSelector, replacing it with a concurrent deque and a atomic boolean

### CODE REVIEW

**Comment by gregw** [comment]
Tom,

we have had the selector lock free before, but hit some surprising race conditions and are cautious about changing it.   Do you have any indications that this gives you greater performance?

Note also that the ArrayDQueue generates a lot less garbage than a linked queue.

**Comment by tom-smalls** [comment]
Happy to write a JMH benchmark to prove/disprove any performance gains. I would expect the removal of the lock to be more performant (even with more garbage) if the lock is ever contended, but that's pure conjecture.

**Comment by gregw** [comment]
Tom,

I think a benchmark is needed.   If you look at the history of this class, you can see that we've tried a lot of variations - lock-free state machines, spin locks and the current locker.

The current locker, can either use re-entrant lock or our own spinlock class (you can use a system property to switch between).    Our tests showed that re-entrant lock was actually better, as modern JVMs actually spin on it first before doing any heavy weight locking. 

I'll also repeat my concerned about the split between the DQ and the atomic boolean, as that is a race condition waiting to happen.... I can't exactly say why it is a problem, but then I can't say that it is not.

Either way, thanks for looking at this stuff - extra eyeballs are always welcome.... EVEN IF we end up not changing.    Unless we periodically validate design decisions, then we will become stale.

cheers

**Comment by tom-smalls** [comment]
Sorry I haven't replied to this sooner. I am will work on benchmark on Friday afternoon (UK).

Do you have these tests for the different lock types to hand by chance? There's a race conditions where you move to selecting mode after polling for an action (another action could be added after your poll via submit(), meaning the queue is not actually empty) in runActions(), and thus switching to selecting mode when there is something in the queue. I don't know the surrounding code well enough to know if this is a problem or not though?

**Comment by gregw** [comment]
@sbordet Do you have the JMH benchmarks we used for these lock tests?   I had thought they were in git@github.com:jetty-project/jetty-bench.git, but can't find them?

Do you have any thoughts about this PR?

**Comment by tom-smalls** [comment]
I've written some very basic JMH benchmarks, but haven't had a chance to run them all yet with the new and original code.

I'll hold off until I've seen the original benchmarks as I would like to compare what I've done to ensure the usage of ManagedSelector is realistic

**Comment by gregw** [comment]
@sbordet poke!

**Comment by gregw** [comment]
Marking this as more info needed as we really need to benchmark this.  But it is a worthwhile area to investigate when we have some spare cycles.

**Comment by jmcc0nn3ll** [comment]
@tom-smalls I think you have the CLA on the file now but we would need this pushed again with the correct Signed-Off-By dealio to be able to merge it, Eclipse githook requirements, etc..

If you are interested please reopen and push the update!

cheers!

**Comment by tom-smalls** [comment]
@jmcc0nn3ll I'll review the PR as it's been a while, and will re-open etc if still happy with it.

Thanks

**Pull request closed without merging**
