### PR TITLE
Issue #2788 -  Graceful close of HTTP/2 Connection.

### PR DESCRIPTION
**Pull request by sbordet**
Implemented HTTP2Session.shutdown() to shutdown the session
gracefully with a timeout.
It's a draft because there are a number of issues to be resolved.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@gregw this is the first draft to implement graceful HTTP/2 close.
There are a number of issues reported here:
https://github.com/eclipse/jetty.project/pull/4089/files#diff-0efc82f322946d301e9cd91fcd844c80R878

We need to discuss them.

**Comment by gregw** [comment]
Does this need to be in 9.4.23?

**Comment by sbordet** [comment]
@gregw not it does not, I'll remove it from the project.

**Comment by sbordet** [comment]
Closed in favor of #4554.

**Pull request closed without merging**
