### PR TITLE
Issue #10066 - Allow customization of `SAXParserFactory` and `SAXParser` in `XmlParser`

### PR DESCRIPTION
**Pull request by joakime**
Backport of PR #10067 to `jetty-9.4.x`

* Allow customization of SAXParserFactory / SAXParser in XmlParser
* Introduce method `.getSAXParser()`

### CODE REVIEW

**Comment by joakime** [comment]
Strange test failures on 8u382 that didn't happen on my 8u362 machine.
Investigating.

**Comment by joakime** [comment]
The JDK difference was a red herring.
The test failures are reproducible on my machine too.
Pushed a fix (really a backport of an old fix from `jetty-10.0.x`)

**Comment by joakime** [comment]
Had to cherry-pick a (limited form of) commit a9c596e3d79fbfa14bf8ae20148881dc9f0f8b05 back to `jetty-9.4.x` to get it to be happy.

**Review by sbordet — APPROVED** [review]

**Comment by chadlwilson** [comment]
Thanks for backporting this! 🙏

Does this backport mean the affected versions of https://github.com/advisories/GHSA-58qw-p7qm-5rvh can be updated to exclude `9.4.52.v20230823` ?

**Comment by chadlwilson** [comment]
On the assumption that this appears to do so, based on how the earlier advisory was structured for 10.x and 11.x and affected versions and PRs, I've suggested updating the main advisory via https://github.com/github/advisory-database/pull/2673

I am not entirely clear how https://github.com/eclipse/jetty.project/security/advisories/GHSA-58qw-p7qm-5rvh is linked to the github-reviewed variant, so if this is inappropriate,let me know and I'll cancel it. Just trying to help out. 🙏

**Comment by joakime** [comment]
@chadlwilson do you use Jetty's `org.eclipse.jetty.xml.XmlParser` directly in your webapp (as in _your own code_ uses the Jetty `org.eclipse.jetty.xml.XmlParser` class)?

If the answer is no, then you are not vulnerable to GHSA-58qw-p7qm-5rvh

**Comment by chadlwilson** [comment]
@joakime I am aware of this distinction. This isn't about my personal usage - already suppressed the reported vulns on that basis a while back.

However it's still useful to get scanner noise to go away for the wider community so there are fewer reported vulns for folks to investigate if they keep their dependencies updated. Trivy is detecting this one right now on container image scans which also means the Helm Artifact Hub is doing the same if publishing OSS images there.

**Comment by joakime** [comment]
@chadlwilson we updated the affected / patched versions in our repository version of the GHSA-58qw-p7qm-5rvh advisory

* https://github.com/eclipse/jetty.project/security/advisories/GHSA-58qw-p7qm-5rvh

And submitted a PR to change the public advisory as well

* https://github.com/github/advisory-database/pull/2688

**Pull request merged**
