### PR TITLE
Issue #150: Ability to handle JAR directories in extraClasspath.

### PR DESCRIPTION
**Pull request by i2shar**
In keeping with Java conventions[0], any directory paths ending in /* should be considered a JAR directory and all jars in that directory will be added (non recursively) to the classpath.

[0] https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html

### CODE REVIEW

**Comment by joakime** [comment]
Do the new files `src/test/resources/ext/com-i2shar-ext-one.jar` etc contain any licensed content?

**Comment by i2shar** [comment]
> Do the new files `src/test/resources/ext/com-i2shar-ext-one.jar` etc contain any licensed content?

No.

**Comment by janbartel** [comment]
Just for completeness, here's a reference to the original PR that was closed, but contains historically useful info: #3324

**Comment by janbartel** [comment]
@i2shar  thanks for updating the unit test. One last thing, could you re-checkin the jars, and add in the source of the Main.java classes? We are an os project, and we need to make the src available, and also to be able to repro the jar if we ever needed to.

**Comment by i2shar** [comment]
@janbartel What would be a good place to add the sources for Main.java? If I add them to jetty.project/jetty-webapp/src/test/java, they end up in target/test-classes and are always in the test classpath so are always loaded, causing the assertCantLoadClass() tests to fail. Also, I couldn't find sources for (your?) jars under jetty.project/jetty-webapp/src/test/resources/mods/foo-bar-janb.jar

**Comment by joakime** [comment]
@i2shar including the `Main.java` in the jar files themselves, next to the `Main.class` should be sufficient.

**Comment by i2shar** [comment]
@joakime @janbartel - included sources in the jar as instructed, can you kindly review?

**Pull request merged**
