### PR TITLE
Issue #8753 - Fix HttpClient initialization with destinationIdleTimeout set.

### PR DESCRIPTION
**Pull request by janvojt**
The fix is also needed in version 12.

### CODE REVIEW

**Comment by sbordet** [comment]
@janvojt please issue PRs against branch `jetty-10.0.x`. We will take care of merging to Jetty 11 and 12.

Also, please comply with https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md, otherwise we cannot accept your PR.

**Comment by sbordet** [comment]
@janvojt I would not mind if you could fix a similar issue with local variable `executor` few lines above the ones you modified for the `scheduler` local variable.

**Comment by janvojt** [comment]
@sbordet The issue is not present in `jetty-10.0.x`, that is why I request merging into `jetty-11.0.x`.

I read `CONTRIBUTING.md`, signed-off commit, created new Eclipse account, agreed with ECA, revalidated ECA sign-off, but the check still failed. My ECA form has the following, so I suppose it is valid:
```
The Eclipse Contributor Agreement 3.1.0 that you signed is valid for a period of three years from date of signing and is set to expire on 2025-10-21.
```

I fixed the `executor` as well.

**Comment by joakime** [comment]
> @sbordet The issue is not present in `jetty-10.0.x`, that is why I request merging into `jetty-11.0.x`.

Considering that we only really work in Jetty 10.0.x, and them merge to 11.0.x, this would be surprising!

**Comment by janvojt** [comment]
I'm sorry, you are correct. I did not update my v10 branch. I am closing this and will create a new PR.

> > @sbordet The issue is not present in `jetty-10.0.x`, that is why I request merging into `jetty-11.0.x`.
> 
> Considering that we only really work in Jetty 10.0.x, and them merge to 11.0.x, this would be surprising!

**Pull request closed without merging**
