### PR TITLE
Issue #1478 - speculative fix for Writer output mode in ErrorHandler

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
@gregw I'm not sure this is the best solution here.

As all it does is reuse Writer if it exists, and creates the output in STREAM mode if it doesn't.
Shifting the behavior from WRITER to STREAM in essence.

**Comment by gregw** [comment]
@joakime, Indeed, this is not what we need.  We need tri-state logic:
 * No existing writer or stream - set charset then return getWriter()
 * Existing writer - return getWriter()
 * Existing output stream - set charset then return wrapped output stream.

But even this is really poor behaviour as how do we know the bytes written to the outputstream already are acceptable.     Let me analyse the OPs situation some more so before we act on this.

**Comment by joakime** [comment]
This PR left 30 tests in error state. yeck!

Feel free to work on the `issue-1478` branch for this.

**Comment by gregw** [comment]
#1478

**Pull request closed without merging**
