### PR TITLE
Fixes #10315 - ServletInputStream::isReady results in IllegalArgument…

### LINKED ISSUE #10315: ServletInputStream::isReady results in IllegalArgumentException
**Jetty version(s)**
Jetty 12.0.0

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
openjdk version "17.0.7" 2023-04-18 LTS

**OS type/version**
MacOS 13.5

**Description**
The Spring Framework is upgrading to 12.0 as part of its 6.1 release.
Using 12.0.0 GA, we run into one particular issue that occurs in an asynchronous servlet, where when we check `ServletInputStream::isReady` it results in a `IllegalArgumentException`. This is the stack trace:

```
at org.eclipse.jetty.server.internal.HttpChannelState$ChannelRequest.demand(HttpChannelState.java:1003) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.Request$Wrapper.demand(Request.java:718) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.handler.ContextRequest.demand(ContextRequest.java:41) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.AsyncContentProducer.isReady(AsyncContentProducer.java:231) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.HttpInput.isReady(HttpInput.java:178) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.springframework.http.server.reactive.ServletServerHttpRequest$RequestBodyPublisher.checkOnDataAvailable(ServletServerHttpRequest.java:312) ~[main/:?]
at org.springframework.http.server.reactive.AbstractListenerReadPublisher.changeToDemandState(AbstractListenerReadPublisher.java:235) ~[main/:?]
at org.springframework.http.server.reactive.AbstractListenerReadPublisher$State$2.request(AbstractListenerReadPublisher.java:350) ~[main/:?]
at org.springframework.http.server.reactive.AbstractListenerReadPublisher$ReadSubscription.request(AbstractListenerReadPublisher.java:276) ~[main/:?]
at reactor.core.publisher.BaseSubscriber.request(BaseSubscriber.java:214) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at org.springframework.http.codec.multipart.MultipartParser.requestBuffer(MultipartParser.java:193) ~[main/:?]
at org.springframework.http.codec.multipart.MultipartParser.hookOnSubscribe(MultipartParser.java:114) ~[main/:?]
at reactor.core.publisher.BaseSubscriber.onSubscribe(BaseSubscriber.java:148) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at org.springframework.http.server.reactive.AbstractListenerReadPublisher$State$1.subscribe(AbstractListenerReadPublisher.java:318) ~[main/:?]
at org.springframework.http.server.reactive.AbstractListenerReadPublisher.subscribe(AbstractListenerReadPublisher.java:109) ~[main/:?]
at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:74) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at org.springframework.http.codec.multipart.MultipartParser.lambda$parse$1(MultipartParser.java:103) ~[main/:?]
at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxConcatMap$WeakScalarSubscription.request(FluxConcatMap.java:479) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2305) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.6.0-M1.jar:3.6.0-M1]
at org.springframework.http.server.reactive.ServletHttpHandlerAdapter.service(ServletHttpHandlerAdapter.java:199) ~[main/:?]
at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1608) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1541) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.ServletChannel$RequestDispatchable.dispatch(ServletChannel.java:910) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:686) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:483) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463) ~[jetty-ee10-servlet-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:808) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.Server.handle(Server.java:177) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:651) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:480) ~[jetty-server-12.0.0.jar:12.0.0]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) ~[jetty-io-12.0.0.jar:12.0.0]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-12.0.0.jar:12.0.0]
at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-12.0.0.jar:12.0.0]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[jetty-util-12.0.0.jar:12.0.0]
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[jetty-util-12.0.0.jar:12.0.0]
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[jetty-util-12.0.0.jar:12.0.0]
at java.lang.Thread.run(Thread.java:1583) [?:?]
```

The line in Spring Framework that causes this is [here](https://github.com/spring-projects/spring-framework/blob/37a4e8445031aebf7eb2deb027e3c4d599368652/spring-web/src/main/java/org/springframework/http/server/reactive/ServletServerHttpRequest.java#L312). 

The line in Jetty that throws the exception is [here](https://github.com/eclipse/jetty.project/blob/cdf5035ab22f695af3084c5184abbe065c8c77ae/jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/internal/HttpChannelState.java#L1003).

This same code worked in previous version of Jetty (9.1+), so this looks like some sort of regression, as I don't think `ServletInputStream::isReady` is allowed to throw an `IllegalArgumentException`. If it is, and we are doing something wrong on our end, please inform us.

**How to reproduce?**

I've tried my best to create a small minimal sample that reproduces this problem, but have been unable to in a reasonable timespan.

The best luck to reproduce the issue is when running the build of my Spring Framework Jetty 12 upgrade branch that you can find [here](https://github.com/poutsma/spring-framework/tree/jetty-12-migration). Two tests occasionally, not predictably, show the behavior, specifically:

* `org.springframework.web.reactive.function.MultipartRouterFunctionIntegrationTests`, and 
*  `org.springframework.web.reactive.result.method.annotation.RequestMappingMessageConversionIntegrationTests`

### LINKED ISSUE #10357: EE10 `ServletChannelState` input FSM should be reviewed
**Jetty version(s)**
12.0.0

**Jetty Environment**
EE10

**Description**
While fixing https://github.com/eclipse/jetty.project/issues/10315, it became apparent that the implementation behind the FSM backing `HttpInput` should be reviewed entirely.

The impedance mismatch between the Jetty 10/11 `needContent()` / `produceContent()` contract vs the Jetty 12 `demand()` / `read()` one means the state checks and transitions need to be placed slightly differently in certain situations.

For instance, #10315 was about the fact that `needContent()` fills, parses and registers for fill interest if necessary while being idempotent; doing the same thing in EE10 requires calling `read()` then `demand()` if necessary, but also needs to take into account that `read()` must not be called while there is a pending demand as the idempotency is gone from the EE10-backing API. Fixing that bug required checking that when using the blocking API, `ServletInputStream.isReady()` must not call `read()` while the FSM is in `UNREADY` state otherwise we would call `read()` during a pending demand. Fixing the bug required changing the state transitions so that `BlockingContentProducer` moves back to `IDLE` state when a demand has been serviced. This means the comments in `BlockingContentProducer.onContentProducible()` which describe this mechanism don't apply anymore to EE10 (`HttpChannelState.asyncError()` went away for instance) and the references to the tests covering this mechanism are stale too.

Another point requiring investigation is that some tests like `ProxyServletTest.testExpect100ContinueRespond100ContinueSomeRequestContentThenFailure` log the following warning when executed, while passing and being apparently correct:
```
java.lang.IllegalStateException: s=HANDLING rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.handling(ServletChannelState.java:357)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:462)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1264)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1251)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1276)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

All the state transitions both in blocking and unblocking modes, as well as test coverage (including using H2 / H3) should be re-assessed for EE10 as we know from experience that this FSM is very delicate.

### PR DESCRIPTION
**Pull request by sbordet**
…Exception.

Made sure that when HttpServletRequest.isReady() returns false, it is possible to call it again without getting an exception.

### CODE REVIEW

**Review by lorban — APPROVED** [review]

**Review by gregw — DISMISSED** [review]

**Comment by lorban** [comment]
`ProxyServletTest.testExpect100ContinueRespond100ContinueSomeRequestContentThenFailure` now fails because of this change, but I think the test was mistakenly passing before it.

This requires more investigation; I'm going to spend some time trying to understand what's going on.

**Review by lorban — CHANGES_REQUESTED** [review]
`testExpect100ContinueRespond100ContinueSomeRequestContentThenFailure` must be fixed

**Comment by lorban** [comment]
@sbordet I committed a patch that fixes the `testExpect100ContinueRespond100ContinueSomeRequestContentThenFailure` proxy test:

but it still logs this warning:

```
java.lang.IllegalStateException: s=HANDLING rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.handling(ServletChannelState.java:357)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:462)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1264)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1251)
	at org.eclipse.jetty.server/org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1276)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

and the comments in `BlockingContentProducer.onContentProducible()` are outdated, so I think this FSM should be reviewed entirely IMHO, possibly in another issue if this solves #10315.

**Review by lorban — APPROVED** [review]
LGTM despite the need for a revisit.

**Comment by lorban** [comment]
https://github.com/eclipse/jetty.project/issues/10357 has been filed to track the assessment of the mechanism backing this feature.

**Pull request merged**
