### PR TITLE
Issue #9502 Configure sbom plugin to produce sbom for jetty-home and include it in the distribution 

### PR DESCRIPTION
**Pull request by olamy**
https://github.com/jetty/jetty.project/issues/9502

### CODE REVIEW

**Comment by joakime** [comment]
This seems sane, and configurable.
I'm ok with this.

**Review by jmcc0nn3ll — DISMISSED** [review]
Looks fine to me, no way to set the cyclonedx.skip at the top level and just turn it on once?

if not, ship it

**Review by joakime — DISMISSED** [review]
As long as Eclipse Foundation is happy with this, then this is fine with me.

**Comment by olamy** [comment]
> Looks fine to me, no way to set the cyclonedx.skip at the top level and just turn it on once?
> 
> if not, ship it

in fact now we generate sbom only for jetty-home, I can remove all the `<cyclonedx.skip>true</cyclonedx.skip>`

**Comment by jmcc0nn3ll** [comment]
> > Looks fine to me, no way to set the cyclonedx.skip at the top level and just turn it on once?
> > if not, ship it
> 
> in fact now we generate sbom only for jetty-home, I can remove all the `<cyclonedx.skip>true</cyclonedx.skip>`

perfect, clean that up and merge it

**Comment by olamy** [comment]
@jmcc0nn3ll @joakime I will approval again as changes have dismissed your previous approvals.

**Review by jmcc0nn3ll — APPROVED** [review]
Lgtm

**Pull request merged**
