### PR TITLE
Fix NPE in ContextHandler.isShutdown

### PR DESCRIPTION
**Pull request by raimohanska**
Initialize the _availability variable properly, as discussed in #1236.

Also, fix a Javadoc comment, add a simple test.

### CODE REVIEW

**Comment by raimohanska** [comment]
There you are! Are you serious about having to sign contracts before accepting my contribution? Just take the fix, pls :)

**Comment by joakime** [comment]
@raimohanska its not our rules, its Eclipse Legal rules (aka, the Lawyers).  We cannot accept patches without a CLA or ECA assigned.  Sorry.

**Comment by raimohanska** [comment]
Ok let's see what I can do about the lawyery stuff...

**Comment by gregw** [comment]
@raimohanska if you have no joy on the lawyery stuff, just say and I will re-implement a fix for the NPE.

**Comment by WalkerWatch** [comment]
@raimohanska Any luck on filling out the ECA? It's relatively easy and [you can find instructions here](https://www.eclipse.org/jetty/documentation/current/contributing-patches.html).

**Comment by raimohanska** [comment]
Yeah, I finally filled the ECA :) Now I guess I'll have to redo these commits to have them "signed off".

**Comment by raimohanska** [comment]
Okay, I've added the signed-off footers to the commits now.

**Comment by janbartel** [comment]
Thanks!

**Pull request merged**
