### PR TITLE
Bring back packageRoot parameter in jetty-jspc-maven-plugin

### LINKED ISSUE #3156: Bring back packageRoot parameter in jetty-jspc-maven-plugin
Being able to precompile jsp files in predefined java package name instead of the default jasper one is quite useful for people using minimal jetty and providing custom jsp container in it (like Eclipse Platform does). This parameter was removed in 9.1.0 for some reason.

### PR DESCRIPTION
**Pull request by akurtakov**
Fixes #3156 . First patch is a general cleanup the other one restores the packageRoot parameter implementation.

### CODE REVIEW

**Comment by olamy** [comment]
LGTM. Any chance you improve the current it tests with this change?

**Comment by akurtakov** [comment]
Can you point me to this it tests? I looked (briefly) but didn't spotted anything.

**Comment by olamy** [comment]
look at src/it directory. You can simply create a new maven project with this option enabled and do some assert with postbuild.groovy file

**Comment by janbartel** [comment]
@akurtakov the packageRoot param was removed along with a bunch of other parameters because I gave you access directly to the JspC instance's setters instead, avoiding the duplication and fragility of having to mirror changes to the JspC methods in the plugin's parameters.

So to set the package name for generated jsps, you would do:
```xml
<configuration>
  <jspc>
    <jspc>
        <package>com.foo.bar</package>
   </jspc>
</configuration>
```

I probably should have made that clearer in the documentation, I'll do that now.

Other than that, the code cleanups look fine - and yes, a test setup would be an added bonus :)

**Comment by akurtakov** [comment]
Thank you. I didn't figure that JspC is directly configurable that way. I will look into adding it test.

**Comment by akurtakov** [comment]
Removed the commit adding the packageRoot parameter and committed new one that adds it test setting jsp/package and verifying that the generated class file from the jsp is in the proper place.

**Pull request merged**
