### PR TITLE
Allow to externally provide 'daemon' parameter

### PR DESCRIPTION
**Pull request by ctron**
This change allows to provide the `daemon` parameter using a property
using `-Djetty.daemon` in addition.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

---

It looks like the file was checked in with CRLF line endings. I tried to keep it that way.

### CODE REVIEW

**Comment by ctron** [comment]
It seems there is some issue with the CI build which I don't understand. According to the Eclipse project handbook [1], copyright headers should be updated accordingly. Maybe I did miss the format this check expects.

[1] https://www.eclipse.org/projects/handbook/#ip-copyright-headers

**Comment by joakime** [comment]
> [WARNING] Missing header in: /opt/jenkins/workspace/jetty.project_PR-1303-SJRGOAXDJ3J6G6XCUFEYBH2XX74QV22M6MMWA5YDY6IS34IFHXJQ/jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyDeployWar.java

Jetty is a project that didn't start at Eclipse, so the eclipse handbook doesn't apply 100% (we have years of work before Eclipse, and dual-licensed header)

Check out the [header-template.txt](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/header-template.txt) in the root of the repository too.

Copy / Paste the header from an existing source file in the git repository (pay attention to the space after the header and before the `package` line too).

**Comment by ctron** [comment]
Ok .. so I will remove "and others" and that is necessary.

**Comment by ctron** [comment]
I don't really understand what is wrong now. The final output says:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by joakime** [comment]
This looks fine.

It should have probably been made against jetty-9.4.x branch tho.
the 'master' branch is for Jetty 10.x and is not stable.

**Comment by waynebeaton** [comment]
> Jetty is a project that didn't start at Eclipse, so the eclipse handbook doesn't apply 100%

Yes it does. The template there doesn't need to be used exactly (and is certainly different for a dual-licensed project), but the requirement to include "and others" still exists.

**Comment by joakime** [comment]
@waynebeaton in rereading what I wrote, yes, I agree that statement was poor wording on my part.

**Comment by ctron** [comment]
I can port this also to the 9.4 branch if you like. And we can add the "and others" then again.

**Comment by sbordet** [comment]
@ctron, we will cherry pick this change for other branches, no need for you to issue another PR. Thanks !

**Comment by ctron** [comment]
Ok cool. Will you also add "and others". I guess adding a separate PR for this is kind of overkill.

**Pull request merged**
