### PR TITLE
align maven plugin versions

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <oliver.lamy@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@olamy I don't think this is right. We should inherit the Maven Plugin versions from the main POM, not duplicating them in children POMs, otherwise they will always be out of sync.

**Comment by olamy** [comment]
This need to add a property for each maven plugin we use in both main pom and maven its.
well I can add that

**Comment by sbordet** [comment]
@olamy they cannot inherit from the main POM?

**Comment by olamy** [comment]
nope those it test poms doesn't know anything about the main pom.
And this is the goal as they must be like an "external" project.
I only need to use the same technique as used for surefire plugin version.

**Comment by joakime** [comment]
@sbordet these are integration test projects that our own maven plugins use.  
notice that these are part of the directory structure `jetty-maven-plugin/src/it/`

**Pull request merged**
