### PR TITLE
Added Sample for org.mariadb.jdbc.MariaDbPoolDataSource

### PR DESCRIPTION
**Pull request by softconex-github**
Added sample for Connection Pool from MariaDB

https://github.com/eclipse/jetty.project/pull/2820

### CODE REVIEW

**Comment by janbartel** [comment]
@softconex-github hi there, sorry its taken so long to get back to you. Seems like there is a problem with the ip validation: did you sign the Eclipse agreement?

**Comment by janbartel** [comment]
@softconex-github can you check your Eclipse Contributor Agreement? We need that in place before we can accept the PR.

**Comment by janbartel** [comment]
@softconex-github  can you sign the Eclipse Committer Agreement, or re-sign this commit with an identity that has signed the ECA? If this is not possible, we will regretfully have to abandon this PR, as we cannot accept non-ECA contributions.

**Comment by joakime** [comment]
Closing due to lack of verified Eclipse Committer Agreement (ECA).

Feel free to open a new PR with corrected Author and Signed-Off-By that relates to your email address that you had a signed ECA with.
See [`CONTRIBUTING.md`](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md) for details

**Pull request closed without merging**
