### PR TITLE
Issue #150: Ability to handle JAR directories in extraClasspath. 

### PR DESCRIPTION
**Pull request by i2shar**
In keeping with Java conventions[0], any directory paths ending in /* should be considered a JAR directory and all jars in that directory will be added (non recursively) to the classpath.

[0] https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html

Signed-off-by: Tushar Inamdar <tusharinamdar@hotmail.com>

### CODE REVIEW

**Comment by janbartel** [comment]
@i2shar any chance you can add the unit test for this new change to the pull request?

**Comment by gregw** [comment]
@janbartel @i2shar We wish to do a 9.4.x release this week, so would be good to merge this PR ASAP!

**Comment by i2shar** [comment]
Hello, I'll try to get the test case in soon. Thanks.

**Comment by i2shar** [comment]
@gregw @janbartel : I added a test case for the extraclasspath case. Kindly review.

(I updated my commit signature to comply with the Eclipse validation, but I guess this check needs to be rerun?)

**Comment by janbartel** [comment]
@i2shar  these changes look good. However, we need to the the Eclipse IP process happy. Can you check that your commits were signed (with commit -s) using the same identity that you use for Eclipse?

**Comment by i2shar** [comment]
@janbartel Couldn't get the Eclipse IP validation to work on this pull request, so created another one here: https://github.com/eclipse/jetty.project/pull/3325 in lieu of this. Will close this off.

**Comment by i2shar** [comment]
@joakime Thank you! Will keep in mind.

**Pull request closed without merging**
