### PR TITLE
Rename RetainableByteBufferPool to ByteBufferPool

### LINKED ISSUE #9284: Jetty 12: Removal of ByteBufferPool breaks AbstractConnector subclasses
**Jetty version(s)**
jetty 12.0.x commit ded18f523d7d1fbac6569256c9bb98aff89e0000

**Description**
The removal of ByteBufferPool and replacement with RetainableByteBufferPool in the constructor signature for AbstractConnector breaks subclasses of that class, such as junixsocket's [AFSocketServerConnector](https://github.com/kohlschutter/junixsocket/blob/f5ac19103b4c6245d89ce388af97bd95b97120bb/junixsocket-jetty/src/main/java/org/newsclub/net/unix/jetty/AFSocketServerConnector.java)

**How to reproduce?**
Implement a subclass of AbstractConnector with Jetty 11 as a dependency, then switch to 12.

### PR DESCRIPTION
**Pull request by kohlschuetter**
With issue #9166, ByteBufferPool was removed and replaced by RetainableByteBufferPool. Since ByteBufferPool was used by AbstractConnector, this change broke backwards compatibility with third-party connectors such as junixsocket-jetty.

Since there's no longer any other ByteBufferPool, rename the RetainableByteBufferPool interface, and thereby not only reinstate compatibility with existing third-party libraries but also save a few keystrokes.

https://github.com/eclipse/jetty.project/issues/9284

Signed-off-by: Christian Kohlschütter <christian@kohlschutter.com>

### CODE REVIEW

**Comment by joakime** [comment]
Related to #9072

**Comment by kohlschuetter** [comment]
For what it's worth, I used the following commands to rename these references:

```
gsed -E -i"" 's/\bRetainableByteBufferPool/ByteBufferPool/g' $(find . -name "*.java")
gsed -E -i"" 's/\bretainableByteBufferPool/byteBufferPool/g' $(find . -name "*.java")
gsed -E -i"" 's/\bgetRetainableByteBufferPool/getByteBufferPool/g' $(find . -name "*.java")
gsed -E -i"" 's/\bsetRetainableByteBufferPool/setByteBufferPool/g' $(find . -name "*.java")
cd ./jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/
git mv RetainableByteBufferPool.java ByteBufferPool.java
cd -
```

I then temporarily added `impsort-maven-plugin` to `pom.xml` to reorganize the now-renamed imports (also see #9304):

1. Add the profile to `pom.xml`:
```
    <profile>
      <id>reformat</id>
      <properties>
        <skipTests>true</skipTests>
        <checkstyle.skip>true</checkstyle.skip>
        <enforcer.skip>true</enforcer.skip>
        <license.skip>true</license.skip>
        <spotbugs.skip>true</spotbugs.skip>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>net.revelc.code</groupId>
            <artifactId>impsort-maven-plugin</artifactId>
            <version>1.8.0</version>
            <configuration>
              <groups>java,*</groups>
              <staticGroups>*</staticGroups>
              <excludes>
                <exclude>**/module-info.java</exclude>
              </excludes>
              <compliance>14_PREVIEW</compliance>
              <staticAfter>true</staticAfter>
              <removeUnused>false</removeUnused>
            </configuration>
            <executions>
              <execution>
                <id>sort-imports</id>
                <goals>
                  <goal>sort</goal><!-- runs at process-sources phase by default -->
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
```

2. Reorganize imports

```
mvn process-sources -Preformat
```

**Comment by kohlschuetter** [comment]
"502 Bad Gateway" in Java 19 unit tests, probably unrelated, since Java 17 tests pass

**Comment by joakime** [comment]
@olamy Seems that we are having DNS issues on our CI machine.

The 502 Bad Gateway is due to the proxy being unable to resolve "www.eclipse.org" ...

```
2023-02-02 22:49:08.262:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 2023-02-02 22:49:08.262:DEBUG:oejepP.JavadocTransparentProxy:qtp1196765369-30: 1187524360 rewriting: http://localhost:35951/proxy/current/ -> https://www.eclipse.org/jetty/javadoc/jetty-10/index.html?overview-summary.html/current/
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 2023-02-02 22:49:08.287:DEBUG:oejepP.JavadocTransparentProxy:qtp1196765369-30: 1187524360 proxying to upstream:
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: GET /proxy/current/ HTTP/1.1
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: User-Agent: Jetty/12.0.0-SNAPSHOT
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: Host: localhost:35951
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: Accept-Encoding: gzip
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: HttpRequest[GET /jetty/javadoc/jetty-10/index.html HTTP/1.1]@a83dae9
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: User-Agent: Jetty/12.0.0-SNAPSHOT
2023-02-02 22:49:08.287:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: Accept-Encoding: gzip
2023-02-02 22:49:08.288:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: Host: www.eclipse.org
2023-02-02 22:49:08.288:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: Via: 1.1 jenkins-slave-6sczs
2023-02-02 22:49:08.288:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: X-Forwarded-For: 127.0.0.1
2023-02-02 22:49:08.288:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: X-Forwarded-Proto: http
2023-02-02 22:49:08.288:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: X-Forwarded-Host: localhost:35951
2023-02-02 22:49:08.288:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: X-Forwarded-Server: 127.0.0.1
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 2023-02-02 22:49:08.494:DEBUG:oejepP.JavadocTransparentProxy:qtp1196765369-31: 1187524360 proxying failed
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: java.net.UnknownHostException: www.eclipse.org: Name or service not known
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1059)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1668)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1003)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1658)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1524)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:165)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at org.eclipse.jetty.util@12.0.0-SNAPSHOT/org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
2023-02-02 22:49:08.494:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 	at java.base/java.lang.Thread.run(Thread.java:1589)
2023-02-02 22:49:08.508:INFO :oejth.JettyHomeTester:ConsoleStreamer/STDERR: 2023-02-02 22:49:08.508:DEBUG:oejepP.JavadocTransparentProxy:qtp1196765369-31: 1187524360 proxying complete
```

**Comment by olamy** [comment]
that's weird we can resolve github.com there is no reason we can't resolve eclipse.org

**Comment by olamy** [comment]
well but on the other side being dependant of external service is not good for unit test ;)

**Comment by gregw** [comment]
This is now clashing with the JPMS fixes that have been merged.

**Comment by kohlschuetter** [comment]
@gregw done. When do you think can this be merged?

**Comment by gregw** [comment]
@sbordet @lorban will defer to you guys on this one.

**Comment by sbordet** [comment]
Approved.
I also changed all references to `RetainableByteBufferPool` in fields, tests, javadocs, documentation, etc.

**Pull request merged**
