### PR TITLE
quic TLS mutual authentication

### LINKED ISSUE #9397: HTTP/3 encryption configuration
**Jetty version**
11.0.13
**Java version**
17.0.5

**Question**
I wanted to get some more information about encryption configuration for HTTP/3.  From what I was able to find, it appears that the server certificate and private key are configured via SslContextFactory.Server key store on the HTTP3ServerConnector.  The private key and certificate of the keystore are passed via the QuicheConfig in [QuicServerConnector.newQuicheConfig()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-server/src/main/java/org/eclipse/jetty/quic/server/QuicServerConnector.java#L211) to [JnaQuicheConnection.buildConfig()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-quiche/quic-quiche-jna/src/main/java/org/eclipse/jetty/quic/quiche/jna/JnaQuicheConnection.java#L121).  For the server this is translated to the following native Quiche calls:

- load_priv_key_from_pem_file
- load_cert_chain_from_pem_file

What I did not see was how to load trust into the server connection.  The [Quiche documentation](https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_verify_locations_from_file) shows the call load_verify_locations_from_file, but I do not see it implemented.  Is there an alternate way to set this configuration for the server?

For the client, I am unclear on how to set the certificate, private key, or trust.  Setting the SslContextFactory.Client set via http3Client.getClientConnector().setSslContextFactory() does not appear to take effect.  More specifically [ClientQuicConnection.onOpen()](https://github.com/eclipse/jetty.project/blob/jetty-11.0.x/jetty-quic/quic-client/src/main/java/org/eclipse/jetty/quic/client/ClientQuicConnection.java#L80) does not configure certificate, private key, or trust.  Is there an alternate way to set these configurations for the client?

My goal is to be able to set a certificate, private key, and trust for the client and server and prove via test that a trusted connection is accepted and an untrusted connection is rejected.  Here is a [sample project](https://github.com/mluckam/jetty-http3-example
) with unit tests.

### PR DESCRIPTION
**Pull request by mluckam**
The quiche library allows for the client and server to set a [private key](https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_priv_key_from_pem_file), [public certificate](https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_cert_chain_from_pem_file), and [trusted CAs](https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_verify_locations_from_file).  The following functionality already existed in jetty:

- server configuration of private key
- server configuration of public certificate

This PR adds functionality to allow for the following:

- client configuration of private key 
- client configuration of public certificate
- client configuration of trusted CAs
- server configuration of trusted CAs

The addition of this functionality was also previously discussed in the following enhancement #9397.

### CODE REVIEW

**Comment by joakime** [comment]
@mluckam can you add a readme to `src/test/resources/certs/` explaining the purpose/role of the various certs, and how to recreate them if needed (command lines)?

**Comment by joakime** [comment]
Build fails for ...

```
[INFO] --- license-maven-plugin:4.1:check (check-java-headers) @ jetty-project ---
[INFO] Checking licenses...
[WARNING] Missing header in: /home/jenkins/agent/workspace/jetty.project_PR-9490/jetty-quic/quic-quiche/quic-quiche-common/src/test/java/org/eclipse/jett/quic/quiche/SSLTrustedCertificatesTest.java
[WARNING] Missing header in: /home/jenkins/agent/workspace/jetty.project_PR-9490/jetty-quic/quic-quiche/quic-quiche-common/src/test/java/org/eclipse/jett/quic/quiche/SSLKeyPairTest.java
[WARNING] Missing header in: /home/jenkins/agent/workspace/jetty.project_PR-9490/jetty-quic/quic-quiche/quic-quiche-common/src/main/java/org/eclipse/jetty/quic/quiche/SSLTrustedCertificates.java
```

Also, what's this `org/eclipse/jett/quic` tree?  is that a typo? (should be `/jetty/` not `/jett/`)

**Comment by mluckam** [comment]
@joakime appreciate the feedback.  Updates have been made. `src/test/resources/certs/ ` now has the script used to generate the certificates along with a README to explain the role of each certificate.

**Comment by joakime** [comment]
The testcase `org.eclipse.jetty.quic.client.End2EndClientTest.testUntrustedClientHTTP2()` fails on all 3 JDKs still.

See: https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-9490/2/tests

**Comment by mluckam** [comment]
I attempted to reproduce the failed test by using each of the 3 java versions as well as the same maven version (3.8.6) and options as provided by the jenkins output.  Here is the command I used for comparison.

```
mvn -Pci -V -B -e clean install --projects jetty-quic/quic-client
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /home/mluckam/.sdkman/candidates/maven/current
Java version: 17.0.6, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.15-200.fc37.x86_64", arch: "amd64", family: "unix"
```

Unfortunately I was unable to reproduce the failed test.  To try something I'll move the setting of the SslContextFactory on the ClientConnector earlier in the setup and double the timeout to 10 seconds even though 5 seconds should be ample time.  Any thoughts on what may be causing this issue?

**Comment by sbordet** [comment]
Whoa, 44 files!

Don't we just need to pass a couple of paths to Quiche?
Also, can we generate all the PEMs on-the-fly rather than storing them in the repository?

I was more under the impression that this PR would be much simpler, as we do not want to test whether Quiche implements properly client-cert validation. We just want to map the calls from Jetty to Quiche, no?

**Comment by mluckam** [comment]
Looking at the number of files a large majority of them (28/44) are keys, certificates, and keystores.  Searching the project there are 30+ keystore.p12 files.  Would it make sense to consolidate a set of keys, certificates, and keystores into a module that could be shared amongst tests?  Possibly something like a test-resources module.  Out of scope for this change but something that may benefit the project.

As for the unit tests, utilizing the End2EndClientTest was for me a simple way to ensure the configuration had been passed appropriately by verifying functionality.  If this is too high level a test, an alternate testing strategy can be developed.  Maybe testing the next level down with the ClientQuicConnection and QuicServerConnector?  I am open to suggestions.

**Comment by zugazagoitia** [comment]
@mluckam I have a use case that is currently unsupported and might be fixed by your PR. 
I use the [Hakky54/sslcontext-kickstart](https://github.com/Hakky54/sslcontext-kickstart) library to setup my identity/trust configuration and generate a `SslContextFactory.Server` for my Jetty server connectors, this enables me to provide support for  `P7B`, `DER`, `P12`, `PEM` and `JKS` files using the same API while having a common TLS configuration.

I currently can't use the HTTP/3 connector, since my certificates are loaded into memory and converted as needed before creating the `SslContextFactory`, and `QuicServerConnector` requires a keystore file to be present in order to work, ignoring my certificates.

Will [this change](https://github.com/eclipse/jetty.project/pull/9490/files#diff-d70991dcfcf95d474b482ad2c6bb2de56a4ccfd24d40917497ae6a037ba9b0b9R163) solve this? If not, could you consider it? I'll be happy to help if there's something to be done. Thanks for your time.

**Comment by mluckam** [comment]
@zugazagoitia it does appear that a side effect of this change is removing the requirement for key stores to be files.  Glad to hear that it would resolve issues for you as well.

The current feedback on this PR is to reduce the number of files in the PR.  To do this and still unit test, I have created another PR to use shared key resources, #9645.

Another issue with this PR is the unit test `org.eclipse.jetty.quic.client.End2EndClientTest.testUntrustedClientHTTP2()` fails on the build server, but I am unable to reproduce locally (see above comments).  If you want to take a look and see if you can correct this unit test that would helpful.

**Comment by zugazagoitia** [comment]
> Another issue with this PR is the unit test `org.eclipse.jetty.quic.client.End2EndClientTest.testUntrustedClientHTTP2()` fails on the build server, but I am unable to reproduce locally (see above comments).  If you want to take a look and see if you can correct this unit test that would helpful.

I've had a similar issue myself testing the exact same setup (untrusted http2), and the issue ended up being the JVM. Different JVMs might produce different exceptions for this same case, so `temurin` might differ from your redhat `openjdk`.

I tried to assert the exception message after catching any `Exception`, but it also differed. In the end I just asserted that any exception was thrown.

**Comment by mluckam** [comment]
I used the temurin-17-jdk today and was unable to reproduce the issue locally.  @zugazagoitia are you able to reproduce the issue?

**Comment by zugazagoitia** [comment]
I could reproduce it, using `OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)` on aarch64 (Apple Silicon M2 pro) running MacOS Ventura 13.3.1

<details><summary>Log</summary>
<p>

```log
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.743 s <<< FAILURE! - in org.eclipse.jetty.quic.client.End2EndClientTest
[ERROR] org.eclipse.jetty.quic.client.End2EndClientTest.testUntrustedClientHTTP2  Time elapsed: 5.536 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected type, expected: <java.nio.channels.ClosedChannelException> but was: <java.net.SocketTimeoutException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertInstanceOf.assertInstanceOf(AssertInstanceOf.java:49)
	at org.junit.jupiter.api.AssertInstanceOf.assertInstanceOf(AssertInstanceOf.java:31)
	at org.junit.jupiter.api.Assertions.assertInstanceOf(Assertions.java:3572)
	at org.eclipse.jetty.quic.client@11.0.15-SNAPSHOT/org.eclipse.jetty.quic.client.End2EndClientTest.testUntrustedClientHTTP2(End2EndClientTest.java:264)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   End2EndClientTest.testUntrustedClientHTTP2:264 Unexpected type, expected: <java.nio.channels.ClosedChannelException> but was: <java.net.SocketTimeoutException>
[INFO] 
```
</p>
</details> 

I fixed it like this, just checking for any Exception to be thrown. Not pretty but it's needed since the exception differs between OSs and JVMs. If you find a better solution I'll also update my tests!

https://github.com/javalin/javalin-ssl/commit/25f58d94cc3be1efa33c7b7b14da9cfa5360be48#diff-24d9506d74bbaf1b0f2281a76bf4f6c570cc431a9c541b91abe0c007f9e45841

**Comment by mluckam** [comment]
I was able to reduce the number of files from 44 to 24 by removing redundant or unused keys and certificates.  All unit tests pass with the advice of @zugazagoitia.  @sbordet @joakime thoughts on the update to this PR?

**Comment by lorban** [comment]
@mluckam I've linked the Jetty trustore config to the Quiche trustore config, plus many other certificate-related tasks, my work is at https://github.com/eclipse/jetty.project/pull/9788. It's against Jetty 10 but I'm reasonably confident this PR can be applied as a patch cleanly on 11.

Your opinion and eventually your testing is welcome! Thanks!

**Comment by lorban** [comment]
Replaced by https://github.com/eclipse/jetty.project/pull/9788

**Pull request closed without merging**
