### PR TITLE
Issue #2556 - bad "file:" scheme present in Xml usage of "jetty.base" and "jetty.home" properties

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@joakime method `setJettyStandardIdsAndProperties()` performs additional things after the code you fixed and they look exactly similar to what you already fixed, so I wonder if they should all use `Path` instead of `Resource` ?

E.g.:

```java
getProperties().put("jetty.webapps.uri",normalizeURI(webapp.getURI().toString()));
```

So if in XML one references this property, it will get the same `file:` error reported in #2556, no ?

**Comment by joakime** [comment]
@sbordet the use of `jetty.webapps.uri` (note the "uri" suffix) means that they **do** want the URI version, even with `file:` included.

**Comment by sbordet** [comment]
@joakime please review `jetty.webapp` and `jetty.webapps` and `jetty.webapp.uri` few lines below the ones you changed in this PR.

**Comment by joakime** [comment]
Tests pass, merging.

**Pull request merged**
