### PR TITLE
Applied skeletal implementation to interface migration automated refactoring

### PR DESCRIPTION
**Pull request by khatchad**
This is a semantics-preserving automated refactoring that migrates existing method implementations in classes to the corresponding implemented interface methods as `default` methods. The tool **does not** add new code; it only rearranges *existing* code.

- We are evaluating a research prototype automated refactoring Eclipse plug-in called [Migrate Skeletal Implementation to Interface](https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring). We have applied the tool to your project in the hopes of receiving feedback.
- The approach is very conservative. Specifically, it only performs a migration if the target interface is unambiguous. That may mean that not all changes that can be made were made. Please feel free to continue the refactoring manually if you wish.
- We only migrated methods declared in abstract classes. We believe such methods to be likely suitable default methods in corresponding interfaces.
- The source code should be semantically equivalent to the original.

Thank you for your help in this evaluation! Any feedback you can provide would be very helpful. In particular, we are interested if *each* of the proposed changes are helpful or not. I've also attached a [precondition failure](https://github.com/eclipse/jetty.project/files/385310/failed_preconditions.csv.zip) report FYI.

### CODE REVIEW

**Comment by gregw** [comment]
@khatchad Note that we've just applied continuous integration, and master is not currently passing all it's tests, this PR has actually broken the build.   If you follow the jenkins link above you will see that it has changed the name of an argument in the Logger, but has not changed the matching javadoc.  This breaks our javadoc build.

So your tool probably needs to be updated to handle javadoc as well... or at least to not change argument names!

**Comment by khatchad** [comment]
@gregw, thank you for the feedback. I see, the build is broken but not due to functional differences but javadoc warnings.

Indeed, dealing with javadoc is something we have not completely implemented and have as planned future work (see https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/issues/20). 

As for the alteration of parameter names, the tool does this when there is a discrepency of parameter names between the source and target methods. Either we need to change the target method parameters to match that of the source or rename all references within the method body to match that of the target parameters. We chose the former as we thought it would be the least invasive thing to do (see https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/issues/148). However, we did not think to also change the javadoc (filed https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring/issues/168).

I've committed a manual workaround in e5482ae7f587423a909c4ece45de86db483821d6. Thanks again for the feedback and please let us know if there are any more issues.

**Comment by gregw** [comment]
I'm closing this with out applying.  On reflection, we cannot really justify such changes for marginal gain.  If we were not such a base project for so many others, then such a refactor would be OK, but we would break too many other things.

**Comment by khatchad** [comment]
Thanks for the consideration and feedback, @gregw. If you are worried about breaking clients, we could revert commit 8c8fd5bdce5075f494592ff83b1bde9ed9a6bfeb that removes the now empty skeletal implementation classes. Please let us know if you are interested in the future. Thank you again.

**Comment by gregw** [comment]
Oh I like that the tool puts each mutation into a different commit.  But we will still not apply even without that... at least not at this phase of development when we are mostly working on 9.4 and merging forward to master.  In a few months when work moves mostly to master, I may reconsider.

**Comment by khatchad** [comment]
Sounds good, @gregw.

**Pull request closed without merging**
