### PR TITLE
remove jetty-annotations dependency from websocket-jetty-server

### PR DESCRIPTION
**Pull request by olamy**

### CODE REVIEW

**Review by timja — DISMISSED** [review]

**Review by joakime — CHANGES_REQUESTED** [review]
Missed a few other dependencies.

* `modules/websocket-jetty.mod` also depends on `annotations` module.
   It should probably depend on `webapp` instead.
* `org.eclipse.jetty.websocket.server.config.JettyWebSocketConfiguration` also depends on `AnnotationConfiguration`.
   Be careful, this will likely put the `JettyWebSocketConfiguration` in a different location in the Configuration ordering.
   We should probably depend on `WebAppConfiguration` instead here, as there's still a `ServletContainerInitializer` to worry about.

**Comment by olamy** [comment]
ah yup that's more changes...
but not so trivial.
I will resume after holidays.

**Comment by joakime** [comment]
@olamy this needs the update you mentioned on June 23rd.

**Comment by joakime** [comment]
@olamy bump

**Comment by joakime** [comment]
@olamy there's an ECA issue on this PR.
Can you fix it please?

**Comment by joakime** [comment]
Closing, as @olamy has not committed from his correct email address.

**Comment by olamy** [comment]
replaced by https://github.com/eclipse/jetty.project/pull/10316

**Pull request closed without merging**
