### PR TITLE
Issue #4148 - config for jetty specific settings with javax WebSockets

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #4148**

Jetty specific websocket settings such as autoFragment, maxFrameSize, outputBufferSize and inputBufferSize can now be configured through `EndpointConfig.getUserProperties()` or `Session.getUserProperties()`. Properties like `org.eclipse.jetty.websocket.autoFragment` can be set and this will call the setter on the `CoreSesion`.

`EndpointConfig.getUserProperties()` and `Session.getUserProperties()` now share the same map instance (the map was being copied in `JavaxWebSocketSession` before).

### CODE REVIEW

**Comment by joakime** [comment]
`BasicEndpointConfig` is the equivalent of the `BufferUtil.EMPTY_BUFFER` or `Collections.emptyList()`.
It only exists to have an empty `EndpointConfig` for where `EndpointConfig` is mandated to be never null.
If we could do a simple `new EndpointConfig()` then this class would have no reason to exist.

**Comment by lachlan-roberts** [comment]
@gregw now every one of our implementations of `EndpointConfig` is a wrapper. I have also removed the `BasicEndpointConfig` and now we ask the `FrameHandlerFactory` to create us a basic one and it will create either a `BasicClientEndpointConfig` or a `BasicServerEndpointConfig`.

**Comment by lachlan-roberts** [comment]
@gregw Graphic of the EndpointConfig hierarchy now.

EndpointConfig

**Comment by joakime** [comment]
Something seems off with `PathParamServerEndpointConfig`.
That used to be a wrapper of it's own, applied to any existing `ServerEndpointConfig` type during upgrade if a Path Param is in use.

* API Implementation Default ServerEndpointConfig
* Jetty BasicServerEndpointConfig (for server non-annotated endpoints added to server container without an endpoint config)
* Jetty AnnotatedServerEndpointConfig (for server annotated endpoints added to a server container without an endpoint config)
* App custom ServerEndpointConfig used during add of endpoint to server container

Is this still the case?

**Comment by joakime** [comment]
Lets say you have the following use case, where an annotated endpoint is automatically added, and a server initialization step adds the same annotated endpoint class using a ServerEndpointConfig with slightly different configuration...

``` java
    @ServerEndpoint(value = "/my/{end}/{point}", 
        subprotocols = "my", 
        encoders = MyStringEncoder.class, 
        configurator = MyConfigurator.class)
    public static class MyEndpoint
    {
        private String handshakePath;

        public void onOpen(EndpointConfig endpointConfig)
        {
            handshakePath = (String)endpointConfig.getUserProperties().get("X-MyConfigurator-Path");
        }

        public String onMessage(String msg, @PathParam("end") String end, @PathParam("point") String point)
        {
            return String.format("[end=%s,point=%s,path=%s,msg=%s]", end, point, handshakePath, msg);
        }
    }

    public static class MyConfigurator extends ServerEndpointConfig.Configurator
    {
        @Override
        public void modifyHandshake(ServerEndpointConfig sec, HandshakeRequest request, HandshakeResponse response)
        {
            sec.getUserProperties().put("X-MyConfigurator-Path", request.getRequestURI().getRawPath());
        }
    }

    public static class MyInit implements ServletContextListener
    {
        @Override
        public void contextInitialized(ServletContextEvent sce)
        {
            ServerContainer container = (ServerContainer)sce.getServletContext().getAttribute(ServerContainer.class.getName());
            ServerEndpointConfig endpointConfig = ServerEndpointConfig.Builder
                .create(MyEndpoint.class, "/{end}/my/{point}")
                .subprotocols(Arrays.asList("end"))
                .build();
            try
            {
                container.addEndpoint(endpointConfig);
            }
            catch (DeploymentException e)
            {
                throw new RuntimeException("Unable to add endpoint alt: " + MyEndpoint.class, e);
            }
        }

        @Override
        public void contextDestroyed(ServletContextEvent sce) { }
    }
```

What ServerEndpoints would exist?
What would their EndpointConfigs look like? (i'm interested in url-pattern, subprotocols, configurators for each deployed server endpoint)

What I would expect ...

1. MyEndpoint.class
   uriTemplate = "/my/{end}/{point}"
   subprotocols = [ "my" ]
   encoders = [ MyStringEncoder class reference ]
   configurator = MyConfigurator class reference
2. MyEndpoint.class
   uriTemplate = "/{end}/my/{point} (from manual endpoint config)
   subprotocols = [ "end" ]  (from manual endpoint config)
   encoders = [ MyStringEncoder class reference ]  (from annotation)
   configurator = MyConfigurator class reference  (from annotation)

This is because the annotation establishes the "default" EndpointConfig for that class, and the ServerEndpointConfig.Builder just overrides specific values from that annotation, if you don't declare the value then it remains the value seen on the annotation.

**Comment by lachlan-roberts** [comment]
@joakime this refactor of `EndpointConfig` was not designed to change the existing behaviour and so it should be exactly the same behaviour as before.

`PathParamServerEndpointConfig` is still used as a wrapper which also gives the pathParam map.
The change is that all our implementations are wrappers that eventually wrap the API Implementation Default `EndpointConfig`.

I agree that using the `ServerEndpointConfig.Builder` to override specific values from the annotation should work like that, but I have tested it and it is not working properly before or after these changes.

**Comment by lachlan-roberts** [comment]
@joakime I have opened a separate issue for that. see #4407

**Comment by lachlan-roberts** [comment]
@gregw can I get a re-review

**Pull request merged**
