### PR TITLE
Avoid NPE when the websocket session is not created

### PR DESCRIPTION
**Pull request by azurvii**

### CODE REVIEW

**Comment by azurvii** [comment]
I could not make the `eclipsefdn/eca` check happy.

I logged in via the `Details` link and signed / accepted / OK'ed the ECA, and clicked `Revalidate`. The check is still off. It seems the anonymized email address reported by github is not matching the email address of my eclipse login. I have no intent to change my github setting.

If this change is deemed worthy, some one who could submit a checks-passing PR please help to take this forward, and possibly for other branches as well (e.g. 10.x, etc.).

Thanks.

**Comment by lachlan-roberts** [comment]
@azurvii if you don't want to fix your ECA I can just open a new PR with this change for you.
This change will need to instead been done in the `10.0.x` branch so it can be merged forward to `11.0.x`.

**Comment by lachlan-roberts** [comment]
Replaced by PR #7294.

**Comment by joakime** [comment]
> I could not make the `eclipsefdn/eca` check happy.

It looks like you submitted this via the github UI, as the `From` on the commit https://github.com/eclipse/jetty.project/pull/7293/commits/7541ad44e49f1b4c9c076dba9e34b0efef852eba
Shows `<github-user-id>@users.noreply.github.com`.

It is not possible for a noreply user from github.com to have a signed ECA.

That commit also lacks the `Signed-Off-By` signature on the commit that the command line `git -s` adds, this is a requirement to satisfy the https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin portion of the ECA check.

Using the gihub UI to created edits for submitted PRs doesn't convey the necessary legal handover stating "I did this", in the eyes of the Eclipse Legal.

**Comment by azurvii** [comment]
Thanks @lachlan-roberts for moving this forward, and including the guard for `remote` as well.

Thanks @joakime for the explanation and pointers. I'll take a look at them. I did use the github UI, but I'd still prefer the github email if I were to use `git`.

**Pull request closed without merging**
