### PR TITLE
Fix authn issues in LdapLoginModule

### PR DESCRIPTION
**Pull request by apyshko**
Current implementation of the LdapLoginModule has several bugs and issues preventing the user to be authenticated correctly.

### CODE REVIEW

**Comment by joakime** [comment]
Can you [add/update your CLA](https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=56375c4876e0e) on the Eclipse Side?  
We cannot accept this pull request without it.

**Comment by apyshko** [comment]
Hello,

I've just signed the CLA but couldn't find the way to resubmit the pull
request.
Only the "Close pull reqest" button is available.

**Comment by joakime** [comment]
Confirmed.

@apyshko now shows up as having a valid CLA on file according to
https://projects.eclipse.org/user/cla/validate

**Comment by joakime** [comment]
*kicks validation bot*

**Comment by jmcc0nn3ll** [comment]
The commits need to be repushed with the signed-off language in the commit themselves.  Might want to squash them while you are at it.

Could you amend these commits with --signoff and force a push into your repo and that should trigger the ip check again?  

FYI, the actual commit message on the pull request must have something like the following for the ip validation check to work, it isn't enough that you use the same email address here and at eclipse.

Signed-Off-By: <email>

**Comment by jmcc0nn3ll** [comment]
took patch and massaged into commit 4bf885c

**Pull request closed without merging**
