### PR TITLE
Issue #5883 - force LC_ALL envvar for tests

### LINKED ISSUE #5883: FileSystemResourceTest.testAccessUniCodeFile fails on *nix when LANG env var does not contain some UTF flavor
**Jetty version**
9.4.x, 10.0.x, 11.0.x

**Java version**
1.8, 11, probably newer ones too

**OS type/version**
Linux, probably all other *nix flavors too

**Description**
When the LANG env var is absent or is set to "C" the JVM is unable to read files that contain non-ASCII characters in their name.  Since FileSystemResourceTest.testAccessUniCodeFile tests exactly this behavior, the build should make sure that the environment is properly set to make sure it won't fail on a mis-configured machine.

### PR DESCRIPTION
**Pull request by lorban**
Closes #5883

### CODE REVIEW

**Review by sbordet — APPROVED** [review]

**Comment by joakime** [comment]
I have worries about this change.
Is `en_US.UTF-8` available on all JVM runtimes? (it could be a mandated support feature for OpenJDK, is that a true assumption?)

**Comment by sbordet** [comment]
> Is en_US.UTF-8 available on all JVM runtimes? (it could be a mandated support feature for OpenJDK, is that a true assumption?)

I don't think it has to do with JVMs at all.

It's something at the OS level - if it's supported good, otherwise (e.g. Windows) who cares.
But if it's supported, at least we don't break the tests.

**Comment by joakime** [comment]
This only changes `LANG` env variable.
What about the other ones?

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by sbordet** [comment]
@joakime the other env variables don't matter.

**Comment by lorban** [comment]
@joakime So far, I figured that those variables control the way `libc` is going to handle character conversion, and that is being used internally by the JVM to transform a java `String` into a C `char *` before giving it to the OS' filesystem system calls.

Those are all standard and documented here: https://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html

The interesting bits I can get from the OpenGroup doc is that `LC_ALL` has precedence over `LC_CTYPE` which itself has precedence over `LANG`, and those three seem to be (and should be?) the only ones impacting what the JVM does w.r.t filename conversion from java to C.

**Review by joakime — APPROVED** [review]
LGTM

**Review by olamy — APPROVED** [review]

**Pull request merged**
