### PR TITLE
Issue eclipse#3361 - added synchronization to updates to handler collections

### PR DESCRIPTION
**Pull request by axeluhl**
Here is a suggestion that we tested successfully for our configuration and that therefore for us fixes issue #3361.

### CODE REVIEW

**Comment by joakime** [comment]
You'd also need to synchronize `getHandlers()` and `handle()` if we go down this path.
I think using `synchronized` modifiers on the methods will be insufficient.

**Comment by axeluhl** [comment]
Yes, synchronizing setHandlers sounds like a good idea, too, specifically because of the updateBeans handling at the end of the method. For the override in ContextHandlerCollection I also agree additional synchronization is needed because of the mapContexts() method.

For the getHandlers method I don't think synchronization is needed. It only reads the _handlers reference. See https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.7.

**Comment by axeluhl** [comment]
> I think using `synchronized` modifiers on the methods will be insufficient.

Why do you think so? Are you worried about lack of parallelism? My take is that the problem we were experiencing was due to the non-atomic updates to the _handlers array which create a copy first, then add to the copy, then set the _handlers reference to the new copy. For us it was important to ensure that this sequence (read/create/set) happens atomically, and that IMHO is ensured now by using synchronized on those methods.

**Comment by joakime** [comment]
Alternate PR #3372 opened by @gregw

**Comment by gregw** [comment]
oops sorry, I only saw the issue and not the PR.    I think we need a touch more than the synchronisation as we also need to improve the way we are using the volatile fields

**Comment by gregw** [comment]
closing in favour of #3372.  Thanks regardless for the PR and issue report.

**Comment by axeluhl** [comment]
Still interested in the stack trace?

**Pull request closed without merging**
