### PR TITLE
Removing SecurityManager in prep of JEP411

### PR DESCRIPTION
**Pull request by joakime**
Removing the usages of deprecated (and slated for removal) methods and classes defined in JEP-411.

### CODE REVIEW

**Review by sbordet — COMMENTED** [review]
There are `SecurityManager` direct usages that it's ok to remove; fine with that.

There are `doPrivileged()` calls that I think were only used to "hide" operations that required permissions (e.g. load the logging properties) and that is ok to remove; fine with that.

There are `doPrivileged()` calls that were done to "cut" the `AccessControlContext` that was captured, which otherwise was retaining `ClassLoader` instances; I don't think it's ok to remove those, but I may be wrong.
If it's not ok, then perhaps try reflection?

@janbartel?

**Comment by janbartel** [comment]
@sbordet @joakime see my comment over here https://github.com/eclipse/jetty.project/issues/6184#issuecomment-1035620780.

The `java.security` classes were essential in fixing the implementation of the `Thread`' constructor pinning of the classloader.

**Comment by sbordet** [comment]
@janbartel I agree, `Thread` pinning the `ClassLoader` is category 3 of my comment above and I think it should remain, so that people using Java 17 will get the right effect, and those using a Java version without `SecurityManager` will have a modified `Thread` class that does not pin the `ClassLoader`, hopefully.

**Comment by sbordet** [comment]
@janbartel looking at this in more details, I am dubious about the fix for the `ClassLoader` pinning.

See how `Executors.privilegedThreadFactory()` is doing things differently from our `PrivilegedThreadFactory`, in particular it does not replace the `AccessControlContext`, which pins a `ProtectionDomain` which pins the `ClassLoader`.

**Comment by janbartel** [comment]
@sbordet `Executors.privilegedThreadFactory` will pin the `AccessControlContext`, thus the `ProtectionDomain` and the `ClassLoader` to be the same as the calling `Thread`.  Thus, depending on when jetty called `Executors.privilegedThreadFactory`, we could be just pinning the server class loader, which would be fine. However, if it was called by code that was _already_ in a context, then it would pin the context's classloader. 

Our solution executes in a privileged block, which means that the `AccessControlContext` is effectively not inherited, thus the `ProtectionDomain` and attendant `ClassLoader` cannot be pinned.

**Comment by joakime** [comment]
@janbartel the `AccessController` is one of the classes deprecated by [JEP-411](https://openjdk.java.net/jeps/411), it's role in JDK-17 is a mere shell now, it barely does anything anymore as you cannot have a SecurityManager (most of the remaining methods now do nothing because of this, compared to previous JDKs).
A future JDK will just delete/remove `AccessController` entirely.

**Comment by joakime** [comment]
Way out of date.
Will redo if there is a desire for it.
Closing.

**Pull request closed without merging**
