### PR TITLE
Replace contraction with possesive

### PR DESCRIPTION
**Pull request by earldouglas**

### CODE REVIEW

**Comment by gregw** [comment]
@earldouglas can you follow the instructions behind the "Details" link to sign a contributor license agreement.  This will allow us to merge this PR.

**Comment by earldouglas** [comment]
@gregw Sure thing, signing up now.  Looks like my chosen password broke eclipse.org, so waiting for webmaster help to reset it.

**Comment by earldouglas** [comment]
@gregw Done.

**Comment by jmcc0nn3ll** [comment]
well I validate you have it on file here: https://projects.eclipse.org/user/cla/validate and it looks like it is signed so will just merge and pray the ip-validation webhook doesn't have any issues

thanks for contribution!

**Pull request merged**
