### PR TITLE
Issue #2858 upgrade jnr-unixsocket to 0.19

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <oliver.lamy@gmail.com>

### CODE REVIEW

**Comment by olamy** [comment]
@gregw this generate the following warning
```
2018-08-25 14:41:44.307:WARN:oeji.ChannelEndPoint:HttpClient@4d2f9e3c-32: Ignoring key update for UnixSocketEndPoint@2e457b59{null<->null,CLOSED,fill=FI,flush=-,to=0/0}{io=1/1,kio=-1,kro=-1}->HttpConnectionOverHTTP@36b7733c(l:null <-> r:null,closed=true)=>HttpChannelOverHTTP@2a7aea49(exchange=null)[send=HttpSenderOverHTTP@6f787162(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@5bc7aefd{s=START}],recv=HttpReceiverOverHTTP@5edd996f(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]
java.lang.NullPointerException
	at jnr.enxio.channels.KQSelector$Descriptor.access$000(KQSelector.java:75)
	at jnr.enxio.channels.KQSelector.handleChangedKey(KQSelector.java:247)
	at jnr.enxio.channels.KQSelector.interestOps(KQSelector.java:301)
	at jnr.enxio.channels.KQSelectionKey.interestOps(KQSelectionKey.java:60)
	at org.eclipse.jetty.io.ChannelEndPoint.updateKey(ChannelEndPoint.java:381)
	at org.eclipse.jetty.io.ChannelEndPoint$1.update(ChannelEndPoint.java:103)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processUpdates(ManagedSelector.java:384)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:355)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joakime** [comment]
What's left to do in this PR?

**Comment by gregw** [comment]
Work stalled on this as JNR had bugs and appeared to be un maintained. 
However, work appears to have restarted and there is now a 0.20 release, so we should at least upgrade to that... will do....

**Comment by olamy** [comment]
well still NPE but tests pass:
```
2018-11-06 18:33:04.432:WARN:oeji.ChannelEndPoint:HttpClient@69499c6f-32: Ignoring key update for UnixSocketEndPoint@63043439{null<->null,CLOSED,fill=FI,flush=-,to=0/0}{io=1/1,kio=-1,kro=-1}->HttpConnectionOverHTTP@1c3fdc45(l:null <-> r:null,closed=true)=>HttpChannelOverHTTP@673bbc81(exchange=null)[send=HttpSenderOverHTTP@22393e02(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@51b619eb{s=START}],recv=HttpReceiverOverHTTP@13515a18(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]
java.lang.NullPointerException
	at jnr.enxio.channels.KQSelector$Descriptor.access$000(KQSelector.java:75)
	at jnr.enxio.channels.KQSelector.handleChangedKey(KQSelector.java:247)
	at jnr.enxio.channels.KQSelector.interestOps(KQSelector.java:301)
	at jnr.enxio.channels.KQSelectionKey.interestOps(KQSelectionKey.java:60)
	at org.eclipse.jetty.io.ChannelEndPoint.updateKey(ChannelEndPoint.java:381)
	at org.eclipse.jetty.io.ChannelEndPoint$1.update(ChannelEndPoint.java:103)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processUpdates(ManagedSelector.java:384)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:355)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Pull request merged**
