### PR TITLE
Issue #7111 - Add support to deprecate jetty-home modules.

### LINKED ISSUE #7111: Add support to deprecate jetty-home modules
**Jetty version(s)**
10.x +

**Description**
We need a feature to allow deprecation of modules.

It should notify on add and use.
It should also allow freeform text to indicate what the suggested action on the deprecation. (such as an alternate module name)

### PR DESCRIPTION
**Pull request by sbordet**
Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Comment by janbartel** [comment]
@sbordet If someone forgets to add `deprecated`  to the `[tags]` in the .mod file, is the module still listed for `--list-modules`, but without any indication it is deprecated?

**Review by joakime — DISMISSED** [review]
I like it.

**Comment by sbordet** [comment]
@janbartel I have addressed your concern. Now the list of enabled modules reports if a module is deprecated.
Best if it also has a tag, so all deprecated modules can be grouped together by `--list-modules`.

**Review by joakime — APPROVED** [review]
:+1:

**Pull request merged**
