### PR TITLE
Adding support for mongodb connection string

### PR DESCRIPTION
**Pull request by kensou**
Adds support for using a connection string to connect to Mongo

### CODE REVIEW

**Comment by jmcc0nn3ll** [comment]
This commit will need to be signed '-s' on the commit and you'll have to have a CLA on file with the Eclipse Foundation.  Please see:

https://www.eclipse.org/jetty/documentation/current/contributing-patches.html

Thanks for the patch!

**Comment by kensou** [comment]
I'll resubmit this with my work email instead (and a properly formatted checkin message)

**Comment by jmcc0nn3ll** [comment]
it will have to whichever you have under CLA, it is a bit of a palaver :/

**Comment by jin-z** [comment]
Closing this pull request and created a new one.
https://github.com/eclipse/jetty.project/pull/1372

**Pull request closed without merging**
