### PR TITLE
Issue #10139 - DefaultServlet not working with named dispatch in Jetty-12 EE10

### LINKED ISSUE #10139: DefaultServlet not working with named dispatch in Jetty-12 EE10.
Discovered from investigations into https://github.com/eclipse/jetty.project/issues/10138.

This seems to have been introduced in the various PRs to fix #9910.

If there is a named dispatch then `DefaultServlet#getEncodedPathInContext` ignores the servletPath of the request because `isDefaultMapping(HttpServletRequest req)` incorrectly says that the default servlet is not at the default mapping.

In the case of the websocket ee10 demo this results in the wrong `index.html` file being served.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #10139

Improve logic in EE10 `DefaultServlet.isDefaultMapping()` in case of servlet dispatch.

### CODE REVIEW

**Comment by joakime** [comment]
This needs test cases to prevent a regression here in the future.
We should have a test case for each variation of Named Dispatcher and DispatcherType.

**Comment by gregw** [comment]
@joakime I had offered to write the test case(s) to speed up the process before a reroll of 12.   But I've run out of time today.
We need to check both a named dispatch to the servlet named "default" and also a normal forward to something that is just a static resource.

Do you want to have a go?

**Comment by gregw** [comment]
or @lorban

**Review by joakime — APPROVED** [review]
Seems like a good change to me.
Do we want to see this in the 12.0.0 reroll?

**Comment by gregw** [comment]
> Seems like a good change to me. Do we want to see this in the 12.0.0 reroll?

yes

**Pull request merged**
