### PR TITLE
Fully decode #9444

### LINKED ISSUE #9444: Unexpected encoding in request.getPathInfo() with Jetty 12 beta 0
**Jetty version(s)**
12.0.0.beta0

**Java version/vendor**
openjdk version "19.0.1" 2022-10-18

**OS type/version**
mac os

**Description**
When requesting a URL like

http://localhost:8888/view/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file%20name

with a servlet mapping of `/view/*` then `request.getPathInfo()` in 

Jetty < 12 returns `"/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file name"` while 
Jetty 12 returns `"/VAADIN/dynamic/resource/5/4a2dc788-7f04-43e4-8471-70d713d6d001/file%20name"`

Is this an intentional change in some spec or accidental?

This breaks handling of resources like "file name" in Vaadin when run in 12 beta0 as Vaadin assumes the path info is decoded and then encodes it to match with a stored, encoded value.

### PR DESCRIPTION
**Pull request by gregw**
This is an alternative to #9462 as a fix for #9444, replacing changes made by #9455 

getServletPath and getPathInfo will never return an encoded path segment. Instead they will throw an IllegalArgumentException if they are called when there is a URI with violations.

### CODE REVIEW

**Comment by gregw** [comment]
@joakime this is a WIP, with many tests broken. But I think the solution is to change the tests.  Let's hangout early next week to discuss tests

**Comment by gregw** [comment]
So to be explicit with the intent of this:
- The methods `getServletPath` and `getPathInfo` will never EVER return any encoded characters
- The method `getContextPath` will continue to return the canonically encoded context path (as always)
- We will match to context using the canonically encoded path
- We will match to filters and servlets using the fully decoded path
- By default we allow no violations to the URI RFC
- If we are configured with any ambiguous violations, then they will play out as they do via matching above... but if anything calls  `getServletPath` and `getPathInfo` then a `BadMessage$IllegalArgumentException` is thrown.

I should add this to the javadoc somwhere.

**Comment by joakime** [comment]
Did you mean to merge PR #9474 into this PR?

**Comment by gregw** [comment]
> Did you mean to merge PR #9474 into this PR?

Yes. It was split out from this PR, as it is needed here

**Comment by gregw** [comment]
close in favour of #9479

**Pull request closed without merging**
