### PR TITLE
Add WebAssembly MIME type support

### PR DESCRIPTION
**Pull request by barabadzhi**

### CODE REVIEW

**Comment by joakime** [comment]
From spec - https://www.w3.org/TR/wasm-web-api-1/

@barabadzhi we legally cannot merge this PR as you don't have an Eclipse ECA on file.
And your commit didn't satisfy the [CONTRIBUTING.md](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md) requirements for git sign-off.

**Comment by barabadzhi** [comment]
@joakime should be fine now. 象形字

**Comment by olamy** [comment]
we do not use master branch. 
Can you please rebase with current jetty-9.4.x?

**Comment by barabadzhi** [comment]
@olamy Sure, done.

**Comment by olamy** [comment]
@barabadzhi 8.x is EOL now see details here https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

**Comment by barabadzhi** [comment]
@olamy Wow :open_mouth:, than we definitely need to upgrade.
Will talk to the team. Thanks! :slightly_smiling_face:

**Pull request merged**
