### PR TITLE
codeql correctly setup maven to not depend on default installation

### PR DESCRIPTION
**Pull request by olamy**
to not depend on what is installed in the image

### CODE REVIEW

**Comment by joakime** [comment]
Seems odd to force a mvnw version like this.

It's just a workflow action.
Can't we just use the normal `setup-java` stuff?

ala ...

``` yml
      - name: Set up JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
```

**Comment by olamy** [comment]
yup something such (from https://github.com/stCarolas/setup-maven)
```
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.6
```

**Comment by olamy** [comment]
@joakime change done

**Review by joakime — APPROVED** [review]
LGTM, this action approach is probably better cached (within github) too.
No need to go out to the internet now.

**Pull request merged**
