### PR TITLE
Jetty 9.4.x 2164 update poms serviceloader with osgi

### PR DESCRIPTION
**Pull request by janbartel**
This is PR is branched off the PR #2167 because it needs spifly to be updated.

### CODE REVIEW

**Comment by joakime** [comment]
Anything in /jetty-websocket/ need this too?

**Comment by janbartel** [comment]
@joakime  ah, yes, it appears that ServiceLoader use has become more diffuse in websocket, so I'll need to update those as well.

**Comment by olamy** [comment]
oops forget my comment I just read #2167 :-)

**Comment by janbartel** [comment]
@olamy  and @joakime  can you both take another look at this PR? I've updated the websocket poms, but I've also added a new test for websocket in osgi.

@joakime FYI:  I tried to also add a test for javax.websocket, but that can't work in osgi because the javax.websocket jar does not have the correct osgi manifest headers for using the ServiceLoader.

**Comment by joakime** [comment]
@janbartel there are 2 javax.websocket jars.  You have to use the one appropriate for server or client.
Do both jars have the same broken osgi manifest?

**Comment by joakime** [comment]
Also, isn't there something in OSGi that lets you update/modify/fix issues with jars with a fragment like concept?

**Comment by janbartel** [comment]
@joakime it's the ContainerProvider in the client-api that is not correct - but the server could have the same problem.

Yes, there are fragments, I'll have a quick look, but I'm not going to spend a lot of time on it - the javax.websocket api guys should fix their manifest headers.

**Comment by joakime** [comment]
@janbartel do the manifests in the version 1.1 jars have what you need?

**Comment by janbartel** [comment]
OK, it was a lot of hassle, but I finally got javax.websocket working in osgi unit tests. This PR is ready for final review.

**Pull request merged**
