### PR TITLE
Issue #1706 resolving the issue by using Log.class's class loader

### PR DESCRIPTION
**Pull request by peterdsdoyle**
Signed-off-by: doylep <doylep@viewstreet.com>

### CODE REVIEW

**Comment by gregw** [comment]
#1706

**Comment by gregw** [comment]
Why was this closed?  @janbartel comment in #1706 indicates it is not an unreasonable thing to do?

**Comment by gregw** [comment]
Ah - I see other changes were made.... can you comment and close.

**Comment by peterdsdoyle** [comment]
hey @gregw  anything required of me to further this request?

**Comment by janbartel** [comment]
@peterdsdoyle  I think you're doing to have to remake the patch as the jetty-9.4.x branch just changed substantially.

**Comment by gregw** [comment]
@peterdsdoyle never mind remaking the PR. I'll apply manually and mention you in the commit.

thanks

**Pull request closed without merging**
