### PR TITLE
Do not execute any phase for maven plugin :start

### LINKED ISSUE #9130: Unnecessary `validate` phase executed by `:start` maven plugin goal
Here's my setup - https://github.com/pzrep/jetty-start-goal/:
https://github.com/eclipse/jetty.project/blob/b8db190114d047a4ac60d01c6fdda4fdbba9609e/pom.xml#L82-L88

This however results in [`validate` being executed](https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:52):
```
[INFO] >>> jetty-maven-plugin:11.0.3:start (start-jetty) > validate @ jetty-start-goal >>>
[INFO] 
[INFO] --- maven-help-plugin:3.3.0:active-profiles (default) @ jetty-start-goal ---
[INFO] 
Active Profiles for Project 'pzrep:jetty-start-goal:war:1.6.0-SNAPSHOT':

The following profiles are active:

 - with-jetty (source: pzrep:jetty-start-goal:1.6.0-SNAPSHOT)



[INFO] 
[INFO] <<< jetty-maven-plugin:11.0.3:start (start-jetty) < validate @ jetty-start-goal <<<
[INFO] 
[INFO] 
[INFO] --- jetty-maven-plugin:11.0.3:start (start-jetty) @ jetty-start-goal ---
```

But it was executed in [line 13](https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:14) already.

_Originally posted by @pzygielo in https://github.com/eclipse/jetty.project/issues/9128#issuecomment-1374180531_

### PR DESCRIPTION
**Pull request by pzygielo**
- Closes #9130

### CODE REVIEW

**Comment by sbordet** [comment]
Thanks for this PR, but can you please describe what is the problem that this PR would be fixing?

**Comment by pzygielo** [comment]
Given

https://github.com/eclipse/jetty.project/blob/8b7723bf98680a7250029fa2cc3a95fad7b401fc/jetty-maven-plugin/src/main/java/org/eclipse/jetty/maven/plugin/JettyStartMojo.java#L25

thus it's almost sure `validate` is already included in buildplan. And the project is validated by the time `:start` is reached.

This is inconvenient if other goals are also bound to `validate` as this triggers them for the second time on `:start`.

**Comment by joakime** [comment]
This is just the recommended phase following the maven "convention over configuration" approach.

You can override this with your own configuration to specify a different phase.

``` xml
<plugin>
  <artifactId>jetty-maven-plugin</artifactId>
  <phase>prepare</phase>
</plugin>
```

or

``` xml
<plugin>
  <artifactId>jetty-maven-plugin</artifactId>
  <executions>
    <execution>
      <phase>prepare</phase>
    </execution>
  </executions>
</plugin>
```

There's no need to remove this from the codebase.

**Comment by joakime** [comment]
Not going to merge this.

**Comment by pzygielo** [comment]
> This is just the recommended phase following the maven "convention over configuration" approach.
> 
> You can override this with your own configuration to specify a different phase.

I don't think so.

> ```
> <plugin>
>   <artifactId>jetty-maven-plugin</artifactId>
>   <phase>prepare</phase>
> </plugin>
> ```

I can't.

This is not about goal being bound to phase (there is no default one set for this goal).

This is about extra execution of life cycle.

> There's no need to remove this from the codebase.

Please use this goal once and reconsider.

**Comment by pzygielo** [comment]
Just for completeness, here's my setup:
https://github.com/eclipse/jetty.project/blob/b8db190114d047a4ac60d01c6fdda4fdbba9609e/pom.xml#L82-L88
I obviously have no other choice - the phase has to be set explicitly anyway for goal to run. Remove the line 84 and it will give
```
[INFO] Jetty not running!
```
in the end, as the `:start` won't happen at all.

This however results in [`validate` being executed](https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:52):
```
[INFO] >>> jetty-maven-plugin:11.0.3:start (start-jetty) > validate @ jetty-start-goal >>>
[INFO] 
[INFO] --- maven-help-plugin:3.3.0:active-profiles (default) @ jetty-start-goal ---
[INFO] 
Active Profiles for Project 'pzrep:jetty-start-goal:war:1.6.0-SNAPSHOT':

The following profiles are active:

 - with-jetty (source: pzrep:jetty-start-goal:1.6.0-SNAPSHOT)



[INFO] 
[INFO] <<< jetty-maven-plugin:11.0.3:start (start-jetty) < validate @ jetty-start-goal <<<
[INFO] 
[INFO] 
[INFO] --- jetty-maven-plugin:11.0.3:start (start-jetty) @ jetty-start-goal ---
```

But it was executed in [line 13](https://github.com/pzrep/jetty-start-goal/actions/runs/3858708613/jobs/6577522172#step:4:14) already. How can I avoid that second run?

**Comment by joakime** [comment]
Open an issue, and please provide a link to an example project. (preferably a github repo)
What you are linking to isn't showing the whole picture.
Have the discussion first, don't jump to the kind of drastic (and workflow breaking) changes you have in this PR.
A solution can be had, we just need more information.

**Comment by pzygielo** [comment]
> Open an issue, and please provide a link to an example project. (preferably a github repo) What you are linking to isn't showing the whole picture. 

I was linking to action for https://github.com/pzrep/jetty-start-goal, which is complete reproducer. It is github repo. It is showing the whole picture.

> Have the discussion first, don't jump 
> to the kind of drastic
> (and workflow breaking)

:eyes: (Took me 8 months to _jump_, since my first discovery.)

My change is just following the (currently misleading) description the class has. And my expectation.

> A solution can be had, we just need more information.

I'm sorry if I'm the first to complain for 11 years (this issue was introduced in _jetty-8.1.0.RC2 - 22 December 2011_).

I have no more information.

Thanks for checking.

**Review by janbartel — APPROVED** [review]

**Pull request merged**
