### PR TITLE
Fixes #3385  Modernize jetty-util-ajax.

### LINKED ISSUE #3385: Modernize jetty-util-ajax
`jetty-util-ajax` should be modernized and use generics in various places where it does not.

### PR DESCRIPTION
**Pull request by sbordet**
Added type parameter to methods that were using raw types.
Updated the implementation to use generics.
Deprecated static methods.
Updated usages.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

Fixes #3385.

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
@sbordet would it worth me looking at creating a persistent `JSON` instance for the OpenId code now that you have removed the static methods, or is the performance penalty of creating a new one every time not much?

**Review by gregw — CHANGES_REQUESTED** [review]
This looks OK.... but I'm a bit in two minds about the deprecation of the statics.   Currently they are deprecated and have changed behaviour.  Either:
 1) they are deprecated and marked for removal, but until that time should retain their semantics of accessing a default instance with convertors etc;
 2) OR this is a major version, they are not needed so just remove them;
 3) OR they are now static convenience methods (no convertors) and as such should not be deprecated. 

I'm leaning towards 3, but with renaming so that  `JSON.fromJSON(...)` is the same as `new JSON().fromJSON(...)`, but no strong preference other than not liking deprecated and changed.

**Comment by sbordet** [comment]
@lachlan-roberts yes if you can create a JSON instance as a field in some OpenId class and reuse that instance will be great.

@gregw I'm leaning for (2), and the renaming that you propose for (3) cannot be done as we cannot have a `static` and non-`static` method with the same name and signature.

**Comment by gregw** [comment]
I'm good with 2 - less clutter

**Comment by sbordet** [comment]
@gregw removed deprecated methods as suggested - please re-review.

**Review by gregw — APPROVED** [review]

**Pull request merged**
