### PR TITLE
Add methods to send text frames with pre-encoded strings.

### PR DESCRIPTION
**Pull request by darnap**
Signed-off-by: dario.napolitano <darnap@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
This change fails the autobahn RFC6455 protocol test suite.
You cannot send any old bytes on a TEXT message.  
The protocol implementation MUST validate the UTF8 nature of the overall TEXT message.

Our implementation would *have to decode* and verify each message being offered on this method for UTF8 validity before we could send it.  Rendering these methods moot.

**Comment by darnap** [comment]
The idea would be to allow applications that already handle encoded UTF-8 strings to directly send them without having to undergo an extra decoding and encoding step, for performance reasons. On high traffic servers this step can take a non-negligible amount of processing time, in addition to extra generated garbage. Of course it would be the application's responsibility to ensure that the bytes are well-formed UTF-8 strings.

**Comment by joakime** [comment]
The API cannot make that assumption, nor can the various websocket extensions. 
If the payload isn't 100% guaranteed to be UTF8, its in violation of multiple websocket specs.

The mere fact that this API exists, means that it will be abused, and will cause extra support concerns on the project.

Instead of adding these as formal methods on the RemoteEndpoint, perhaps a more advanced API where you control the sending of raw frames (instead of using RemoteEndpoint) makes more sense?

**Comment by darnap** [comment]
Thanks for the suggestion, I understand the concern. Do you think that there is room for such a feature in Jetty itself or is it too specific to be of general interest?

**Comment by gregw** [comment]
Perhaps the API should be in two parts: 1) to encode a string into an Opaque object that would internally hold the ByteArray (lt's call it PreparedTextMessage class); 2) an API that sends PreparedTextMessage classes.

This way a the expense of creating the ByteBuffer is done only once and the message can be sent again and again.

Note that I'd also rather that such an API be proposed back the the JSR to see if it can be included in the next revision of the standard.

**Comment by joakime** [comment]
Please see the [bugs/388](https://github.com/eclipse/jetty.project/tree/bugs/388) branch and see if that would be an acceptable solution for you.

**Comment by darnap** [comment]
That would definitely provide a clean way to provide such a specific feature. Thanks.

**Comment by joakime** [comment]
@darnap please give that branch a go, and let us know if it needs any work to improve it.
We'll merge it back to [jetty-9.3.x] once its confirmed to satisfy your needs.

**Comment by joakime** [comment]
Another possible alternative here ...

```java
    sendString(CharBuffer charbuffer) 
```

This buffer, will undergo more native calls ...

```java
    CharsetEncoder encoder = StandardCharsets.UTF8.newEncoder();
    encoder.onMalformedInput(new OnProtocolViolation());
    encoder.onUnmappableInput(new OnProtocolViolation());

    // ... then later per .sendString() ...
    ByteBuffer bytebuf = encoder.encode(charbuffer);
    outgoingFrames.append(new TextFrame().setPayload(bytebuf));
```

**Comment by darnap** [comment]
@joakime I've tried using the proposed changes, but the factory interface declares the concrete WebSocketRemoteEndpoint type for its return value instead of the RemoteEndpoint interface. The RemoteEndpoint interface lacks the getInetSocketAddress() method used by WebSocketSession, while WebSocketRemoteEndpoint is not practical to extend as it is, due to several private methods.

A solution would be to move the getInetSocketAddress method to the RemoteEndpoint interface. Making the WebSocketRemoteEndpoint class methods protected would also make it easier to use it as a base class.

Would that be acceptable?

Thanks

**Comment by gregw** [comment]
@joakime 
Also I think that because the service loader can return multiple factories, then you should really call each until one returns a non null response.. if they all produce null, then call this.

Alternately have a warning or even fatal error if there are more than one factories on the classpath.

**Comment by joakime** [comment]
Next release of Jetty 9.3.x will have this in it.

**Comment by darnap** [comment]
Thanks.

**Pull request closed without merging**
