### PR TITLE
Bug 485625 - Allow overriding the conversion of a String into a Crede…

### PR DESCRIPTION
**Pull request by gouessej**
…ntial

Signed-off-by: Julien Gouesse <gouessej@orange.fr>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=485625

**Comment by gouessej** [comment]
@gregw Sorry for the formatting changes in some code unrelated to my request for enhancement. Is it ok for you now? I will probably improve a bit the documentation and maybe provide a unit test.

**Comment by joakime** [comment]
Jan, can you take a look at this?

**Comment by gregw** [comment]
I'll look at this because I looked before.

**Comment by gouessej** [comment]
Thank you :)

**Pull request merged**
