### PR TITLE
Add Checkstyle and IDE Code Formatters

### PR DESCRIPTION
**Pull request by joakime**
Place to discuss the Checkstyle proposal and standardized IDE code style formatters.

### CODE REVIEW

**Comment by olamy** [comment]
@gregw install -DskipTests first to get the build resource module locally

**Comment by joakime** [comment]
The philosophy in this branch is to create the checkstyle rule first, then adjust the IDE code styles to conform.

> I don't really like the following:
> 
> * forcing use of {} for single line conditionals

Where did you see this?
The checkstyle rule for that is disabled.

https://github.com/eclipse/jetty.project/blob/9557c18ef59f63a150bf9d4a166570857a86c428/build-resources/src/main/resources/jetty-checkstyle.xml#L189-L192

> * space after a (Cast)

I think that can be checked for via `NoWhitespaceAfter` with the `TYPECAST` token.

https://checkstyle.org/config_whitespace.html#NoWhitespaceAfter

> * lambdas should not be allows to have { on same line

Seems reasonable.

Simple cases like ...

``` java
this.fooProvider = () -> { otherObj.getFoo(); };
```

shouldn't even have the parens `{`, and the only reason to have parens is for multiple statements, which should be on multiple lines anyway.

> * We should allows local variable named like_this.... in fact we should probably disallow local variables named likeThis... or allow both styles.

We have an exception for the standard sun style guide and language reference for your special `_fieldname` syntax now.
Snake case (aka `a_snake_case_name`) is not a standard in any large public java open source style guide (any eclipse project, any apache project, any spring project, hibernate, google, etc...)

It should be noted that there is only one use case for `_` in a field variable name, immutable constants. (that's special case is pointed out in the Java Language Spec, and Java Style Guide (Sun and Oracle), the Google Style Guide, Spring Style Guide, and others)

``` java
public static final Joiner COMMA_JOINER = Joiner.on(',');
```

Also worth noting, if using snake_case on field values that have accessors (get / put) then IDE refactoring tools really freak out, so there's that too.

I'm good with standard camelCase, and the occasional `_` prefixed field. (which the checkstyle has now)

https://github.com/eclipse/jetty.project/blob/9557c18ef59f63a150bf9d4a166570857a86c428/build-resources/src/main/resources/jetty-checkstyle.xml#L99-L102

I think we should reject double `__prefixed` though, as the only use case for that is constants, which should follow the all uppercase syntax.

Keep in mind that we are making the checkstyle, style guide, and IDE codestyles to have submissions and PRs with as minimal effort as possible (don't do things that are strange, rare, or tool breaking just because of our history)

> * I like having the option to format ? : expressions on multiple lines like:
>   ```
>   Object foo = (test == null)
>       ? some(very + long) / expression
>       : other(long, line, of, code);
>   ```
>   
>   
>   I'd give up insisting on all operators being on trailing wrapped lines to get this style.

Your specific example argues more for refactoring that logic (to a method?) especially if you have `some(very + long) / expression` or `other(long, line, of code)`.
As that becomes far too information dense to read.  Remember the `Predicate.or()` and `Predicate.and()` PR?

But that's a different topic! unrelated to the request to allow `[variable] = [test] ? [true-return] : [false-return]` to be on separate lines with the '?' and ':' on the new line.

We have 2 rules currently setup for where tokens live ('nl' or 'eol') ...

This one insists that token (COMMA `.`) should show up on the next line (the `nl` value)

https://github.com/eclipse/jetty.project/blob/9557c18ef59f63a150bf9d4a166570857a86c428/build-resources/src/main/resources/jetty-checkstyle.xml#L131-L135

So that things like this work ...

https://github.com/eclipse/jetty.project/blob/076c6b1c71c13f4b03562fbde16196fedd861f45/tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/AttributeNormalizerTest.java#L122-L125

or

https://github.com/eclipse/jetty.project/blob/076c6b1c71c13f4b03562fbde16196fedd861f45/tests/test-quickstart/src/test/java/org/eclipse/jetty/quickstart/AttributeNormalizerTest.java#L326-L328

And we have the second rule ...

https://github.com/eclipse/jetty.project/blob/9557c18ef59f63a150bf9d4a166570857a86c428/build-resources/src/main/resources/jetty-checkstyle.xml#L136-L140

That says the tokens ...

 * COMMA `,`
 * ELLIPSIS `...`
 * ARRAY_DECLARATOR `[]`
 * METHOD_REF `::`

... must show up at the end of line (`eol` rule)

Point is, we can make the rules for `nl` (new line) or `eol` for specific token types.
I'll look into allowing the inline conditionals to be separated by `nl`.

> 
> Also I can't actually run the checkstyle plugin from the command line?
> With:
> 
> ```
> mvn -P checkstyle checkstyle:checkstyle
> ```
> 
> I get:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:checkstyle (default-cli) on project jetty-project: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.jetty:build-resources:jar:9.4.19-SNAPSHOT in https://repository.apache.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
> ```

Like @olamy pointed out, the checkstyle rule is part of the build reactor, so partial builds wouldn't work.

Incidentally, you don't need the `checkstyle:checkstyle` goal on your command line, only the `-Pcheckstyle` is needed (it already does the `checkstyle:checkstyle` reporting goal).

Perhaps you can use ...

```
$ mvn clean install site -Pcheckstyle
```

That way you'll get all of the supporting html / js / css too (makes reading the html reports easier)

**Comment by joakime** [comment]
Checkstyle rules and Formatters / CodeStyles have been updated based on PR feedback.
Please perform your reviews of this new reality :-)

**Comment by janbartel** [comment]
I prefer the opening curly of an array declaration on a new line if there are multiple entries, ie I don't like this:

``` java

public final static String[] __dftSystemClasses = {
        "java.",
        "javax.",
        "org.xml.",
        "org.w3c."
}
```

I prefer this:
``` java

public final static String[] __dftSystemClasses = 
{
        "java.",
        "javax.",
        "org.xml.",
        "org.w3c."
}
```


The wrapping on multi-line method calls is yuck. This nice formatting:

``` java
        dumpObjects(out,indent,
            new ClassLoaderDump(getClassLoader()),
            new DumpableCollection("Systemclasses "+this,system_classes),
            new DumpableCollection("Serverclasses "+this,server_classes),
            new DumpableCollection("Configurations "+this,_configurations),
            new DumpableCollection("Handler attributes "+this,((AttributesMap)getAttributes()).getAttributeEntrySet()),
            new DumpableCollection("Context attributes "+this,((Context)getServletContext()).getAttributeEntrySet()),
            new DumpableCollection("Initparams "+this,getInitParams().entrySet())
            );

```
became this hodge-podge when I applied the stylesheet:

``` java
dumpObjects(out, indent, new ClassLoaderDump(getClassLoader()), new DumpableCollection("Systemclasses " + this,
            system_classes), new DumpableCollection("Serverclasses " + this, server_classes), new DumpableCollection(
                "Configurations " + this, _configurations), new DumpableCollection("Handler attributes " + this,
                    ((AttributesMap)getAttributes()).getAttributeEntrySet()), new DumpableCollection(
                        "Context attributes " + this, ((Context)getServletContext()).getAttributeEntrySet()),
            new DumpableCollection("Initparams " + this, getInitParams().entrySet()));
```

See also something like the following nice formatting that gets chewed up and spat out in a less readable fashion by the stylesheet:

``` java
  if ((listener instanceof HttpSessionActivationListener)
            || (listener instanceof HttpSessionAttributeListener)
            || (listener instanceof HttpSessionBindingListener)
            || (listener instanceof HttpSessionListener)
            || (listener instanceof HttpSessionIdListener))
```

Also, in 2019, do we really care about forcing a max line length in the actual code? Isn't this just a presentation issue for the ide?

**Comment by joakime** [comment]
@janbartel are you referring to the behavior you see in the Eclipse IDE formatter / codestyle?

**Comment by sbordet** [comment]
I imported the IJ format, and run "Reformat code" in IJ.

Things that happened:

* single line `if` without braces -> braces added. This impacts lines such as 
```java
if (LOG.isDebugEnabled())
    LOG.debug()
```
For this to be fixed, weirdly, the setting should be: "if() statement / force braces = do not force".

After fixing that, refactoring the `http` modules, which I mostly wrote, resulted only in good changes.

**Comment by joakime** [comment]
@janbartel some behavior differences on the formatter / codestyle.

If I take a block of code like this ...

``` java
public final static String[] FOO_VAR = {
    "foo.",
    "bar.",
    "baz.",
    "zed."
}
```

And apply a formatter / codestyle for both "opening brace" == forced and "indent" == 4 then the result is the following ...

On IntelliJ
``` java
public final static String[] FOO_VAR =
    {
        "foo.",
        "bar.",
        "baz.",
        "zed."
    }
```

On Eclipse IDE

``` java
public final static String[] FOO_VAR =
{
    "foo.",
    "bar.",
    "baz.",
    "zed."
}
```

**Comment by joakime** [comment]
@sbordet yes, i agree.

The checkstyle rule on this should probably be disabled as well ...

https://github.com/eclipse/jetty.project/blob/d99f639c20c6beefbd8cdf9ad29e1557bc422457/build-resources/src/main/resources/jetty-checkstyle.xml#L204-L206

Behaviors on that rule if we keep it in place ...

``` java
// This is allowed
if (foo == null) foo = new Foo();

// This is a violation 
if (foo == null)
    foo = new Foo();
```

Interestingly, both Eclipse IDE and Intellij has an option for forcing braces "on multiline".
But that means ...

``` java
// This will be left alone
if (foo == null) foo = new Foo();

// This uses 2 lines (and is considered "multiline")
if (foo == null)
    foo = new Foo();

// So that would end up as
if (foo == null)
{
    foo = new Foo();
}
```

I was hoping to catch nested if/for loops like (notice the if statement on line 285) ...

https://github.com/eclipse/jetty.project/blob/d99f639c20c6beefbd8cdf9ad29e1557bc422457/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java#L282-L290

... but neither Eclipse IDE, nor Intellij, nor checkstyle has a variation of the braces rule for that kind of scenario. (indentation rules however do kick in)
I feel this kind of scenario should have braces. WDYT?

What are your feelings on mismatched braces behaviors with if / else?

``` java
// Aka something like this ...
if (foo == null)
    foo = new Foo();
else
{
    foo.prepare();
    foo.fiddleWidget();
}

// or ...
if (foo == null)
    foo = new Foo();
else
{
    try
    {
        foo.prepare();
        foo.fiddleWidget();
    }
    finally
    {
        foo.cleanup();
    }
}


```

**Comment by sbordet** [comment]
@joakime now I understand too what "multiline" means.
It's yucky but at this point I prefer `if` statements with braces (so basically the setting would be "always force").

**Comment by janbartel** [comment]
@joakime  I checkout out your branch, got the eclipse ide style file and applied it to a couple of classes in jetty-9.4.x. All of the cut and pasted code I included came directly from what eclipse generated with the style.

**Comment by joakime** [comment]
@janbartel @sbordet I just pushed an update for both formatters / codestyles to fit with your feedback, along with a minor change to the checkstyle rules.

See comment on commit 6e44a7cfd177e06171f782881839be892e3e97f5 for details of changes.

**Comment by janbartel** [comment]
@joakime that is heaps better, thanks!

**Comment by olamy** [comment]
please keep limit on too lines some people keep using laptop :)

**Comment by sbordet** [comment]
@joakime with the latest code, in IJ this simple lambda went from:

```java
Runnable noop = () -> {};
```

to:

```java
Runnable noop = () -> 
{};
```

I would prefer the former.

**Comment by gregw** [comment]
I would prefer one line for ()->{}  but can live with the multi-line as it would only apply to empty {}

I'm pretty keen on supporting simple multi-lines like:
```java
if (foo == null)
    foo = new Foo(); // GOOD
```
but can live with curly blocks in all other cases... even if the simple multi-line is part of an if-else

I don't like single line if statements:
```java
if (foo == null) foo = new Foo();  // BAD
```

**Comment by WalkerWatch** [comment]
+1 to no single-line ifs. I also prefer using curly braces regardless.

**Comment by joakime** [comment]
> @joakime with the latest code, in IJ this simple lambda went from:
> 
> ```java
> Runnable noop = () -> {};
> ```
> 
> to:
> 
> ```java
> Runnable noop = () -> 
> {};
> ```
> 
> I would prefer the former.

That's not possible in the formatters / codestyles for both IntelliJ and Eclipse IDE.
It conflicts with the next line for opening brace style.

But it is possible for the checkstyle rules.

**Comment by joakime** [comment]
> I would prefer one line for ()->{} but can live with the multi-line as it would only apply to empty {}

The codestyle / formatters don't seem to support this exception in behavior.

> 
> I'm pretty keen on supporting simple multi-lines like:
> 
> ```java
> if (foo == null)
>     foo = new Foo(); // GOOD
> ```

"Simple multi-line" is a minefield.

Take this example (from our BufferUtils!)

https://github.com/eclipse/jetty.project/blob/d99f639c20c6beefbd8cdf9ad29e1557bc422457/jetty-util/src/main/java/org/eclipse/jetty/util/BufferUtil.java#L282-L290

That's a single if statement (line 285), with a single for statement.
From the point of view of that if statement, there's only 1 statement under it.
It doesn't see the nested if > for > if > block

If we force braces, then that block will look like ...

``` java
    public static long remaining(ByteBuffer... buf)
    {
        long remaining = 0;
        if (buf != null)
        {
            for (ByteBuffer b : buf)
            {
                if (b != null)
                {
                    remaining += b.remaining();
                }
            }
        }
        return remaining;
    }
```

But if we give this "if" statement exclusion (no braces required if there is only 1 statement under it) then that block looks like this ...

``` java
    public static long remaining(ByteBuffer... buf)
    {
        long remaining = 0;
        if (buf != null)
            for (ByteBuffer b : buf)
            {
                if (b != null)
                    remaining += b.remaining();
            }
        return remaining;
    }
```

> 
> but can live with curly blocks in all other cases... even if the simple multi-line is part of an if-else
> 
> I don't like single line if statements:
> 
> ```java
> if (foo == null) foo = new Foo();  // BAD
> ```

I'm not a fan of single line statements too.

**Comment by gregw** [comment]
While I personally would probably put the extra {} in the following:
```java
    public static long remaining(ByteBuffer... buf)
    {
        long remaining = 0;
        if (buf != null)
            for (ByteBuffer b : buf)
            {
                if (b != null)
                    remaining += b.remaining();
            }
        return remaining;
    }
```
It is still pretty readable as is (and not that far from what you would see if using { on the same line.

So I don't think we want to go crazy with trying to make these style rules take away all programmer discretion.    If code is hard to read without {}, then the programmer should add those {} as needed.    If they don't add the {} all we need is reasonable consistent formatting of the results.   I know this can make search and replaces more difficult, but if we have regular formatting then there will only be 2 search patterns needed.

**Comment by gregw** [comment]
Can we:

- turn off `overload methods should not be split` rule.   Method ordering is not really important (IDEs give you overview) and there may be reasons for other orderings.  Programmers should be responsible for sensible ordering.
- add _ as a field prefix in the styles

ummmmm other than that, it's looking pretty good to me.   The only other thing I saw was a quibble.   The style allows a break outside of a block but checkstyle complains about indent level:
```java
    switch(something)
    {
        case "state":
        {
            doSomething();
            doSomethingElse();
        }
        break;
    }
```

I've got no strong opinion either way on that one... just thought I'd raise it to see if we can/want the break in the block or if checkstyle can be made happy with it outside the block.

**Comment by joakime** [comment]
> Can we:
> 
> * turn off `overload methods should not be split` rule.   Method ordering is not really important (IDEs give you overview) and there may be reasons for other orderings.  Programmers should be responsible for sensible ordering.

Easy enough

> * add _ as a field prefix in the styles

Thought that was already there.

> 
> ummmmm other than that, it's looking pretty good to me. The only other thing I saw was a quibble. The style allows a break outside of a block but checkstyle complains about indent level:
> 
> ```java
>     switch(something)
>     {
>         case "state":
>         {
>             doSomething();
>             doSomethingElse();
>         }
>         break;
>     }
> ```
> 
> I've got no strong opinion either way on that one... just thought I'd raise it to see if we can/want the break in the block or if checkstyle can be made happy with it outside the block.

What about turning ON this rule ... https://checkstyle.org/config_blocks.html#AvoidNestedBlocks

**Comment by gregw** [comment]
@joakime @janbartel @olamy @sbordet @lachlan-roberts @jmcc0nn3ll @WalkerWatch Let's go for this big reformat just after 9.4.19 release and just before the 10.0.0.alpha0 ?  Vote with thumbs up or down!

**Comment by joakime** [comment]
Already merged into `jetty-9.4.x` soon to be in `jetty-10.0.x`

**Pull request closed without merging**
