### PR TITLE
#7863 Include value of first accept-encoding header where multiple accept-encoding headers are given

### LINKED ISSUE #7863: Default servlet drops first accept-encoding header if there is more than one.
**Jetty version(s)**
11.0.9

**Java version/vendor** `(use: java -version)`
N/A

**OS type/version**
N/A

**Description**
When `DefaultServlet` handles a request with multiple `accept-encoding` headers, it attempts to combine their values, but it drops the value of the first header (and produces a value with a leading comma).

**How to reproduce?**
Test case to follow.

### PR DESCRIPTION
**Pull request by joakime**
Cherry-pick of commit 8bcb842fbbd2e4c9f57bfa7718b038786edc0aa0 for `jetty-9.4.x`

### CODE REVIEW

**Review by gregw — COMMENTED** [review]
This code looks rather strange... even before the fix. @lorban can you have a look with your recent resource service experience and check that the while loop with no body is correct.

**Comment by lorban** [comment]
@gregw I agree that this loop is quite convoluted. It feels like it was written that way to optimize the cases where there is no accept-encoding header or when it contains a single value.

The existing code also is buggy in the sense that it forgets to include the first accept-encoding value in the key it builds in case there are multiple values for that header, which poisons the cache with incorrect values.

But it feels like this `_preferredEncodingOrderCache` isn't going to be that efficient as it allows logical duplicates and requires multiple allocation before looking up a multi-accept-encoding value which feels to me like that would defeat most savings bypassing the `QuotedQualityCSV` parser could bring.

I think this fix should go in, but we should revisit this `_preferredEncodingOrderCache` and consider dropping it.

**Comment by joakime** [comment]
Opened issue #7928 about that review of `_preferredEncodingOrderCache` at issue #7928

**Comment by joakime** [comment]
@lorban or @gregw want to approve this then? (so we can get it merged)

**Review by lorban — APPROVED** [review]

**Pull request merged**
