### PR TITLE
Issues #1717 DoSFilter remotePort tracker loadId delimiter added

### PR DESCRIPTION
**Pull request by dellgreen**
RemotePort tracking feature of DosFilter tracker now has address and port delimited with a colon to avoid rare collisions by just concatenating them together

### CODE REVIEW

**Comment by joakime** [comment]
Please add IPv6 test cases.  The behavior here smells like it will fail on IPv6 scenarios.

**Comment by joakime** [comment]
You didn't have to close this, just add another commit

**Comment by dellgreen** [comment]
apologies newish to github

**Comment by joakime** [comment]
Then let us say: Welcome to github!
You have the option to reopen and comment on this existing PR.
After that, just add more commits to your `dellgreen:dosfilter-1717` branch and they should show up automatically here in this PR. (just don't forget to sign-off the commits)

**Comment by dellgreen** [comment]
do you need me to squash the commits on my branch or leave them as separate commits? i'm guessing the latter?

**Comment by joakime** [comment]
Don't worry about squashing commits, that's handled later, on our end after the review.

If I had any advice about the PR process, I would encourage you to *not* merge from a different branch into the one you submitted (it just makes the merge on our side very messy to have to merge a PR which has a merge of its own to deal with).

**Comment by dellgreen** [comment]
ok great thanks for the tips :)

**Comment by gregw** [comment]
This looks like a good problem to fix.  However, can it be tested more simply without the two mock classes, as that's a bit of noise to test a small edge case fix.

**Comment by dellgreen** [comment]
Having looked quickly at what would be needed, it looks like the test classes AbstractDoSFilterTest and ServletTester classes would need to be altered/expanded as looks like the connectors they create for the tests are hard coded for ipv4. Also I dont see any simple method to get a reference to the instantiated filter as the server seems to start up via a class parameter, as I eventually need a reference to the filters RateTracker to assert the results and also make sure the tracker doesnt timeout.

Also what if ipv6 is disabled on running system? the current solution has no dependency on ipv6 being enabled on teh system. I appreciate a lot of systems have ipv6 enabled by default, but recently I had to disable ipv6 on my mac or linux servers, i forget which, as there was a bug in dns resolver (cant rememebr which process) causing hanging.

Looks like i would possibly be trading one set of noise for another? I'll make the changes if you wish, although it probably is prefereable to continue with others issues i am working on for now?

**Comment by joakime** [comment]
@dellgreen thanks for the PR.

Feel free to ask for a patch redemption: https://webtide.com/patch-for-a-patch/

**Comment by dellgreen** [comment]
cool thanks :)

**Pull request merged**
