### PR TITLE
HttpExchange retained by HttpSenderOverHTTP which caused memory leak(12.0.x)

### PR DESCRIPTION
**Pull request by shaoxt**
Same issue describe in this PR

https://github.com/jetty/jetty.project/pull/11779

### CODE REVIEW

**Comment by shaoxt** [comment]
PR for https://github.com/jetty/jetty.project/issues/11781

**Comment by shaoxt** [comment]
ECA is signed, but the github didn't detect.

**Comment by olamy** [comment]
> ECA is signed, but the github didn't detect.

When did you sign it? This might not be immediate.

**Comment by olamy** [comment]
I have revalidate it.

**Comment by shaoxt** [comment]
> I have revalidate it.

Appreciate it.

Can you please review the PR ?

**Pull request closed without merging**
