### PR TITLE
jetty 12.0.x no need test jar

### PR DESCRIPTION
**Pull request by olamy**
- **simplify pom and avoid using test-jar for distribution test**
- **spotless:apply**

### CODE REVIEW

**Review by sbordet — CHANGES_REQUESTED** [review]
I don't particularly like to put test classes in `src/main`, they belong to `src/test`.

If I need to reuse test classes, then it's natural to depend on a `test-jar`.

What is the problem this PR is trying to solve?

**Comment by olamy** [comment]
> I don't particularly like to put test classes in `src/main`, they belong to `src/test`.
>

I do not see a problem with having this abstract class here (it's not a test class at all)
This module is intended to be used for testing (see the name  ) only, and this class is abstract. 
And we shared classes (all other tests) which are definitely not needed by other modules (we are polluting the classpath for no reason except one class)

 
> If I need to reuse test classes, then it's natural to depend on a `test-jar`.
> 
> What is the problem this PR is trying to solve?

I want to avoid producing this test jar which is not needed and add more artifact (with not needed classes) for no reason 

And you cannot use `-Dmaven.test.skip=true`

**Comment by olamy** [comment]
@sbordet  :) https://github.com/jetty/jetty.project/issues/3080

**Comment by olamy** [comment]
more seriously I'm looking at improving build time and IO usage (disk) is a big problem.
So reducing the size of generated/copied file might help (here we can reduce the need of sharing a jar file with only 1 class)

By the way I wonder why do we have all of those `test-ee9-distribution` `test-ee10-distribution` with duplicated classes and test with only differences some module names such `ee10-webapp` vs `ee9-webapp` those could test parameter using `ParameterizedTest` 
Reducing this will reduce the number of modules, and so IO/build time.

**Comment by olamy** [comment]
finally moving `AbstractJettyHomeTest.java` is even better as it reduce inter dependencies (for only this single class), no more need of this test-jar as test classes were not re use but only this abstract class doing absolutely no test but just an helper as all other classes from `jetty-tester` module.

**Comment by olamy** [comment]
done via https://github.com/jetty/jetty.project/pull/12274

**Pull request closed without merging**
