### PR TITLE
Issue #3731 - Testing various ways to use CDI

### PR DESCRIPTION
**Pull request by joakime**
Creating a test-cdi2-webapp and using it from `/test-distribution/` in different ways.

1. weld is included in `WEB-INF/lib`, provided by webapp itself.
2. weld is provided by server, via `cdi2` module. (webapp does not include weld)

### CODE REVIEW

**Comment by joakime** [comment]
> 2. weld is provided by server, via `cdi2` module. (webapp does not include weld)

@janbartel is it expected that the `cdi2` module we have should provide what it needs for example 2?

**Comment by janbartel** [comment]
@joakime I think we decided that people using weld were mostly using it from inside their webapp, not from the server path, so the cdi2 module only supports example 1.

**Comment by joakime** [comment]
> btw, there's a weld 3.x release now, is that CDI3?

Why does the `cdi2` module exist then?
Pretty much everything that it provides is already present with the webapp.

If it's just for the server / system classpath tweaking, then perhaps we should rename it to indicate it's limited scope?  (it doesn't even pull in other modules that are required for weld to function, such as jsp)
Or just make it automatic. 
Eg: if the weld class `org.jboss.weld.environment.servlet.Listener` exists in webapp, and it's been added as an EventListener to the webapp.
Then automatically expose the CDI specific classes in the WebAppContext/WebAppClassloader?
A new kind of `CDIConfiguration` feature in Jetty?

**Comment by janbartel** [comment]
I'm not sure we need to do anything at the moment. As I commented at the time, we could do some integration code in jetty, but ideally in a vendor neutral way using only the cdi API, but that didn't seem feasible at the time.

Moreover, as the Jakarta ee changes are about to occur in the near future, IMHO we should wait and see what shakes out.

**Comment by joakime** [comment]
"vendor neutral" in what way?

1. We, Jetty, provide a CDI vendor neutral way for CDI implementations (weld and apache openwebbeans) to wire up in Jetty?
2. or CDI itself has a standard hook that Jetty just uses in a vendor neutral way?

Interestingly, of the only 2 CDI as a library options (weld and apache openwebbeans), both require the exposure of the same specific classes in Jetty's WebAppClassLoader.

* Apache OpenWebBeans - https://github.com/apache/openwebbeans/blob/openwebbeans-2.0.11/webbeans-jetty9/README.asciidoc
* Weld - http://docs.jboss.org/weld/reference/latest/en-US/html/environments.html#_class_loading

Both also ...
* Operate via a Listener
* Have a `META-INF/beans.xml` requirement

And Apache OpenWebBeans has it's own Jetty 9 module! \o/
https://github.com/apache/openwebbeans/blob/openwebbeans-2.0.11/webbeans-jetty9/src/main/config/modules/apache-owb.mod

And Apache OpenWebBeans has it's own Jetty Configuration class \o/
https://github.com/apache/openwebbeans/blob/openwebbeans-2.0.11/webbeans-jetty9/src/main/java/org/apache/webbeans/web/jetty9/OwbConfiguration.java

**Comment by gregw** [comment]
Ideally CDI would provide a standard SPI or integration API which we could implement to integrate...  so we could decorate Servlets, Filters and Listeners....

Note also the current javax renaming issue may mean the javax.inject at the core of CDI is going to be forked (rather than renamed), so CDI could be in a state of flux for a while.   So let's not commit too much effort until we can see a clear direction to go or have clear demand from real users.

But I'm +1 for deleting any modules for which there are no real users!

**Comment by joakime** [comment]
The broken module was never officially stable.
It's been labelled as Experimental since the beginning.

From our last release: https://github.com/eclipse/jetty.project/blob/jetty-9.4.19.v20190610/jetty-cdi/cdi-servlet/src/main/config/modules/cdi.mod

```
[description]
Experimental CDI/Weld integration

[depend]
cdi1
```

**Pull request merged**
