### PR TITLE
HttpRequest has a wrong HTTP Version.

### PR DESCRIPTION
**Pull request by Drdoteam**
# Problem
- When I use HttpClient with HTTP/2(HTTP2Client, HttpClientTransportOverHTTP2), it creates HttpRequest Objects has wrong HTTP Version(HTTP/1.1)
- HttpRequest is never assigned a HTTP Version.  
(But, HttpResponse is assigned a right HTTP Version.)  
- Wrong version is printed.
```
[HttpClient@627185331-17] DEBUG org.eclipse.jetty.client.HttpSender.queuedToBegin(219) - Request begin HttpRequest[POST /3/device/bad-token HTTP/1.1]@cb51256
[HttpClient@627185331-17] DEBUG org.eclipse.jetty.client.HttpSender.headersToCommit(255) - Request committed HttpRequest[POST /3/device/bad-token HTTP/1.1]@cb51256
```

# Changes
- Add 'getHttpVersion' method to HttpClientTransport interface.  
Because, HttpClientTransport represents what transport implementations.
- Its children implements  'getHttpVersion' method.  
AbstractHttpClientTransport returns HTTP_1_1.   
HttpClientTransportOverHTTP2 returns HTTP_2.  
- HttpClient assign HttpClientTransport's HTTP Version when HttpRequest is being created.

### CODE REVIEW

**Comment by Drdoteam** [comment]
ip-validation is failed.
Should I add "signed off by: Drdoteam <drdoteam@gmail.com>" in commit ?

**Comment by gouessej** [comment]
Please sign the CLA. Then, configure your email and your user name in GIT. After that, use "git commit -s".
http://www.eclipse.org/jetty/documentation/current/contributing-patches.html
https://help.github.com/articles/setting-your-email-in-git/
https://help.github.com/articles/setting-your-username-in-git/

**Comment by gouessej** [comment]
Please follow the coding standards of this project:
https://www.eclipse.org/jetty/documentation/current/coding-standards.html

**Comment by sbordet** [comment]
Thanks for raising this issue.

I would think that would be much simpler to add the following line:

```java
public class HttpConnectionOverHTTP2 ...
{
    ...

    @Override
    protected SendFailure send(HttpExchange exchange)
    {
        // Line that fixes the issue
        exchange.getRequest().version(HttpVersion.HTTP_2);

        normalizeRequest(exchange.getRequest());
        ...
}
```

**Comment by Drdoteam** [comment]
@sbordet Yeah, it is more simple.
Could I fix code and re-commit them ?

@gouessej I signed CLA and signed off, but it failed consistently..;;
how to figure it out ?

**Comment by sbordet** [comment]
@Drdoteam please file an issue at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Jetty, and I will take care of adding that line.
Thanks for raising this !

**Comment by Drdoteam** [comment]
You're welcome.
I'm implementing APNs HTTP/2 Provider API Client with Jetty now.
So, I hope to contribute to Jetty often.

And I will file this!

**Comment by Drdoteam** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=486589

**Comment by sbordet** [comment]
Great, thanks. 

BTW, are you the same person that raised this: http://stackoverflow.com/questions/34874992/proxied-http-2-apple-apn-connection-with-jetty-httpclient-9-3-6-v20151106 ?

**Comment by Drdoteam** [comment]
@sbordet No, I am not.

**Pull request closed without merging**
