### PR TITLE
[WIP] Issue #3167 - lazy creation of WebSocketCoreClient

### PR DESCRIPTION
**Pull request by lachlan-roberts**
#3167

### CODE REVIEW

**Comment by gregw** [comment]
On review of this, I can see a lot more refactoring is needed in the initialisation of websockets.  
So I have merged into https://github.com/eclipse/jetty.project/tree/jetty-10.0.x-3167-websocket-mapping and I'll do some reworking there.

**Comment by gregw** [comment]
@joakime @sbordet @lachlan-roberts 

I'm going to verbosely dump thoughts about WebSocket initialisation here prior to actually changing anything.... hopefully you can see anything I'm getting wring

__Current 10 setup:__

+ the javax SCI creates:
    * WebSocketCreatorMapping as a context attribute
    * JavaxWebSocketServletFrameHanderFactory as a context attribute
    * JavaxWebSocketServerContainer
    * WebSocketUpgradeFilter
    * For each annotated WS endpoint a mapping is added to the WebSocketCreatorMapping
    * annotations are used to configure the individual creator
+ the Jetty SCI creates:
    * JettyWebSocketServletFrameHandlerFactory as a context attribute
+ Jetty API WS Servlets create: 
    * more instances of WebSocketCreatorMapping!
    * mappings added to the WebSocketCreatorMapping
    * servlet init params are used to configure the WebSocketCreatorMapping
+ Javax Upgrade requests are:
    * matched by the WebSocketCreatorMapping in the WebSocketUpgradeFilter
    * a WS endpoint POJO is then created, 
    * because we have forgotten we are javax, we apply the pojo to  all WebSocketServletFrameHanderFactory found until one creates a FrameHandler
+ Jetty Upgrade requests are:
    * first mapped to the servlet
    * then mapped again by the private WebSocketCreatorMapping
    * a WS endpoint POJO is then created, 
    * because we have forgotten we are javax, we apply the pojo to  all WebSocketServletFrameHanderFactory found until one creates a FrameHandler


__What I don't like:__
 + the class names are too long and hard to understand
 + There are multiple WebSocketCreatorMapping instances, only one of which appears in the dump
 + When mapping a websocket, we forget it's API type and then have to apply the pojo to all WebSocketServletFrameHanderFactory in an array.  The mapping could remember the type, or better yet lets merge the creator and framehandlerfactory!
 + javax and jetty differ in how they are setup and configured


__What I want to do:__
 + both SCIs will share single instance of WebSocketMapping set as an context Attribute, with the first one creating it and the WebSocketUpgradeFilter
 + The WebSocketMapping will map pathSpecs to a tuple of (Creator, frameHandlerFactory, configuration), perhaps merged into a single class for each type of API.
 + The javax SCI will add mappings to the shared WebSocketMapping
 + The jetty WS Servlets will add mappings to the shared WebSocketMapping
 + The WebSocketUpgradeFilter will handle all WS upgrade requests.

thoughts?

**Comment by sbordet** [comment]
@gregw I cannot comment on the details, but there is an important use case that needs to be covered, which is web applications defining the `WebSocketUpgradeFilter` in `web.xml` (possibly _after_ some other filter - e.g. authentication filters).
This is necessary e.g. for CometD.

For this case to work, the creation of the default `WebSocketUpgradeFilter` must be skipped if the webapp defines one already (and BTW it may define more than one on different paths with different configs).
@joakime and I struggled quite a bit to make this work in 9.4.x so the functionality should be retained.

**Comment by gregw** [comment]
@sbordet different configs on different paths is fine.
So is using a predefined filter.... I think.... hmmm what if there are javax endpoints at a path not mapped by an existing filter?   Maybe if some filters exist, but are not mapped to /* then add one at /* after the preexisting.

But yes - think that case can be handled.

**Comment by gregw** [comment]
#3222 not yet merged

**Pull request closed without merging**
