### PR TITLE
Add ee8 modules with sources generated from ee9 sources

### LINKED ISSUE #7777: Failing Test Jetty 11 - ServletContextHandlerTest.testAsyncServletRequestListenerListener
Jetty 11 build keep failing with this
```
java.lang.AssertionError: 

Expected: <2>
     but: was <9>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.eclipse.jetty.servlet@11.0.9-SNAPSHOT/org.eclipse.jetty.servlet.ServletContextHandlerTest.testAsyncServletRequestListenerListener(ServletContextHandlerTest.java:1052)
```

https://jenkins.webtide.net/job/jetty.project/job/jetty-11.0.x/1026/testReport/

### PR DESCRIPTION
**Pull request by olamy**
add some modules ee8 translated from ee9:
- jetty-ee8-annotations  
- jetty-ee8-jaas  
- jetty-ee8-nested  
- jetty-ee8-plus  
- jetty-ee8-security  
- jetty-ee8-servlet	
- jetty-ee8-servlets  
- jetty-ee8-webapp

### CODE REVIEW

**Review by gregw — CHANGES_REQUESTED** [review]
The generated sources are not in jetty format.  Not in itself a big deal, but when I try to run test the checkstyle plugin complains and fails.
So either remove the plugin or preserve the formatting.

**Comment by olamy** [comment]
> The generated sources are not in jetty format. Not in itself a big deal, but when I try to run test the checkstyle plugin complains and fails. So either remove the plugin or preserve the formatting.

Will be complicated for some parts to keep exact formatting.
So I will remove it. Sorry I was using a `clean install` so checkstyle do not complain same as Jenkins as checkstyle is executed before source generation.

**Comment by olamy** [comment]
@gregw still some issues for now with `-config.jar` so just use `mvn test`

**Review by gregw — APPROVED** [review]
Bio readouts all in the green, looks like she is alive!

**Pull request merged**
