### PR TITLE
Fix getCharacterEncoding issue with #10563

### PR DESCRIPTION
**Pull request by gregw**
Do not persist a defaulted charset used in the request.

### CODE REVIEW

**Comment by gregw** [comment]
@olamy can you check if this fixes the TCK failures?

**Comment by olamy** [comment]
@gregw Tested. Most of the tests are passing now.
Except:
`request.getReader();` with an unknown charset `Content-Type:text/plain; charset=DoesNonExist` should throw `UnsupportedEncodingException` but here it's another exception.

**Comment by gregw** [comment]
@olamy can you run again now?

**Comment by olamy** [comment]
@gregw all good! thanks

**Review by olamy — APPROVED** [review]

**Pull request merged**
