### PR TITLE
Fixes some spelling mistakes, see issue #4160

### PR DESCRIPTION
**Pull request by gouessej**
Signed-off-by: Julien Gouesse <gouessej@orange.fr>

### CODE REVIEW

**Comment by gouessej** [comment]
@joakime This time, it should work.

**Comment by joakime** [comment]
A *MUCH* smaller PR, thank you for that. :-)

**Comment by sbordet** [comment]
@gregw I don't think this PR was merged in the right branch.
It says it merged into `master` but we don't use `master`.
I don't see the changes of this PR in `jetty-9.4.x'.

**Comment by gouessej** [comment]
@sbordet  Oops, sorry. Should I make another pull request on the branch jetty-9.4.x?

**Comment by sbordet** [comment]
@gouessej yes please.

**Comment by gouessej** [comment]
@sbordet I'll do it in a few hours.

**Comment by gouessej** [comment]
@sbordet Done: https://github.com/eclipse/jetty.project/pull/4230

**Pull request merged**
