### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by isapir**

### CODE REVIEW

**Comment by WalkerWatch** [comment]
Before we can accept this Pull Request, you will need to sign an Eclipse Contributor Agreement. This is a requirement of the Eclipse foundation and is mandatory. It is very easy to set up, and instructions [can be found here](https://www.eclipse.org/jetty/documentation/current/contributing-patches.html).

**Comment by isapir** [comment]
@WalkerWatch I signed the ECA.  What's next?

**Comment by WalkerWatch** [comment]
@isapir If you re-commit these changes it should pick up the validation. Make sure to sign the commit by adding `-s`: `git commit -s -am 'Interesting commit message.' `

**Comment by joakime** [comment]
@WalkerWatch this PR shows as a Committer (and Author) of "noreply@github.com".  
Eclipse Legal will not allow us to merge this PR like this (it essentially has an anonymous committer/author)

**Comment by WalkerWatch** [comment]
@isapir Can you re-submit this in another pr after signing your commits?

**Comment by isapir** [comment]
I will try.  If it takes too long then feel free to edit the file and close this issue.  no problem.

**Pull request merged**
