### PR TITLE
Cherry-pick of Improvements to PathSpec for Jetty 10.0.x

### LINKED ISSUE #8126: Improve PathSpec handling with Regex
**Target Jetty version(s)**
10.0.x

**Enhancement Description**
Take effort done in PR #7947 and port to Jetty 10.0.x

### PR DESCRIPTION
**Pull request by joakime**
From PR: #7947 
From commit: 5b4d1dd1c64482d00919029e0a2ba4ac1f4d8e6b

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by gregw** [comment]
@joakime this looks to have broken a lot of tests... which don't look like flakes ?

**Comment by joakime** [comment]
Yes, some things I appear to have missed.
I'll take care of them.

**Review by sbordet — DISMISSED** [review]

**Comment by sbordet** [comment]
@joakime is this still a draft?

**Comment by joakime** [comment]
@sbordet I flagged it as draft as it wasn't ready yet.
There were still a few bugs to work out.

I believe I've fixed the final issues.
In the process I discovered a corner case with RegexPathSpec that needs a backport to Jetty 9.4.x (see commit 4e419d80cc53b23b1e82a4ae0c96614d409288cd)

**Review by sbordet — APPROVED** [review]

**Pull request merged**
