### PR TITLE
Issue #3302 Supporting host:ip in X-Forwarded-For

### PR DESCRIPTION
**Pull request by abarsov**
Signed-off-by: alexey.barsov <foster_licey_reg@mail.ru>

### CODE REVIEW

**Comment by abarsov** [comment]
I have signed ECA after I noticed "The pull request did not pass Eclipse validation..."

**Comment by gregw** [comment]
I have manually verified the ECA for alexey.barsov@jetbrains.com.  Not sure why the auto verification is still red?

**Comment by gregw** [comment]
@joakime pointed out that you signed ECA as alexey.barsov@jetbrains.com but signed off commit as foster_licey_reg@mail.ru

**Comment by abarsov** [comment]
> I see you have based this on your 9.3 branch - do you want it in 9.3 as well as 9.4 (which is the target of this PR?).
yes, I would like to see that both in 9.3 and in 9.4

**Comment by abarsov** [comment]
It is strange, it is reported that tests failedб but by Details link i see 
> [INFO] BUILD SUCCESS

**Comment by joakime** [comment]
Multiple scenarios of test `org.eclipse.jetty.client.HttpClientProxyTest.testProxyAuthenticationWithServerAuthentication` are failing.

**Comment by abarsov** [comment]
@gregw 
> Any chance you could also sign the ECA as foster_licey_reg@mail.ru?

I have done that already.
I have just checked it one more time on https://accounts.eclipse.org/users/abarsov/eca
and it reports 
> There is a valid ECA on file for foster_licey_reg@mail.ru.

@joakime 
locally `org.eclipse.jetty.client.HttpClientProxyTest.testProxyAuthenticationWithServerAuthentication` passes successfully in jetty-9.3.x branch with my changes,

Though it is a bit tricky to compile jetty project with all unit-tests switched on. 
Many of them fail (Windows 10). 
For instance, `InetAddressSetTest.testBadSingleton` fails with the following output:
```
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1290-b3)
OpenJDK 64-Bit Server VM (build 25.152-b3, mixed mode)

java.lang.AssertionError: unknown
	at org.junit.Assert.fail(Assert.java:88)
	at org.eclipse.jetty.util.InetAddressSetTest.testBadSingleton(InetAddressSetTest.java:92)
```

**Comment by gregw** [comment]
#3302

**Pull request merged**
