### PR TITLE
Issue #5711 Update to infinispan 11.0.x

### PR DESCRIPTION
**Pull request by aschugunov**
Update to Infinispan 11.0.9.
Infinispan started using the new docker hub repository.

Signed-off-by: Andrei Chugunov <develop.chugunov@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
This is an incomplete PR, as there are are now 44 test failures on infinispan related tests.

**Comment by aschugunov** [comment]
> This is an incomplete PR, as there are are now 44 test failures on infinispan related tests.

You are right. Infinispan changed the marshaller's conception and it requires to change registration process of marshallers.
After fixing the configuration I encountered with flaky test org.eclipse.jetty.server.session.AbstractSessionDataStoreTest#testStoreSession
so I am working on it

**Comment by janbartel** [comment]
@aschugunov nudge

**Comment by aschugunov** [comment]
> @aschugunov nudge

Hi @janbartel
To be honest, I was stuck with serialization errors after changing marshaller. Two unit tests are still failed. 
The issue is in different classloaders (web-app, server), my current implementation of marshaller does not work with this feature.

Could you get some advice on how it should be solved, please?

**Comment by janbartel** [comment]
@aschugunov has infinispan changed to use a thread pool do to serialization/deserialization? If so, it won't know anything about the context classloader (ie the classloader specific to the webapp). Is there any interface provided to allow you to set the context classloader to use?

**Comment by aschugunov** [comment]
> @aschugunov has infinispan changed to use a thread pool do to serialization/deserialization? If so, it won't know anything about the context classloader (ie the classloader specific to the webapp). Is there any interface provided to allow you to set the context classloader to use?

@janbartel It looks like infinispan uses org.jboss.threads.JBossExecutors#classLoaderPreservingTaskUnchecked and  ContextClassLoaderSavingRunnable (class is from jboss-threads library) under the hood and should save context classloader.
Unfortunately, I didn't understand why it does not happen

Moreover, tests are passed separately but failed during a common run

**Comment by janbartel** [comment]
@aschugunov I've actually had to open a different PR for this, as the changes to infinispan resulted in some fairly invasive and extensive changes. I will close this pull request, but thank you for the initial work that you did on this, and please feel free to open more prs to improve the infinispan integration.

**Pull request closed without merging**
