### PR TITLE
Issue #9400 Handle scan of weird jar format

### PR DESCRIPTION
**Pull request by janbartel**

### CODE REVIEW

**Comment by janbartel** [comment]
The `elasticsearch-x-content` jar has a very odd format, whereby it seems to contain the contents of many other jars, eg:

>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/versions/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/versions/9/
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/versions/9/module-info.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/MANIFEST.MF
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/services/
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/services/com.fasterxml.jackson.core.JsonFactory
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/maven/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/maven/com.fasterxml.jackson.dataformat/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/maven/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/maven/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/pom.properties
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/META-INF/maven/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/pom.xml
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileBufferRecycler.class
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/databind/
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/databind/SmileMapper$Builder.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/databind/SmileMapper.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileParserBootstrapper.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileParser.class
>   created: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/async/
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/async/NonBlockingParserBase.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/async/NonBlockingByteArrayParser.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileConstants.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileWriteContext.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileGenerator$Feature.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileGenerator.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileParserBase$1.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileFactoryBuilder.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileFactory.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileUtil.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/PackageVersion.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileGenerator$SharedStringNode.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileParser$Feature.class
>  inflated: IMPL-JARS/x-content/jackson-dataformat-smile-2.13.2.jar/com/fasterxml/jackson/dataformat/smile/SmileParserBase.class
>  inflated: IMPL-JARS/x-content/LISTING.TXT

Our class scanning was expecting to find `module-info.class` at the root of the jar, not buried down at some sublevel. Changed the `AnnotationParser` to look for `module-info.class` as the last name element.

**Review by joakime — CHANGES_REQUESTED** [review]
Another thing we can do.

If a directory contains a `.` (period char), it should be ignored (and all sub-content).
(We could expand this to other illegal characters in the future)

That's an invalid directory for a JAR in a ClassLoader and would never be usable.

We should also ensure that the asm produced package name for the scanned class fits in the jar file.

Example: a file in the jar `a/directory/deep/org/eclipse/jetty/Server.class`, which is scanned by ASM shows the package as `org.eclipse.jetty`.
That is a bad class, that cannot be accessed by the ClassLoader.

**Comment by sbordet** [comment]
@janbartel the format:

`/META-INF/versions/9/module-info.class`

is legal and the widely accepted solution to deploy Java 8 compliant jars (that won't look into `/META-INF/versions/`) -- where all the classes are compiled with target=8 -- but have the same jar also work in Java 9+ runtimes (which will look into `/META-INF/versions/`), so we should definitely support this style.

This also means that we should not look into _any_ sublevel, but only under `/META-INF/versions/<version>/module-info.class`, where `<version>` may be any number >= 9.

**Comment by janbartel** [comment]
> @janbartel the format:
> 
> `/META-INF/versions/9/module-info.class`
> 
> is legal and the widely accepted solution to deploy Java 8 compliant jars (that won't look into `/META-INF/versions/`) -- where all the classes are compiled with target=8 -- but have the same jar also work in Java 9+ runtimes (which will look into `/META-INF/versions/`), so we should definitely support this style.
> 
> This also means that we should not look into _any_ sublevel, but only under `/META-INF/versions/<version>/module-info.class`, where `<version>` may be any number >= 9.

@sbordet the point is that we actually _don't_ want to look at `module-info.class` at all, because it is not a useful class to look at for servlet annotations nor the class inheritance hierarchy. The problem was that before this PR, we couldn't correctly _ignore_ a `module-info.class` file buried at some deep level inside a jar.

**Comment by janbartel** [comment]
> Another thing we can do.
> 
> If a directory contains a `.` (period char), it should be ignored (and all sub-content). (We could expand this to other illegal characters in the future)
> 
> That's an invalid directory for a JAR in a ClassLoader and would never be usable.
> 
> We should also ensure that the asm produced package name for the scanned class fits in the jar file.
> 
> Example: a file in the jar `a/directory/deep/org/eclipse/jetty/Server.class`, which is scanned by ASM shows the package as `org.eclipse.jetty`. That is a bad class, that cannot be accessed by the ClassLoader.

@joakime we already do ignore `.` directories.  For the weird `a/directory/deep/org/eclipse/jetty/Server.class` I don't see where that would be retained as `org.eclipse.jetty.Server.class` other than if the class actually reports that as its package.

**Comment by janbartel** [comment]
> @sbordet the point is that we actually don't want to look at module-info.class at all, because it is not a useful class to look at for servlet annotations nor the class inheritance hierarchy. The problem was that before this PR, we couldn't correctly ignore a module-info.class file buried at some deep level inside a jar.

@sbordet to be clear, this PR has nothing to do with correctly parsing `META-INF/versions` which we already do. This is purely about some odd jar that seems to be a zip file containing jars of other jars - see that everything is contained in some sub-directory called `IMPL-JARS/x-content/` - tripping up the parser and triggering an NPE.

**Comment by gregw** [comment]
I would go as far as saying this is not a jar file.  A jar file is a zip file that in the top level has classes in a package hierarchy and a META-INF directory with some meta data.
This is a zip file that has class files and META-INF directories in some other layout that I have never seen before.

I think it is good that we correctly skip `module-info.class` files no matter where they are found.... but should we actually be scanning any of the classes in this zip file, as none of them are in the correct location.   Should we be rejecting any class file whose location in the zip does not match the package the class files advertises (modulo multi-version support).

**Comment by janbartel** [comment]
Before we expend too much more energy on this issue, let's remember that users can always exclude jars from being parsed.

**Comment by gregw** [comment]
Can you at least put in a TODO in the code somewhere saying that we should check that a discovered class file is in it's correct location within the zip file before scanning it.

Can we also push back to the OP and/or the source of that jar and ask WTF?

**Comment by janbartel** [comment]
@gregw we could check the package matches the path of the class, but it would be a lot easier to do in jetty-12 than in jetty-10. I propose that we commit this change as-is, then open a separate enhancement to check package with class location in jetty-12.

**Comment by joakime** [comment]
> Can you at least put in a TODO in the code somewhere saying that we should check that a discovered class file is in it's correct location within the zip file before scanning it.

I think this would be the other way around, scan the class, take the reported fully qualified class, and then check that it's in a valid location.

**Review by gregw — APPROVED** [review]
Approving on the basis that an issue will be opened to add in 12 the checking of a correct package during the scan.  Please open issue before merge.

**Review by joakime — APPROVED** [review]

**Comment by janbartel** [comment]
@gregw I raised the following for the jetty-12 enhancement: https://github.com/eclipse/jetty.project/issues/9511

**Pull request merged**
