### PR TITLE
Issue #847 - add writeTimeout to jetty websocket API in jetty 10

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Signed-off-by: Lachlan Roberts <lachlan@webtide.com>

#847

### CODE REVIEW

**Review by gregw — COMMENTED** [review]
Why is a write timeout needed in addition to the idle timeout, but not a read timeout?  That feels asymmetric!

Is this for DOS protection?  If so, then a minimum data rate might be better that a timeout because the time to write a 10GB message is obviously longer than a 1GB message, so DOS can just send lots of slow little message 1 byte at a time.

**Comment by sbordet** [comment]
@gregw the write timeout is required to implement the JSR API `RemoteEndPoint.Async#setSendTimeout(long)`.

**Comment by gregw** [comment]
If this timeout is needed for the jsr API, then let's not put it in common and in other APIs.  It is a wrong, non scalable configuration, like the blocking timeout that caused so many issues in HTTP.

**Comment by lachlan-roberts** [comment]
@gregw this timeout is already a feature of the core API so I wanted to give it access through the jetty API as well. I don't understand why it is a "wrong, non scalable configuration".
But if you don't think it is needed in the jetty API we can close this PR.

**Comment by gregw** [comment]
It doesn't scale with message size as data rate and idle timeout does. It's asymmetric as there is no read timeout. Best to leave it out of our API and look to deprecated it in core.

**Pull request closed without merging**
