### PR TITLE
feat(mimetypes): Added mimetypes for font files .eot, .woff, .woff2

### PR DESCRIPTION
**Pull request by jhaeyaert**
Do you think it's possible to add the following mimetypes (common font formats) :

- .eot :application/vnd.ms-fontobject (http://www.iana.org/assignments/media-types/application/vnd.ms-fontobject)
- .woff -> application/font-woff (https://www.w3.org/TR/WOFF/#IMT)
- .woff2 -> font/woff2 (https://www.w3.org/TR/WOFF2/#IMT)

Thanks

### CODE REVIEW

**Comment by WalkerWatch** [comment]
@jhaeyaert Before we can accept this Pull Request, you will need to sign an Eclipse Contributor Agreement. This is a requirement of the Eclipse foundation and is mandatory. It is very easy to set up, and instructions [can be found here](https://www.eclipse.org/jetty/documentation/current/contributing-patches.html).

**Comment by jhaeyaert** [comment]
OK, Done.

**Comment by WalkerWatch** [comment]
@jhaeyaert Will just need you to add to/amend the commit to get the system to reprocess the IP validation.

**Comment by gregw** [comment]
I accepted on the basis of the signed ECA even though the auto check didn't notice.
thanks

**Pull request merged**
