### PR TITLE
Support Mongo 2.x and 3.x API in Jetty 9.2.x

### PR DESCRIPTION
**Pull request by w2cc**

### CODE REVIEW

**Comment by joakime** [comment]
@w2cc before we can accept this, we need you to satisfy Eclipse Legal.  Can you file a CLA with Eclipse, and sign the commits?

**Comment by w2cc** [comment]
I have satisfy Eclipse Legal with w2cc@w2cc.cc

**Comment by jmcc0nn3ll** [comment]
can you sign the commit and repush it? -s option on commit

**Comment by w2cc** [comment]
I have repush and create a new pr #636

**Pull request closed without merging**
