### PR TITLE
ProxyConnectionFactory should not ignore TLVs

### LINKED ISSUE #4540: ProxyConnectionFactory should not ignore TLVs
**Jetty version**
master

**Java version**
all

**OS type/version**
all

**Description**
In version 2 of the proxy protocol, it allows for application-specific TLV types:
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

See section 2.2.7.  Basically the type code in range  0xE0..0xEF gets associated with an arbitrary block of bytes.  

Currently it appears these custom TLVs are being ignored:
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ProxyConnectionFactory.java#L545

I think ideally these custom TLVs should be accessible by the underlying connection.  For example, proxyEndPoint could simply maintain a map from type -> byte[].  e.g. 

  default:
      proxyEndPoint.setTLV(type, value);

Or perhaps it could even reuse setAttribute() for this if it treats the type code as a string. 

There should be an associated getter or reader that the downstream Connection can invoke.  e.g.

    byte[] value = proxyEndPoint.getTLV(type)

### PR DESCRIPTION
**Pull request by m0mus**
Signed-off-by: Dmitry Kornilov <dmitry.kornilov@oracle.com>

### CODE REVIEW

**Comment by m0mus** [comment]
On behalf of @jjspiegel. Fixes #4540

**Comment by sbordet** [comment]
@m0mus @jjspiegel I have merged your contribution, and took the chance to generify it better so all TLVs are now exposed, not only the custom ones.
The API is slightly different, `getTLV()` vs `getCustomValue()`.
Thanks!

**Comment by jjspiegel** [comment]
Thanks @sbordet - Do we need to do anything special to get this ported to the 9.4.x line?

**Comment by sbordet** [comment]
@jjspiegel it's a new feature for 10.0.x, so we don't plan to backport it to 9.4.x.

**Pull request merged**
