### PR TITLE
Wrong ? packages in the JNDI mail example

### PR DESCRIPTION
**Pull request by karstenhusberg**
I think these two packages are wrong in the document. At least it works much better for me if changed as suggested.

### CODE REVIEW

**Review by janbartel — APPROVED** [review]
Thanks

**Comment by olamy** [comment]
@karstenhusberg thanks for the PR but we need you to sign the ECA (Eclipse Contributor Agreement) you will find more details here https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Comment by karstenhusberg** [comment]
Sorry, should have guessed that one couldn't just submit changes that easy :-) I've now signed. Thanks for a good documentation!

**Comment by olamy** [comment]
> Sorry, should have guessed that one couldn't just submit changes that easy :-) I've now signed. Thanks for a good documentation!

haha. All good now.
Thanks!

**Pull request merged**
