### PR TITLE
The replaceCookie method renamed to putCookie and refined #10797

### LINKED ISSUE #10797: Multiple identical `Set-Cookie` response lines produced
**Jetty version(s)**
Jetty 12

**Jetty Environment**
All: ee10, ee9, ee8

**Java version/vendor** `(use: java -version)`
OpenJDK 17

**OS type/version**
Linux / Ubuntu

**Description**
Multiple `Set-Cookie` response lines produced.

**How to reproduce?**

When testing for the bug reported in issue #10794 it was noticed that the response produces multiple `Set-Cookie` lines.
See below, testing with Jetty 12.0.2 with ee10-demos, using curl.

```
[tmp]$ curl -vvv http://localhost:8080/ee10-test?a=b
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /ee10-test?a=b HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: Jetty(12.0.2)
< Set-Cookie: visited=yes
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: visited=yes
< Set-Cookie: visited=yes
< Location: /ee10-test/;a=b
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

This produced 3 identical `Set-Cookie: visited=yes` lines.

### PR DESCRIPTION
**Pull request by gregw**
Fix #10797 by make addCookie always replace existing SetCookie fields. Deprecated replaceCookie method.

### CODE REVIEW

**Review by janbartel — DISMISSED** [review]
Weren't there any explicit tests for addCookie and replaceCookie that should be changed?

**Review by joakime — CHANGES_REQUESTED** [review]
This issue appears in ee9/ee8 as well.
But I don't see changes to that codebase for this issue.
Is the core classes the only place to address this?
Wouldn't it make sense to also cease using replaceCookie in the ee9/ee8 codebase?

**Comment by joakime** [comment]
Some ee9 places to address...

```
jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/ContextHandler.java:                _httpChannel.getResponse().replaceCookie(cookie);
jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Request.java:            cookieCache.replaceCookieList(servletCookieList);
jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/Response.java:    public void replaceCookie(HttpCookie cookie)
jetty-ee9/jetty-ee9-nested/src/main/java/org/eclipse/jetty/ee9/nested/SessionHandler.java:                baseRequest.getResponse().replaceCookie(cookie);
jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/ResponseTest.java:        response.replaceCookie(HttpCookie.from("Foo", "123456"));
jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/ResponseTest.java:        response.replaceCookie(HttpCookie.from("Foo", "123456", Map.of(HttpCookie.DOMAIN_ATTRIBUTE, "A", HttpCookie.PATH_ATTRIBUTE, "/path")));
jetty-ee9/jetty-ee9-nested/src/test/java/org/eclipse/jetty/ee9/nested/ResponseTest.java:        response.replaceCookie(HttpCookie.from("Foo", "123456", Map.of(HttpCookie.DOMAIN_ATTRIBUTE, "B", HttpCookie.PATH_ATTRIBUTE, "/path")));
```

**Comment by gregw** [comment]
> This issue appears in ee9/ee8 as well. But I don't see changes to that codebase for this issue. Is the core classes the only place to address this? Wouldn't it make sense to also cease using replaceCookie in the ee9/ee8 codebase?

The ee8/ee9 code base is substantially as it was in Jetty-10/Jetty-11 (buf for bug compatible).   They had both addCookie and replaceCookie, so we are not intending to change the behaviour of those.     Note that these are methods on `ee9/nested/Response`  not `core/server/Response` .

This PR just makes addCookie the same as replaceCookie for core and EE10.

**Comment by joakime** [comment]
> The ee8/ee9 code base is substantially as it was in Jetty-10/Jetty-11 (buf for bug compatible). They had both addCookie and replaceCookie, so we are not intending to change the behaviour of those. Note that these are methods on `ee9/nested/Response` not `core/server/Response` .
> 
> This PR just makes addCookie the same as replaceCookie for core and EE10.

The bug where we produce multiple `Set-Cookie` lines in a response is also present in ee9-demos.

Results from Jetty 12.0.2 with the ee9-demos ...

```
[tmp]$ curl -vvv http://localhost:8080/ee9-test?a=b
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /ee9-test?a=b HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: Jetty(12.0.2)
< Set-Cookie: visited=yes
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: visited=yes
< Set-Cookie: visited=yes
< Location: /ee9-test/;a=b
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by gregw** [comment]
@joakime can jetty-9/10/11 produce duplicate cookies in the same circumstance?
I can't see anything in the servlet spec that says addCookie should be a replaceCookie.

I'm now doubting this whole PR....

**Comment by joakime** [comment]
@gregw here's the results of testing 9.4.53, 10.0.18, and 11.0.18 behaviors.

**Test of 9.4.53.v20231009 distribution `demo-base`**

``` shell
$ curl -vvv http://localhost:8080/test?a=b
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test?a=b HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Set-Cookie: visited=yes
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://localhost:8080/test/?a=b
< Content-Length: 0
< Server: Jetty(9.4.53.v20231009)
< 
* Connection #0 to host localhost left intact
```

**Test of 10.0.18 `demo` module**

``` shell
$ curl -vvv http://localhost:8080/test?a=b
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test?a=b HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Set-Cookie: visited=yes
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://localhost:8080/test/?a=b
< Content-Length: 0
< Server: Jetty(10.0.18)
< 
* Connection #0 to host localhost left intact
```

**Test of 11.0.18 `demo` module**

``` shell
$ curl -vvv http://localhost:8080/test?a=b
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /test?a=b HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Set-Cookie: visited=yes
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://localhost:8080/test/?a=b
< Content-Length: 0
< Server: Jetty(11.0.18)
< 
* Connection #0 to host localhost left intact
```

Looks like those do not produce the duplicate `Set-Cookie: visted=yes` lines.

**Comment by gregw** [comment]
@joakime on review, I think we need to keep addCookie and putCookie semantics. 
If an application calls addCookie multiple times, then there will be multiple Set-Cookie headers.

**Comment by janbartel** [comment]
Let me just run this through the tck before I approve: https://jenkins.webtide.net/job/tck/job/servlettck-run-12.0.x-ee10/531/

**Comment by gregw** [comment]
@joakime note that I changed the rewrite rule to use putCookie rather than addCookie, so that should fix the demo.

**Review by janbartel — APPROVED** [review]

**Review by joakime — APPROVED** [review]

**Pull request merged**
