### PR TITLE
 Issue #11560 - Implement EIP-4361 Sign-In With Ethereum

### PR DESCRIPTION
**Pull request by lachlan-roberts**
## Issue #11560

Add new Jetty module called `jetty-siwe`, which implements EIP4361 Sign-In With Ethereum via the `EthereumAuthenticator`. This allows you to authenticate with a crypto wallet such as MetaMask.

See https://eips.ethereum.org/EIPS/eip-4361

Replaces https://github.com/jetty/jetty.project/pull/11883

### CODE REVIEW

**Comment by joakime** [comment]
Instead of `jetty-siwe` how about one of the following ...

* `jetty-ethereum-auth`
* `jetty-ethereum-sign-in`
* `jetty-ethereum`
* `jetty-ethereum-security`

**Comment by gregw** [comment]
> Instead of `jetty-siwe` how about one of the following ...
> 
> * `jetty-ethereum-auth`
> * `jetty-ethereum-sign-in`
> * `jetty-ethereum`
> * `jetty-ethereum-security`

@joakime I'm guessing that @lachlan-roberts will reply with (It is called siwe or sign-in with etherium in the spec).    Which is a good point.

But if we were to implement any more etherium based features, they would probably end up in this module, so I'm OK with  the `jetty-ethereum` module name.

Actually, it really should be `jetty-integrations/jetty-ethereum` and we should probably move openid to `jetty-integrations/jetty-openid` as well (deprecating old classes for now).

**Review by gregw — CHANGES_REQUESTED** [review]
Sorry... but I think this should be moved to `jetty-integrations/jetty-ethereum`

**Review by gregw — APPROVED** [review]
I think we should also think above moving openid?

**Pull request merged**
