### PR TITLE
Experiment for cancelling callback

### PR DESCRIPTION
**Pull request by gregw**
This is a thought bubble of how this could be done... but much more work is needed to make sure cancel propagates correctly through things like IteratingCallback.

I'm not yet convinced this is the right solution.

### CODE REVIEW

**Comment by lorban** [comment]
To fix #11854, canceling must be propagated to wrapped callbacks so this feature definitely is needed.

I tried adding a new `cancel()` method to `Callback` but I found that this quickly became too invasive. So I came up with a slightly modified version of your original proposal in #11860 that does not require any modification to the `Callback` interface.

**Comment by gregw** [comment]
@lorban I tried to use this PR and it is too difficult!  The abstraction is not exactly correct.     But I have an idea for a variant that might work....    I'll give that a go.  Feel free to continue playing with it and we can hangout tomorrow to discuss our findings.

**Comment by gregw** [comment]
@lorban @sbordet My second attempt at this also failed.... but I have hope for take 3.     I think the crux is in our IteratingCallback class, that already has `abort` semantic... but it is not well implemented and not entirely serialized with other calls.

Let's hangout tonight to discuss.

**Comment by gregw** [comment]
I'm closing this as a dead end.

**Pull request closed without merging**
