### PR TITLE
Issue #2821 Add SpnegoAuthentication support to jetty client

### PR DESCRIPTION
**Pull request by CaoManhDat**
Signed-off-by: Cao Manh Dat <caomanhdat317@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@CaoManhDat I actually expected a PR that was just checking for `Result.getURI()` and if it was `null` not adding to the result store.

A complete implementation of SPNEGO is not easy exactly because it's a connection based authentication that completely violates the HTTP rules.
Your implementation in this PR does not take into account that, so it can receive the challenge in one connection, but then send the challenge reply on another.

I would accept a PR that only does the `null` check for this issue.

I'm not sure we want to maintain a SPNEGO implementation though (although we can change our mind); I can give directions on how to properly implement it.

Thanks!

**Comment by sbordet** [comment]
@CaoManhDat I'll close this PR. Please open a new issue about implementing SPNEGO, or look at #1708.

As for the implementation, `AuthenticationProtocolHandler` currently does not support using the same connection to send authentication challenges replies.
This is because it taps on the _complete_ event to handle authentication, when the `Connection` has already been released back to the `ConnectionPool` and may be used by other requests.

The idea would be perhaps to have `AuthenticationProtocolHandler` ask to the `Authentication` implementation if it needs to stay on the same connection, and if so, tap on the _response success_ event, and expose the `Connection` object to the `Authentication` implementation for use, and avoid that the `Connection` is released to the `ConnectionPool`.
It's going to be rather complicated.

**Comment by CaoManhDat** [comment]
Thank @sbordet, I am following your idea but I can't find a nice way to expose the `Connection` object to the `Authentication`, should we do that in `HttpReceiver`? Will that cause conflict with https://github.com/eclipse/jetty.project/issues/560

**Comment by CaoManhDat** [comment]
BTW: Correct me if I wrong but when I look into `SpnegoAuthenticator` in Jetty server side. I can't find anything relate to `connection` based here? Therefore even we send the challenge reply in another `connection` that should be fine. After the `Authorization` process finish the last `Connection` will be authorized (in some case: the server may return a cookie to skip the `authorization` process for subsequence requests)

**Pull request closed without merging**
