### PR TITLE
Issue #2941 - JDK 11: UnsupportedOperationException at AnnotationParser.scanClass.

### PR DESCRIPTION
**Pull request by sbordet**
Issue #2941.

Updated to ASM 7.0-beta, and defaulted AnnotationParser to ASM 7.

Signed-off-by: Simone Bordet <simone.bordet@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
@janbartel we have OSGi test errors but I have no clue why, so I'll defer to the greatest OSGi expert I know: you!

**Comment by janbartel** [comment]
@sbordet you mean I'm the _only_ person with eve a faint understanding of osgi that you know :)

The problem is that the spifly jar (which is necessary for ServiceLoader to work in the osgi environment) does not support asm 7:  I tried updating to their latest version 1.0.14 released on 20th August 2018 and it excludes version 7 on the import for asm:  Import-Package: org.objectweb.asm;version="[5,7)"

I googled but can't find any roadmap for when they expect to support asm-7.

**Comment by joakime** [comment]
@janbartel Created new Jira for Aries SPI Fly upgrade for ASM 7 -> https://issues.apache.org/jira/browse/ARIES-1844

**Comment by sbordet** [comment]
@janbartel given we can use ASM 7.0-beta, but Aries SPI Fly is not there yet, what are your thoughts on merging this?

We use SPI Fly only for testing, but this change should be merged to allow people to use JDK 11 with Jetty.

I'm for disabling the tests for now, filing an issue to re-enable them when SPI Fly is compatible with JDK 11.

**Comment by janbartel** [comment]
@sbordet it's not only the tests - anybody that wants to use jetty in osgi will also need spifly to work. So if you do a release without an updated version of spifly, then osgi is broken.

**Comment by sbordet** [comment]
@janbartel it may take a while for SPI Fly to catch up, and it would be only broken for those that have targeted Java 11 (kind of the current situation we have with 9.4.12).

**Pull request merged**
