### PR TITLE
Issue #1485: Add systemd service file

### PR DESCRIPTION
**Pull request by gouessej**
Signed-off-by: Julien Gouesse <gouessej@orange.fr>

### CODE REVIEW

**Comment by gouessej** [comment]
Is there anything wrong with my pull request? It's already merged in the branch "master".

**Comment by joakime** [comment]
@gouessej which commit is it?
I'll cherry-pick it into `jetty-9.4.x` for you.

**Comment by gouessej** [comment]
@joakime This one: https://github.com/eclipse/jetty.project/commit/f107ec8c213cfe73bae067a8984367ac627224d1

**Comment by joakime** [comment]
> @joakime This one: [f107ec8](https://github.com/eclipse/jetty.project/commit/f107ec8c213cfe73bae067a8984367ac627224d1)

The commit that introduced the change is 65d714846173b05e8b9bdae07994501b8f3dff04

```
$ git branch --remote --contains 65d714846173b05e8b9bdae07994501b8f3dff04
  origin/jetty-10.0.x
  origin/jetty-10.0.x-1743-refactor-maven-plugin-redux
  origin/jetty-10.0.x-2429-httpclient_backpressure
  origin/jetty-10.0.x-2578-EventListener
  origin/jetty-10.0.x-2609-findexpiredsessions
  origin/jetty-10.0.x-3537-bootstrap_websocket_http2
  origin/jetty-10.0.x-3726-osgiAnnotationTest
  origin/jetty-10.0.x-3897-new_docs_2
  origin/jetty-10.0.x-3951-http2_demand
  origin/jetty-10.0.x-4228-demoKeystore
  origin/jetty-10.0.x-AutobahnTests
  origin/jetty-10.0.x-FragmentingFlusher
  origin/jetty-10.0.x-WebSocketClient_stopAtShutdown
  origin/jetty-10.0.x-websocket_compression
  origin/jetty-10.0.x_no_disabled_test
  origin/master
$ git tag --contains 65d714846173b05e8b9bdae07994501b8f3dff04
jetty-10.0.0-alpha0
jetty-10.0.0.alpha1
jetty-10.0.x-pre-restyling
```

I'll cherry-pick that to `jetty-9.4.x` now

**Comment by joakime** [comment]
Done.

**Comment by joakime** [comment]
See commit 9cede68b355515e1cf8802fd1fcf67aa7547aad1

**Comment by gouessej** [comment]
@joakime Thank you.

**Pull request closed without merging**
