### PR TITLE
Fix #482 The CCL while parsing the xml files should be set to a combination of Jetty and Bundle-Classloader

### LINKED ISSUE #482: [jetty-osgi] The CCL while parsing the xml files should be set to a combination of Jetty and Bundle-Classloader
When referncing custom Classes in the XML files these currently fails with CNF-Exception since the Context-Classloader is set to jetty-boot. It should fallback to the bundle of the cfg-files if any is given. I'll try to contribute a Pull-Request that shows a minimal work-around the next days.

### PR DESCRIPTION
**Pull request by laeubi**
For any reason this contains a commit for #480, please ignore this and just merge the commit for #482

### CODE REVIEW

**Comment by janbartel** [comment]
Before I can accept this patch I need to get Eclipse to approve the use of Pax Tinybundles for Jetty. I've begun the Eclipse CQ process for this, so its a matter of waiting until approved.

**Comment by laeubi** [comment]
Thanks! If this is an issue the test can be rewritten to use a separate maven-module-bundle-project as well of course.

**Comment by joakime** [comment]
Don't worry about altering the pull request.

The fact that the dependency is from `org.ops4j`, and that its used exclusively for testing will make the IP/CQ requirements at Eclipse Legal much lower/easier (than a new 3rd party dependency we release/ship with)

**Comment by laeubi** [comment]
It seems thsi was only applied to master, can this be merge to the 9.3.x and 9.4.x branches?

**Comment by joakime** [comment]
@laeubi backporting / cherry-picking can be done.

The PR itself was submitted for master, so that's how it was merged.

**Comment by laeubi** [comment]
Can you do that or is anything required from me to backport this? Must I open several PRs fro master and/or branches?

**Pull request merged**
