### PR TITLE
Enable "gcloud" profile for gcloud session testing.

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
We need to enable gcloud session testing on CI.

This would allow us to vet dependency updates for things like grpc (#5510)

**Comment by olamy** [comment]
looking at it. currently this fail because `com.google.cloud.datastore.testing.LocalDatastoreHelper` is starting some datastore using command line `gcloud` I'm trying a solution using a remote instance

**Comment by janbartel** [comment]
So the exceptions reported are IOExceptions, connection refused.

This is because the com.google.cloud.datastore.testing.LocalDatastoreHelper class calls this method on com.google.cloud.testing.BaseEmulatorHelper to find a free port to start the server process on:

>  protected static int findAvailablePort(int defaultPort) {
>     try (ServerSocket tempSocket = new ServerSocket(0)) {
>       return tempSocket.getLocalPort();
>     } catch (IOException e) {
>       return defaultPort;
>     }
>   }

This won't work, as we discovered in the jetty-maven-plugin integration tests. You can't ask ServerSocket to find you an available port and just use the _port number_, you have to use the _ServerSocket_ returned, otherwise the os may allocate that port to another user by the time you get around to trying to connect to it.

I've checked the latest available google code for the google-cloud-core jar (v 1.94.0) and this problem is still there.

Can you look into how we would dockerize this test instead, as that may avoid this problem.

**Comment by olamy** [comment]
closing in favour of #5651 5651

**Pull request closed without merging**
