### PR TITLE
Issue #12255 Dump CookieConfig

### LINKED ISSUE #12255: Environment CookieConfig details not visible in Server Dump or JMX
**Jetty version(s)**
12.0.13

**Enhancement Description**

The configured CookieConfig for an environment is not visible in dump or jmx.

When using `jetty.server.dumpAfterStart=true` to see the WebAppContext details for a Cookie Config, the output is simply ...

```
|        += oeje8w.WebAppContext@63eef88a{EE8 Demo Jetty WebApp,/ee8-test,file:///home/joakim/code/jetty/distros/bases/ee8-samesite-strict/webapps/ee8-demo-jetty/,true}{/home/joakim/code/jetty/distros/bases/ee8-samesite-strict/webapps/ee8-demo-jetty} - STARTED
|        |  +~ oeje8n.ContextHandler$CoreContextHandler@47dbb1e2{EE8 Demo Jetty WebApp,/ee8-test,b=file:///home/joakim/code/jetty/distros/bases/ee8-samesite-strict/webapps/ee8-demo-jetty/,a=AVAILABLE,h=GzipHandler@74cadd41{STARTED,min=2048,inflate=-1}} - STARTED
|        |  += oeje8n.SessionHandler@649725e3{STARTED} - STARTED
|        |  |  += oeje8n.SessionHandler$CoreSessionManager@3c0fae6c{STARTED} - STARTED
|        |  |  |  += org.eclipse.jetty.session.DefaultSessionCache@4c168660[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
|        |  |  |  |  += org.eclipse.jetty.session.NullSessionDataStore@52b56a3e[passivating=false,graceSec=3600] - STARTED
|        |  |  |  +~ oejs.DefaultSessionIdManager@3faf2e7d{STARTED}[worker=node0] - STARTED
|        |  |  |  +- ju.ImmutableCollections$ListN@1(size=0)
|        |  |  +- org.eclipse.jetty.ee8.nested.SessionHandler$CookieConfig@fd0e5b6
|        |  |  +- juc.CopyOnWriteArrayList@4eed470d(size=1)
```

Which shows no details about the configuration.
We should at least add a `CookieConfig.toString()` to make that entry useful.

The JMX level information for CookieConfig is also missing.

Screenshot from 2024-09-10 08-54-06

### PR DESCRIPTION
**Pull request by janbartel**
Closes #12255

Dump CookieConfig.

### CODE REVIEW

**Comment by joakime** [comment]
This works for the Server dump.

How about doing some extra work for the JMX level?
Since these objects derive from `ContainerLifeCycle`, they are already a `@ManagedObject`.
Lets cleanup the `@ManagedObject` description, and specify a few getter method for `@ManagedAttribute` too?

**Comment by janbartel** [comment]
@joakime  the `CookieConfig` classes aren't and haven't ever been visible in JMX. However, in past releases there have been `@ManagedAttribute` annotations on the `SessionHandler` methods that are equivalent to calling the `CookieConfig` methods. I can add those if you like.

**Comment by joakime** [comment]
> @joakime the `CookieConfig` classes aren't and haven't ever been visible in JMX. However, in past releases there have been `@ManagedAttribute` annotations on the `SessionHandler` methods that are equivalent to calling the `CookieConfig` methods. I can add those if you like.

See JMX:

Screenshot from 2024-09-10 08-54-06

Just as a note, ANY class derived from `ContainerLifeCycle` will show up on JMX.

**Comment by janbartel** [comment]
@joakime I'm attaching a screen cap of jmx mbeans with jetty-11. As you can see only the getters/setters on the `SessionHandler` are exposed. Note that the `CookieConfig` classes are not `ContainerLifeCycles` in any version of jetty, it's only the `SessionHandler` that is.
Screenshot from 2024-09-13 08-30-54

**Review by joakime — DISMISSED** [review]

**Review by joakime — APPROVED** [review]

**Pull request merged**
