### PR TITLE
Update realm.properties

### PR DESCRIPTION
**Pull request by crotwell**
package name for Password class in comments was wrong

### CODE REVIEW

**Comment by janbartel** [comment]
@crotwell  you'll need to sign the eclipse contributor's agreement before we are cleared to accept this patch. If you follow the "Details" link next to the ip-validation check failure it will tell you what to do.

If that's too much bother for a small change, I'm happy to make the change myself: your choice.

cheers
Jan

**Comment by crotwell** [comment]
I tried to get to the contributor agreement, but couldn't get past the
login, password reset not working for some reason. Maybe not worth the
effort for such a small change, if you are willing to just do it I am happy
with that.

thanks
Philip

**Comment by jmcc0nn3ll** [comment]
Sorry you are having issues with the Eclipse IP process, I would encourage you to sort out the agreement when you have the chance as it makes any future pull requests from you acceptable (at least from the eclipse IP perspective).  I will also forward your experience off to the powers that be at Eclipse.

**Comment by jmcc0nn3ll** [comment]
@crotwell FYI, Eclipse Webmasters said they had an issue over the weekend and to try again, if you still have issues ping (webmaster@eclipse.org) directly and they will work with you.

**Comment by crotwell** [comment]
Worked this time!

Thank you for following up on this.

Philip

**Pull request closed without merging**
