### PR TITLE
HttpClient: allow setting 'name'; improve default for subclasses

### PR DESCRIPTION
**Pull request by stevenschlansker**
I have multiple HttpClient instances in my application.  Right now they are identified by their hash code, but my application has a more informative name it could use.

### CODE REVIEW

**Comment by stevenschlansker** [comment]
I'm unclear as to why the signoff check is failing.  I added the signed-off-by line, and it matches the commit author:

```
commit 1d0fd3546205a42378e8c77a50f0a33722b9af8a
Author: Steven Schlansker <stevenschlansker@gmail.com>
Date:   Wed Oct 25 10:57:46 2017 -0700

    HttpClient: allow setting 'name'; improve default for subclasses
    
    Signed-off-by: Steven Schlansker <stevenschlansker@gmail.com>
```

**Comment by jmcc0nn3ll** [comment]
Your email address checks out as having an ECA on file too.

*kicks the bot to try again*

**Comment by jmcc0nn3ll** [comment]
You signed the commit with '-s' right?

**Comment by stevenschlansker** [comment]
Yes, that's how the `Signed-off-by` line got added.  I did have to correct it a couple of times with `--amend` but I'm not sure if that's relevant...

**Comment by jmcc0nn3ll** [comment]
Found it, your commit is signed by the wrong address.

Author:     Steven Schlansker <stevenschlansker@gmail.com>
AuthorDate: Wed Oct 25 10:57:46 2017 -0700
Commit:     Steven Schlansker <sschlansker@opentable.com>
CommitDate: Wed Oct 25 11:03:36 2017 -0700

**Comment by stevenschlansker** [comment]
Yikes, that was confusing.  Apparently specifying `--author=` is insufficient, you must additionally `-c user.email=`.  Thanks git :)

**Comment by jmcc0nn3ll** [comment]
you can validate it with

> git log -1 --format=fuller

**Comment by stevenschlansker** [comment]
Side question, I am running 9.4.7 right now, and I'm going to have a number of minor improvements coming down the line.  Is it better to target `master` or `jetty-9.4.x` branch, given that my goal is ideally that it could make it in the next Jetty release?  I assumed `9.4.x` but maybe that's not correct.

**Comment by jmcc0nn3ll** [comment]
9.4.x is the best place to go then, master is jetty 10 which will be servlet 4.0 features which we are still kicking around the first beta release on, if you want to see the changes showing up in new releases then you are in the right place with 9.4.x, everything gets merged up

**Comment by sbordet** [comment]
@stevenschlansker, the "name" is not needed as you can name the `QueuedThreadPool` and pass it to `HttpClient`:

```java
QueuedThreadPool executor = new QueuedThreadPool();
executor.setName("client");
HttpClient client = new HttpClient();
client.setExecutor(executor);
client.start();
```

It's a bit longer to write but not that much.
Also, the `HttpClient.name` property you would like to introduce would only be applied to the internally created `QueuedThreadPool`, and would confuse people that explicitly set an `Executor` on `HttpClient`, even if it's a `QueuedThreadPool`.

I'm inclined to close this PR, sorry.

Thanks for you contribution though, and keep them coming.

**Comment by stevenschlansker** [comment]
Well, my intent is to take the Jetty default, but have sensible names.  I don't want to override Jetty's choice of default -- if later QTP is replaced with BetterQTP, I'd then be behind the times.  All I wanted to do was change the name :/

**Comment by stevenschlansker** [comment]
Would factoring out the construction into `protected` helper methods be more palatable?  e.g. `HttpClient.doStart` now has `executor = createExecutor()`.  Then I could override it like:

```java
@Override
protected Executor createExecutor() {
    return super.createExecutor().setName(myName);
}
```

**Comment by sbordet** [comment]
Nope. `Executor` does not have a `setName()` method.

**Comment by sbordet** [comment]
@stevenschlansker I changed my mind on the subject, you were right.

While it is possible to name `QueuedThreadPool` it is also true that a single `QueuedThreadPool` may be shared among many `HttpClient` instances so we're back at needing a name for `HttpClient`.

Can you please have a look at #2020 and possibly provide a PR that satisfies #2020 requirements ?
Thanks !

**Pull request closed without merging**
