### PR TITLE
Fix #7518 Trie.getBest with empty Key

### LINKED ISSUE #7518: ArrayTrie getBest fails to match the empty string entry in certain cases
**Jetty version(s)**
9.4.x

**Description**

When an `ArrayTrie` contains an empty string, `getBest()` should always match it as a last resort. But when `getBest()` is given a key that starts with common letters but does not match an existing entry then `null` is returned instead of the empty string's value.

Consider the following:

```java
ArrayTrie<Integer> trie = new ArrayTrie<>();

assertTrue(trie.put("", 0));
assertTrue(trie.put("prefix", 1));

assertEquals(0, trie.getBest("unknown"));
assertEquals(0, trie.getBest("pre-unknown")); // fails
```

### PR DESCRIPTION
**Pull request by gregw**
Fixes #7518 
Only increment current row if not recursing.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Review by lorban — CHANGES_REQUESTED** [review]
As for #7528 `HttpParserTest` got broken.

**Comment by gregw** [comment]
@lorban Added extra test. The problem was a bug with the return if the first non matching character was a big index one.

**Comment by gregw** [comment]
@lorban Added extra test. The problem was a bug with the return if the first non matching character was a big index one.

**Review by lorban — APPROVED** [review]
It looks like #7528 duplicates these changes, otherwise LGTM.

**Pull request merged**
