### PR TITLE
Remove long dead jetty-overlay-deployer module

### PR DESCRIPTION
**Pull request by joakime**

### CODE REVIEW

**Review by gregw — CHANGES_REQUESTED** [review]
There is a commented out line in the top level pom.xml that needs to be removed as well.

**Comment by janbartel** [comment]
Shouldn't this be removed in jetty-10.0.x instead of jetty-9.4?

**Comment by gregw** [comment]
@janbartel It has not been included in the build in 9 for a long time.  It's safe to remove.

**Review by gregw — CHANGES_REQUESTED** [review]
```
[418] find jetty-documentation -type f | xargs egrep -i overlay-d
jetty-documentation/src/main/asciidoc/configuring/deploying/chapter.adoc://include::overlay-deployer.adoc[]
jetty-documentation/src/main/asciidoc/configuring/deploying/overlay-deployer.adoc:[[overlay-deployer]]
```

**Comment by joakime** [comment]
> ```
> [418] find jetty-documentation -type f | xargs egrep -i overlay-d
> jetty-documentation/src/main/asciidoc/configuring/deploying/chapter.adoc://include::overlay-deployer.adoc[]
> jetty-documentation/src/main/asciidoc/configuring/deploying/overlay-deployer.adoc:[[overlay-deployer]]
> ```

Good catch.

One little tip, `git grep` is a cool thing to learn, it will perform a git across all committed content in the tree.
It's like `git` but it also does recursive natively, and will not return hits from generated code (like from `/target/` directories)

Example:

``` shell
$ git grep overlay-deployer
jetty-documentation/src/main/asciidoc/configuring/deploying/chapter.adoc://include::overlay-deployer.adoc[]
jetty-documentation/src/main/asciidoc/configuring/deploying/overlay-deployer.adoc:[[overlay-deployer]]
jetty-overlay-deployer/pom.xml:  <artifactId>jetty-overlay-deployer</artifactId>
jetty-overlay-deployer/src/main/config/modules/overlay.mod:lib/jetty-overlay-deployer-${jetty.version}.jar
pom.xml:    <!-- <module>jetty-overlay-deployer</module> -->
```

**Review by olamy — APPROVED** [review]

**Review by gregw — APPROVED** [review]

**Pull request merged**
