### PR TITLE
 Unit tests for Jetty-Jmx module to increase code coverage from 60% to 85%

### PR DESCRIPTION
**Pull request by charuvijay**
This pull request is focused on module Jetty-Jmx. Code coverage is measured using Cobertura. This pull request increases code coverage of the whole project by 25%.

Metric                |Before     |After
--------------------|------------|--------
Coverage%       |60%        |85%
Lines Covered  |308         |433
Total Lines       |505         |505

Please let me know if you have any questions. 

Vijay
DevFactory - Code Quality Team

### CODE REVIEW

**Comment by gregw** [comment]
thanks...  but while we look into getting IP clearance for powermock, could you update the PR to follow the jetty coding standards: https://www.eclipse.org/jetty/documentation/current/coding-standards.html

**Comment by gregw** [comment]
reformatted and merged in commits dd4a9f97 and 22d4eee6f

**Comment by gregw** [comment]
https://github.com/eclipse/jetty.project/commit/93a8d8e05f4120e57bc3c830d5c10e38dd4a9f97
https://github.com/eclipse/jetty.project/commit/fc2859dd33e363707736b3382004ec422d4eee6f

**Comment by joakime** [comment]
This pull request breaks the build.  (no license headers)

**Comment by gregw** [comment]
@joakime it had license headers, but 2015! Second commit above is the happy new year one!

**Pull request closed without merging**
