### PR TITLE
Access to cookie config with accessor method

### PR DESCRIPTION
**Pull request by dejpec**
With this minimal change one can provide different cookie configs for the same SessionHandler
without coping the whole method into the inherited class.

Signed-off-by: Dejan Pecar <dejan.pecar@abacus.ch>

### CODE REVIEW

**Review by gregw — APPROVED** [review]
ummmmmm not exactly sure what you say you want this for is a good idea..... but hey people use jetty in all sorts of weird and wonderful ways.

This change is harmless enough and probably makes the code more robust for a number of different weird things that could be done to `_cookieConfig`, so LGTM.  

@janbartel what do you think?

**Comment by joakime** [comment]
How would this be used?

Would you override `getSessionCookieConfig()` and produce something different?

**Comment by dejpec** [comment]
exactly. i want to have 2 different cookie configs and decide dynamically which one is used in
a derivation of SessionHandler.
it already works in my derivation but i had (like i mentioned) to copy the whole getSessionCookie method
with exactly that change in it which is not good for maintainablility.

**Comment by joakime** [comment]
@janbartel bump, can you review this?

**Comment by janbartel** [comment]
LGTM, but @dejpec can you fix the conflict in your branch so it will apply cleanly?

**Review by janbartel — CHANGES_REQUESTED** [review]
Seems fine, but please resolve the conflict in SessionHandler in your branch so we can apply it cleanly.

**Review by janbartel — APPROVED** [review]
LGTM

**Pull request merged**
