### PR TITLE
Better handling of Objects in JMX MetaData

### LINKED ISSUE #10477: Jetty 12: Review MBeans for Handlers
**Jetty version(s)**
12

**Description**
The `Handler` class structure in Jetty 12 has changed, but the associated `MBean` classes have been left behind, so they must be reviewed.

### PR DESCRIPTION
**Pull request by gregw**

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet This approach works for most of the failing attributes.   Only Maps and/or Attributes are not working.... I had a try, but ran out of time to make it work.  Feel free to take over

**Comment by gregw** [comment]
@sbordet I couldn't get CompositeData to work, so for now I'm sending Attributes as Map<String,String>

**Review by sbordet — APPROVED** [review]
@gregw I added test cases, now good coverage for the MetaData class and the changes you made.
LGTM.

**Comment by gregw** [comment]
The CI failures are unrelated.  I am merging.

**Pull request merged**
