### PR TITLE
Issue #4548 - clean up websocket removing duplicated and unused classes

### LINKED ISSUE #4538: review WebSocket MessageWriter and MessageReader
**Jetty version**
10.0.x

**Description**
`MessageWriter` and `MessageOutputStream` look inefficient and are duplicated in both the jetty API and javax API implementations.

### LINKED ISSUE #4548: duplicated classes between jetty and javax websocket implementations
**Jetty version**
10.0.x

**Description**
The jetty and javax websocket implementation modules, specifically `websocket-jetty-common` and `websocket-javax-common` have many duplicated classes. By introducing a common module such as `websocket-common` or `websocket-util`, this duplication could be eliminated and this would make the code easier to update and maintain in the future.

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Closes #4548**
- Create new module `websocket-util` which contains implementation classes shared by `websocket-jetty` and `websocket-javax`.
- Many of these classes had to be changed as the javax and jetty versions of them differed slightly.

Other general cleanups, removed unused interfaces and classes, etc..

### CODE REVIEW

**Comment by joakime** [comment]
Quite the mess you have here. :-)

The InvokerUtils has 2 versions.

The javax version is the most complete and should be the one we settle on for websocket-core (or even jetty-util)
The ReflectUtil could probably be in jetty-util as well.

**Review by joakime — DISMISSED** [review]
The `MessageWriter` should not use `OutputStreamWriter`, as the contract for `OutputStreamWriter` violates the rules of RFC6455 (we MUST validate outgoing UTF-8 and fail the connection if in violation.  `OutputStreamWriter` will use replacement characters, which is not allowed)

**Comment by lachlan-roberts** [comment]
@joakime good catch, I see that this is a problem but it would also be good to not duplicate the implementations, and we probably want to use the `ByteBufferPool` instead of allocating `CharBuffers`.

I see that this is also going to be a problem with our `MessageReader` which I have not changed. It implements `InputStreamReader` and so will have the same problem with the replacement characters.

I might leave out the changes to `MessageWriter`, and put a separate issue up (#4538). I'm having enough trouble getting this PR working as is.

**Comment by lachlan-roberts** [comment]
I had to change `InvokerUtils` so that it gets passed in the `MethodHandles.Lookup`, this makes it have the same access permissions as the calling module and we don't get lots of IllegalAccessExceptions.

**Comment by lachlan-roberts** [comment]
Can I get some reviews on this soon. Any other work in jetty-10 websocket would likely cause lots of merge conflicts as there are so many files changed here.

I also have some further changes based off this branch to fix issues #4538 and #4571. So I can put PRs up for those once this has been merged.

**Review by olamy — APPROVED** [review]

**Review by gregw — APPROVED** [review]
There are aspects of these classes I don't like.... but in general the move to util is good!

**Comment by joakime** [comment]
> There are aspects of these classes I don't like.... but in general the move to util is good!

Please file issues about what you don't like.

**Pull request merged**
