### PR TITLE
using memcached docker to run memcached session remote tests

### PR DESCRIPTION
**Pull request by olamy**
@janbartel tests are  limited to one. Do you think about some test suite we could add? or we are fine with the current coverage?

### CODE REVIEW

**Comment by janbartel** [comment]
As memcache is just used as a cache, I figure we're good if we just test the standard create, load, update and delete ops. Looking the test, I don't think we test delete, maybe that could be added. Do you want me to do that or will you do it?

**Comment by olamy** [comment]
As you want.
Feel free to do it if you have time

**Comment by olamy** [comment]
@janbartel not sure if we have something blocking that?

**Comment by janbartel** [comment]
@olamy sorry, completely forgot to do it: I've added the deletion test now.

**Pull request merged**
