### PR TITLE
save jetty-home artifacts in case of label save-home

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by sbordet** [comment]
@olamy can you detail why this is necessary?

**Comment by joakime** [comment]
In theory, this would allow Jenkins to store the artifacts for a specific build + job for other people to use.

Eg: you could be working on a PR, and each green build of that PR has the associated jetty-home artifacts available on Jenkins for download.

**Comment by olamy** [comment]
> In theory, this would allow Jenkins to store the artifacts for a specific build + job for other people to use.
> 
> Eg: you could be working on a PR, and each green build of that PR has the associated jetty-home artifacts available on Jenkins for download.

not only in theory but this will do it :) if you add the label `save-home` to your PR

**Comment by gregw** [comment]
@olamy so why don't I see jetty-home in the artifacts of the build of this?   Is that because it is built with the setup before this is merged?

**Comment by olamy** [comment]
@gregw ditto good point. they are for build `#1` https://jenkins.webtide.net/job/jetty.project/view/change-requests/job/PR-10931/1/
but not second build because of the cache. I need to find a solution for this.

**Review by gregw — CHANGES_REQUESTED** [review]
How about have the `save-home` label also force the no-cache option as well?

**Comment by olamy** [comment]
> How about have the `save-home` label also force the no-cache option as well?

@gregw yes that's the ezy fix. But this mean we will have 1h15 build as using the cache could be only 10 minutes build before having the artifacts ready. 
I'll try something first.

**Comment by olamy** [comment]
@gregw fixed now

**Review by gregw — APPROVED** [review]

**Pull request merged**
