### PR TITLE
Improve executorSizedThreadPool

### PR DESCRIPTION
**Pull request by gregw**
Improved executorSizedThreadPool to see if better than QueuedThreadPool in benchmarks for #1803 

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet needs some work!

**Comment by sbordet** [comment]
@gregw I have improved the implementation, which I think is now on par with `QueuedThreadPool` feature-wise.

**Comment by gregw** [comment]
Looks good!

However, the name still sucks!  How about just `ExecutorThreadPool`?   We would need to keep the `Sized` name as a deprecated extension.
I'm investigating a JMH comparison between the pools, but lets also see if they make a macro difference in the main benchmarks

**Comment by gregw** [comment]
We also need to test if a BlockedArrayQueue would be better than a LinkedBlockingQueue

**Comment by gregw** [comment]
I added a JMH executor test based on an example I found:
```
# Run complete. Total time: 00:03:26

Benchmark                     (size)  (tasks)  (type)   Mode  Cnt      Score       Error  Units
ThreadPoolBenchmark.testPool     200       50     QTP  thrpt    3  59781.160 ± 50520.444  ops/s
ThreadPoolBenchmark.testPool     200       50     ETP  thrpt    3  49824.764 ± 34097.516  ops/s
ThreadPoolBenchmark.testPool    2000       50     QTP  thrpt    3  52758.317 ± 65843.204  ops/s
ThreadPoolBenchmark.testPool    2000       50     ETP  thrpt    3  46001.731 ± 29267.341  ops/s
```

This shows that QTP is still better..... however, I'm dubious this is a good/fair test, but a starting point...

**Pull request merged**
