### PR TITLE
Create .lgtm.yml to support building with LGTM.com

### PR DESCRIPTION
**Pull request by JLLeitschuh**

### CODE REVIEW

**Comment by WalkerWatch** [comment]
@JLLeitschuh Please make sure you sign an Eclipse Contributor Agreement, which you can[ find here.](https://accounts.eclipse.org/user/eca)

**Comment by JLLeitschuh** [comment]
I think we're good now.

**Review by joakime — APPROVED** [review]
:+1: LGTM (hah!)

**Comment by jmcc0nn3ll** [comment]
Does this mess anything up at lgtm when it gets merged to 11?

**Comment by joakime** [comment]
it shouldn't.  looks like the lgtm website just uses the default branch.

**Pull request merged**
