### PR TITLE
Jetty 10.0.x doc reformat

### PR DESCRIPTION
**Pull request by WalkerWatch**
First pass of the doc reformat for Jetty 10. 

Items of note:

- Docbook has been removed - docs render straight to html from asciidoctor

- Images still need fixed
1. Includes in-chapter images as well as TOC/header images

- Content will likely need re-shuffled/pulled apart

### CODE REVIEW

**Comment by jmcc0nn3ll** [comment]
Note: this is purely a rejiggering of the content, the look and feel of the produced content is still up in the air and is closely related to the update of the Jetty website and a mess of redirects that are intended to clean up interactions with the overall Jetty website

**Comment by sbordet** [comment]
@jmcc0nn3ll @WalkerWatch this PR fails on Eclipse IP, conflicts, etc.
Can you please drop it and issue another one that is correct?

**Comment by jmcc0nn3ll** [comment]
I have the new look and feel artifacts in place and will wire up this PR
with that in place as well.

--
jesse mcconnell
jesse.mcconnell@gmail.com

**Comment by jmcc0nn3ll** [comment]
closing so @WalkerWatch can get it made with proper signoff

**Pull request merged**
