### PR TITLE
Jetty 12 add duplicate classes finder plugin to avoid sames classes with different content coming from different jars

### PR DESCRIPTION
**Pull request by olamy**
Using this plugin https://basepom.github.io/duplicate-finder-maven-plugin/

### CODE REVIEW

**Comment by joakime** [comment]
@olamy what release of Jetty 12 do you want to see this in? (update your Project assignment)

**Comment by olamy** [comment]
@joakime nothing really urgent so moved it to 12.0.4

**Comment by janbartel** [comment]
Is there a way to define in the top level pom the dependency for `testcontainers`, _always_ excluding `hamcrest` so we don't have to do it in each and every pom?

**Comment by olamy** [comment]
> Is there a way to define in the top level pom the dependency for `testcontainers`, _always_ excluding `hamcrest` so we don't have to do it in each and every pom?

not really as we are managing using testcontainers via the bom and we can't really exclude via the bom declaration in top level dptMngt. I will try  something but not sure it will work

**Comment by olamy** [comment]
@janbartel found a way

**Review by janbartel — APPROVED** [review]
Nice.

**Pull request merged**
