### PR TITLE
Added nullchecks and test for getters using _metadata to avoid throwing

### PR DESCRIPTION
**Pull request by pethers**
nullpointer exception.

Follow up on https://github.com/eclipse/jetty.project/pull/69

Signed CLA now as well.

### CODE REVIEW

**Comment by joakime** [comment]
These null-checks seem curious, the Request object shouldn't ever be null in a scenario where those methods would be used.

Perhaps these NPE's are a side effect of your AsyncContext handling got awry?

**Comment by pethers** [comment]
Probably caused by bug in Atmosphere, will follow it up by raising an issue there.

**Comment by janbartel** [comment]
@pethers  the ip-validation check on the commit seems to have failed. Can you check that you signed the commit with the correct email address? See the failed ip-validation check for details.  As soon as that's fixed, I'm happy to commit the patch.

**Comment by pethers** [comment]
Will try to fix the ip-validation later tonight. Not sure if I can update the current pull request or if I have to create a new one.

**Comment by jmcc0nn3ll** [comment]
Just push again and it should try the validation once more, you get a little green checkbox after commit line and we are cleared to merge it.

**Pull request merged**
