### PR TITLE
Issue #2886 Handle SNI with non SNI certificates

### LINKED ISSUE #2886: SNI matching does not work in certain cases when there is only one CN certificate in the keystore
Jetty version 9.4.12.

Conditions:
* keystore contains two certificates: one CN certificate with subjectAltNames configured and alias "cert1", and one certificate without CN, with alias "default".
* SslContextFactory configured with certAlias set to "default", so it will fallback if SNI matching fails.

Expected behaviour:
SNI matching works and "cert1" is selected correctly when connecting to it's host name.

Observed behaviour:
"default" certificate is always selected unless a second CN certificate is added to the keystore.

I think this is related to commit 8660055574026ed963f4f5b7aa2e8a16ad292f50.

### PR DESCRIPTION
**Pull request by gregw**
Fix #2886 by modifying the #2010 fix so that a single SNI host will still trigger SNI if there are other certificates.
 
Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by gregw** [comment]
@sbordet @joakime This looks a little bit wrong... I need brains trust!

**Comment by sbordet** [comment]
@gregw hold this until we have more information about #2886.
While I think the changes in this PR may be ok, they may not fix #2886.

**Comment by gregw** [comment]
@joakime can your re-review

**Comment by gregw** [comment]
@sbordet @joakime The build broke because of 2 unrelated flaky tests.
Am I good to merge?

**Pull request merged**
