### PR TITLE
Issue #2040 return error code 431 when http2 request header too large

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by sbordet** [comment]
@ellisjoe you have to comply with the [contribution guidelines](https://www.eclipse.org/jetty/documentation/current/contributing-patches.html).

Also, I'm not sure the patch is good... you are not returning a 413 response to the client which seems to be your original intent.

**Comment by ellisjoe** [comment]
Hey @sbordet. I've signed the ECA and am wondering what else needs to be done to send the response code to the client besides passing it to `onConnectionFailure`?

**Comment by sbordet** [comment]
`onConnectionFailure()` does not send a HTTP response.
It closes the connection with a `GOAWAY` frame with the error code you passed in, which I don't think it's what you want.

**Comment by ellisjoe** [comment]
Based on https://http2.github.io/http2-spec/#StreamErrorHandler it looks like we should be sending a `RST_STREAM` frame instead. Will update the PR.

**Comment by ellisjoe** [comment]
that doesn't seem quite right either given the valid error codes here: https://tools.ietf.org/html/rfc7540#section-7

**Comment by ellisjoe** [comment]
@sbordet any suggestions on where the right place to wire this through is? As far as I can tell this should be done by sending a legitimate response with a 431 status code and there isn't a nice way to do that from the http2 protocol layer that exists in jetty today.

**Comment by sbordet** [comment]
@ellisjoe let's close this PR and continue discussion on #2040.

**Pull request closed without merging**
