### PR TITLE
Issue #4047 Graceful Cleanup

### PR DESCRIPTION
**Pull request by gregw**
Initially created to just address #4047, this PR has now started addressing other graceful shutdown issues (in preparation for HTTP/2 graceful).   See also #4100 for the core fix

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by gregw** [comment]
I've taken this out of 9.4.22... I'm not even sure it should be in 9.4.x

**Comment by gregw** [comment]
I'm going to rebase this on jetty-10

**Comment by alefab** [comment]
> I've taken this out of 9.4.22... I'm not even sure it should be in 9.4.x

I was searching a way to wait for requests to be handled during shutdown and I find this ticket.
Is there any issue for this ticket not being fixed in the 9.4.x branches ?

**Comment by gregw** [comment]
@alefab There is graceful shutdown support in both 9 and 10.  This issue is about cleaning up the implementation.

If you install the stats handler and set the stopTimeout then you'll get graceful shutdown behaviour.

**Comment by alefab** [comment]
@gregw Thanks ! After adding a stats handler, the graceful shutdown is working like a charm (9.4.31) :)

**Comment by gregw** [comment]
I know that is kind of counter intuitive..... but counting request can be expensive and cause contention.  So if we have to do it, we only want to do it once, hence we make it optional in the stats handler and then hang graceful shutdown off that.

@sbordet in Jetty-10 I guess we could add a `graceful-shutdown.mod` that depends on the `stats.mod` ?

**Pull request closed without merging**
