### PR TITLE
Issue #11047 Update EE8 to Apache Jasper 9.0.83.1

### LINKED ISSUE #11047: Update jetty-12 ee8 to apache jasper 9.0.83

### PR DESCRIPTION
**Pull request by janbartel**
Closes #11047

### CODE REVIEW

**Comment by joakime** [comment]
@olamy there's a duplicate class checker that's preventing this PR from proceeding.

This particular set of duplicates have been present since 12.0.0 release.

```
[WARNING] Found duplicate and different resources in [org.eclipse.jetty.toolchain:jetty-schemas:5.2, org.eclipse.jetty.toolchain:jetty-servlet-api:4.0.6]:
[WARNING]   javax/servlet/resources/j2ee_1_4.xsd
[WARNING]   javax/servlet/resources/j2ee_web_services_1_1.xsd
[WARNING]   javax/servlet/resources/j2ee_web_services_client_1_1.xsd
[WARNING]   javax/servlet/resources/javaee_5.xsd
[WARNING]   javax/servlet/resources/javaee_6.xsd
[WARNING]   javax/servlet/resources/javaee_7.xsd
[WARNING]   javax/servlet/resources/javaee_8.xsd
[WARNING]   javax/servlet/resources/javaee_web_services_1_2.xsd
[WARNING]   javax/servlet/resources/javaee_web_services_1_3.xsd
[WARNING]   javax/servlet/resources/javaee_web_services_1_4.xsd
[WARNING]   javax/servlet/resources/javaee_web_services_client_1_2.xsd
[WARNING]   javax/servlet/resources/javaee_web_services_client_1_3.xsd
[WARNING]   javax/servlet/resources/javaee_web_services_client_1_4.xsd
[WARNING]   javax/servlet/resources/permissions_7.xsd
[WARNING]   javax/servlet/resources/web-app_2_2.dtd
[WARNING]   javax/servlet/resources/web-app_2_3.dtd
[WARNING]   javax/servlet/resources/web-app_2_4.xsd
[WARNING]   javax/servlet/resources/web-app_2_5.xsd
[WARNING]   javax/servlet/resources/web-app_3_0.xsd
[WARNING]   javax/servlet/resources/web-app_3_1.xsd
[WARNING]   javax/servlet/resources/web-app_4_0.xsd
[WARNING]   javax/servlet/resources/web-common_3_0.xsd
[WARNING]   javax/servlet/resources/web-common_3_1.xsd
[WARNING]   javax/servlet/resources/web-common_4_0.xsd
[WARNING]   javax/servlet/resources/web-fragment_3_0.xsd
[WARNING]   javax/servlet/resources/web-fragment_3_1.xsd
[WARNING]   javax/servlet/resources/web-fragment_4_0.xsd

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:47 min
[INFO] Finished at: 2023-12-13T05:45:20Z
[INFO] ------------------------------------------------------------------------
[INFO] Saving cache report on build completion
[INFO] Saved to remote cache http://nginx-cache-service.jenkins.svc.cluster.local:80/v1/org.eclipse.jetty/jetty-project/796de4cd-f318-46fe-a00a-2f8089b25b9b/build-cache-report.xml
[ERROR] Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:2.0.0:check (default) on project jetty-ee8-apache-jsp: Found duplicate classes/resources! -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.basepom.maven:duplicate-finder-maven-plugin:2.0.0:check (default) on project jetty-ee8-apache-jsp: Found duplicate classes/resources!
```

**Comment by janbartel** [comment]
@joakime why doesn't head of jetty-12.0.x fail on ci then?

**Comment by joakime** [comment]
> @joakime why doesn't head of jetty-12.0.x fail on ci then?

Build cache?

**Comment by joakime** [comment]
~@janbartel the older jar has those XSDs too.~

```
$ jar -tvf apache-jsp-9.0.52.jar | grep xsd
 14643 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/jsp_2_3.xsd
 28257 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/web-jsptaglibrary_2_0.xsd
 13269 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/jsp_2_2.xsd
 32876 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/web-jsptaglibrary_2_1.xsd
 11484 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/jsp_2_1.xsd
 10253 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/jsp_2_0.xsd
 17109 Tue Nov 20 17:36:18 CST 2018 javax/servlet/jsp/resources/jspxml_2_0.xsd

$ jar -tvf apache-jsp-9.0.83.jar | grep xsd
 11828 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/jsp_2_2.xsd
 26845 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/web-jsptaglibrary_2_0.xsd
 13107 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/jsp_3_0.xsd
  8812 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/jsp_2_0.xsd
 37182 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/web-jsptaglibrary_3_0.xsd
 31466 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/web-jsptaglibrary_2_1.xsd
 10043 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/jsp_2_1.xsd
 13161 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/jsp_2_3.xsd
 17109 Tue Sep 01 11:51:56 CDT 2020 javax/servlet/jsp/resources/jspxml_2_0.xsd
```

Never mind, the reported error is between servlet 4 and schemas

**Comment by olamy** [comment]
> > @joakime why doesn't head of jetty-12.0.x fail on ci then?
> 
> Build cache?

not sure because it was the first build.

anyway jetty-schemas have been upgraded https://github.com/jetty-project/jasper-jsp/compare/jasper-jsp-9.0.52...jasper-jsp-9.0.83#diff-4e45a214df17f0b8019ede7ef117da3d09904bbdc9cc002ed080617b526ee7b7L328

culprit:
https://github.com/jetty-project/jasper-jsp/commit/3e425742a96025c232c28f530982a62d0015e4cb

so there are changes. and same xsd file have different sizes.

**Comment by janbartel** [comment]
@olamy I can't see how the `apache-jsp` artifact is involved in this. If you list it's contents, the only `servlet` resources you see is:

>      0 Tue Sep 01 11:51:56 AEST 2020 javax/
>      0 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/
>      0 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/
>      0 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/
>  12188 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_1_2.dtd
>  11828 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_2.xsd
>  26845 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_2_0.xsd
>  13107 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_3_0.xsd
>   8812 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_0.xsd
>  37182 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_3_0.xsd
>  31466 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_2_1.xsd
>   5559 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_1_1.dtd
>  10043 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_1.xsd
>  13161 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_3.xsd
>  17109 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jspxml_2_0.xsd
>   5622 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jspxml_2_0.dtd

These have _always_ been released as part of the `apache-jsp` jar, that's not new.  If you look at the original reported duplicates, none of these resources are involved.

**Comment by olamy** [comment]
> @olamy I can't see how the `apache-jsp` artifact is involved in this. If you list it's contents, the only `servlet` resources you see is:
> 
> > ```
> >  0 Tue Sep 01 11:51:56 AEST 2020 javax/
> >  0 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/
> >  0 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/
> >  0 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 12188 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_1_2.dtd
> > 11828 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_2.xsd
> > 26845 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_2_0.xsd
> > 13107 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_3_0.xsd
> > 8812 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_0.xsd
> > 37182 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_3_0.xsd
> > 31466 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_2_1.xsud
> > 5559 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/web-jsptaglibrary_1_1.dtd
> > 10043 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_1.xsd
> > 13161 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jsp_2_3.xsd
> > 17109 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jspxml_2_0.xsd
> > 5622 Tue Sep 01 11:51:56 AEST 2020 javax/servlet/jsp/resources/jspxml_2_0.dtd
> 
> These have _always_ been released as part of the `apache-jsp` jar, that's not new. If you look at the original reported duplicates, none of these resources are involved.

because `jetty-schemas` is a dependency of apache-jsp and declared so in the pom so it's available in the classpath.
if it's not correct the scope of jetty-schemas must be changed in apache-jsp project

**Review by olamy — APPROVED** [review]

**Pull request merged**
