### PR TITLE
Fixes #10347 - Ensure documentation snippets for XML don't have their doctype hot-linked

### LINKED ISSUE #10347: [source,xml] documentatation issue
**Jetty version(s)**
Jetty 10, 11, 12

**Description**

The documentation uses a lot of [source] tags, and the ones that render XML occasionally generate a clickable link to a URL that is 404 on the eclipse jetty website—specifically the DOCTYPE section.

```
[source,xml]
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
```
This is fine.

However, with `[source,xml,subs=normal]`, the doctype link renders a clickable link to `https://eclipse.dev/jetty/configure_10_0.dtd%22%3E`.

I am opening this issue to see if there was any reason we had the source section declared like this. I can't find one and I suspect it is a long holdover to a previous way of doing things, or just a cut and paste and issue.

@sbordet, any reason we shouldn't just remove these?

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
Generate correct xml doctype statements in documentation.

### CODE REVIEW

**Review by joakime — APPROVED** [review]
Straight forward enough.

**Review by sbordet — CHANGES_REQUESTED** [review]
Sorry, but no, removing `subs=normal` does not work because it will also remove callouts, highlights and other visual cues that have been explicitly added for clarity.
See https://docs.asciidoctor.org/asciidoc/latest/subs/ and https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/

**Comment by joakime** [comment]
Your commit says "Fixes #10107", which is an totally unrelated Issue.

**Comment by jmcc0nn3ll** [comment]
> Your commit says "Fixes #10107", which is an totally unrelated Issue.

o.O IntelliJ autofilled that and I completely missed it.  I'll fix it, push a new PR, and just merge it.

**Comment by joakime** [comment]
> Sorry, but no, removing `subs=normal` does not work because it will also remove callouts, highlights and other visual cues that have been explicitly added for clarity.
> See https://docs.asciidoctor.org/asciidoc/latest/subs/ and https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/

Huh?  `subs=normal` does not include `callouts`, says so in the asciidoc documentation.

How can we have the URL present in the DOCTYPE not hotlink, but allow the rest of the substitutions to occur?

**Comment by jmcc0nn3ll** [comment]
Okay, I may be treating a symptom and not the problem. However, if that `subs=` is present in the XML source statement, a bogus URL is generated from that DOCTYPE. Perhaps it is a bug in the tooling.

I was made aware of this by looking at the Google Analytics and 404 calls being generated to `https://eclipse.dev/jetty/configure_10_0.dtd">`

**Comment by sbordet** [comment]
@jmcc0nn3ll it is an issue, just need to find the right asciidoctor incantation.

**Comment by jmcc0nn3ll** [comment]
closing this out, will have to noodle out something else

**Pull request closed without merging**
