### PR TITLE
fix possible empty coverage report and avoid storing too many data non needed

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Review by joakime — DISMISSED** [review]

**Comment by olamy** [comment]
holding up this a bit as I'd like to test with jdk21 as well

**Comment by joakime** [comment]
@olamy are you done testing this with jdk21 yet?

**Comment by olamy** [comment]
Not exactly. I figured out jacoco doesn't produce same output for 17 and 21 :( 
We can still merge that though as it's another problem

**Comment by joakime** [comment]
This seems out of date

**Pull request closed without merging**
