### PR TITLE
Happy New Year 2023!

### PR DESCRIPTION
**Pull request by joakime**
The standard start of year bump of year in license headers.

### CODE REVIEW

**Comment by sbordet** [comment]
@joakime @jmcc0nn3ll @gregw would it be possible to avoid specifying the last year, so we do it this last time and never again?

**Comment by joakime** [comment]
Sure, lets drop the years entirely from the copyright header ...

From ...

```
Copyright (c) 1995-2022 Mort Bay Consulting Pty Ltd and others.
```

to ...

```
Copyright (c) Mort Bay Consulting Pty Ltd and others.
```

**Comment by joakime** [comment]
Seems that Eclipse wants the year though.

https://www.eclipse.org/legal/cpl2epl/cpl_copyrightandlicensenotice.php  (note the header that says this document is deprecated)

I'll see if there's a newer up to date version.

**Comment by joakime** [comment]
Other Eclipse documents (that seem more up to date)

https://www.eclipse.org/legal/legalfaq.php#h.x0s5sxj1z2cp

> ## [Do I have to place copyright notices in all my code?](https://www.eclipse.org/legal/legalfaq.php#h.x0s5sxj1z2cp)
> Yes. Where possible, copyright notices must be included the [file headers](https://www.eclipse.org/projects/handbook/#ip-copyright-headers) for all project content. This includes source files and, where possible, configuration. A best effort approach is expected, and so reasonable exceptions are acceptable (e.g. there is not standard means for providing a file header in JSON content). See the [default copyright and license notice template](https://www.eclipse.org/projects/handbook/#ip-copyright-headers).

... which links to https://www.eclipse.org/projects/handbook/#ip-copyright-headers and shows the template that should be used.

We should be able to use 1 year version (not a range) but that year should represent when that specific source file was created.
Need to experiment and see how we can allow that in the license-maven-plugin checks.

**Comment by waynebeaton** [comment]
To the best of my knowledge, the current best practice (as defined by copyright lawyers) is to specify just the date when the specific source file was created. This provides the best possible protection in the event we ever have to defend the copyright.

FWIW, thanks for highlighting the old CPL page; I haven't looked at it in quite a while. I've used the opportunity to add a pointer to the current documentation on the matter and leverage the more comprehensive right-nav that's common to the rest of the /legal section of the website. I'll also add a task to engage in a more complete review of this section of the website to our queue. While I'm at it, I'll also add a task to review the related content in the handbook.

**Comment by joakime** [comment]
I have a solution for this with creation year.
I'll submit a new PR for this using that technique, then we can review.

**Comment by joakime** [comment]
Reopening to continue the discussion here.

**Comment by jmcc0nn3ll** [comment]
@waynebeaton Would it be ok to...

- For any file that existed on the source import into Eclipse, we set the copyright date to 1995.
- Any file created since then can be set to the year it was checked into Git.

Then we don't do this yearly update.

@gregw ^^

**Comment by waynebeaton** [comment]
Given that you've been using 1995 as the base date for some time, that seems reasonable to me. As I stated earlier, this is about copyright law (not some arbitrary requirement of the EF) and my understanding is that getting this "start" date as correct as possible provides the best possible legal position should ever find ourselves with a need to defend the copyright.

With the usual caveat that I am not a lawyer and cannot give legal advice.

**Comment by joakime** [comment]
To see what the creation year option for license header looks like PR #9194 has been created that does it that way.

**Comment by gregw** [comment]
I'm working on a better script to work out the creation date of a file (one that doesn't think that jetty was born on the 3rd of May 2022).
However, I'm not doing this as a priority as we currently have 27 PRs open.... to avoid merge hell/confusion, we need to greatly reduce that number before changing every file in the repo.

**Comment by gregw** [comment]
Closing in favor of #9194 (or similar).

**Pull request closed without merging**
