### PR TITLE
fixing configuring-jsp doc typo

### PR DESCRIPTION
**Pull request by smanikim**

### CODE REVIEW

**Comment by WalkerWatch** [comment]
@smanikim You will need to sign your commit per Eclipse requirements. If you've not signed the Eclipse Contributor Agreement you can do that [here](https://www.eclipse.org/legal/ECA.php). You can then amend your commit with your signature.

**Comment by WalkerWatch** [comment]
@smanikim Just wanted to remind you that this must pass IP Validation before we can accept it.

**Comment by smanikim** [comment]
I have signed ECA, not sure what does it take to update signature

**Comment by sbordet** [comment]
@smanikim you did not sign-off your commit, so please sign it off and force push it. This will re-check your ECA as well.

**Comment by gregw** [comment]
@WalkerWatch looks like we wont get the ECA done correctly for an automated merge on this one.  Can you fix the documentation referenced yourself without a merge (and then close this PR)
Thanks @smanikim for the contribution, but we can't merge without the ECA sign offs.  But will fix ourselves now you brought it to our attention.

**Comment by smanikim** [comment]
not sure where I messed up on ECA sign offs. thanks for taking care of this

**Comment by WalkerWatch** [comment]
Fixed in 7bb1adb

**Pull request closed without merging**
