### PR TITLE
Fix #5939 unwrap ServletException

### LINKED ISSUE #5939: Use unwrapped exception as exception type for error handling
some context here https://github.com/jetty-project/tck-run/issues/14

### PR DESCRIPTION
**Pull request by gregw**
Fix #5939 unwrap ServletException

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by gregw** [comment]
@olamy I reverted the default

**Comment by gregw** [comment]
I currently have this as a boolean on the error handler. It is not really a HttpCompliance issue.  Perhaps we should create a JettyCompliance or ServletCompliance class?  But I'm thinking having the boolean is OK for a start and if we add a compliance, then it can just set the boolean

**Review by janbartel — APPROVED** [review]
LGTM

**Review by olamy — APPROVED** [review]

**Comment by olamy** [comment]
would be good to have some ini files with this.

**Comment by gregw** [comment]
@olamy can't do an ini file because it is a per context configuration.  Ultimately if we create another compliance instance, then we can have ini files to set the server-wide default, but will do as part of a different PR.

**Comment by gregw** [comment]
@olamy merged to 11.  Yell if you need help updating context.xml file for TCK to set this.

**Pull request merged**
