### PR TITLE
Issue #7252 - Customizers before HttpChannel.Listener.onBeforeDispatch

### PR DESCRIPTION
**Pull request by joakime**
Moved `Customizer.customize()` from after `HttpChannel.Listener.onBeforeDispatch()` to before `onBeforeDispatch()`

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Review by gregw — COMMENTED** [review]
I'm not convinced we should make such a big behaviour change in 9.4
In hindsight, perhaps it should have been this way.... except that  customizers can also be considered user code and can actually handle the request.... so perhaps they are a dispatch?

I think this is something for jetty-12 consideration

**Review by gregw — CHANGES_REQUESTED** [review]
I think the new ordering is better..... but we should have an already deprecated option to revert to the old ordering in case we break somebody.

**Comment by joakime** [comment]
While I like the new ordering as it makes sense.
The motivation around this change is lessened due to changes in other PRs.
Perhaps this should be for Jetty 12+? and not Jetty 9+?

**Comment by joakime** [comment]
> I think this is something for jetty-12 consideration

@gregw Still good with this being redone for `jetty-12.0.x-hackathon` branch?

**Comment by gregw** [comment]
Kind of.   Currently 12 has dropped the HttpChannel.Listener concept... but I expect that we will need either to restore it, or a similar mechanism.
So the ordering concern expressed in this PR should definitely be considered when we add listeners back to 12.

Maybe for now, it should just become a TODO in the 12 branch(es) to indicate that listeners should be called after customization.

**Comment by joakime** [comment]
@gregw *bump* do you want to see this for `jetty-12.0.x` ?
We don't have Customizers or HttpChannel.Listener anymore, so ... ??

**Comment by joakime** [comment]
Closing.

Opened as Issue #8218 instead

**Pull request closed without merging**
