### PR TITLE
BZID:455047 Unit tests for jetty-jaspi module to increase code coverage from 58% to 97%

### PR DESCRIPTION
**Pull request by mfarid**
This pull request is focused on module jetty-jaspi. Code coverage is measured using Cobertura. This pull request increases code coverage of this module by 39%.

This PR also addresses the test harness part of the  [BZID:455047](https://bugs.eclipse.org/bugs/show_bug.cgi?id=455047)

Metric | Before | After
-------- | --------- | -----
Coverage % | 58% | 97% 
Lines Covered | 148 | 248
Total Lines | 255 | 255

Please let me know if you have any questions.

Mohd Farid
DevFactory - Code Quality Team

Signed-off-by: mfarid <mohd.farid@devfactory.com>

### CODE REVIEW

**Comment by joakime** [comment]
Just a note, but the addition of powermock means that before this pull request can be accepted, the entire powermock dependency tree and source (and commit history) must go through Eclipse Legal IP Clearance.

It can take a while, months even.
(average turnaround for IP clearance on new project dependencies is 5 months currently)

Be patient.

**Comment by gregw** [comment]
while we look into getting IP clearance for powermock, could you update the PR to follow the jetty coding standards: https://www.eclipse.org/jetty/documentation/current/coding-standards.html

**Comment by gregw** [comment]
@joakime did you kick of a CQ for powermock?

**Comment by janbartel** [comment]
@mfarid could you back out the reformatting of some of the xml files? The reformatting makes it difficult to see what your changes actually are.

Also, I don't think we'd want to accept the changes to the top level pom.xml:   you've removed the definition of the maven deploy plugin. The jacoco plugin has also been added to the <plugins> section instead of the <reporting> section. In fact, should jacoco be in the top-level pom? Perhaps it should be declared in the jetty-jaspi module only?

Also, can you confirm there are 2 new 3rd party dependencies:  powermock and openpojo? We would need to apply for permission from Eclipse to use these before we could accept this (modified) pull request.

**Comment by joakime** [comment]
This pull request isn't going to be merged as-is.
The requests from @janbartel (re formatting of xml) and the powermock requirement makes this difficult to accept.

Consider making these changes in smaller pull requests.
Eg: the powermock addition is 1.  the xml changes in another, etc ...

**Pull request closed without merging**
