### PR TITLE
Fixes #10891 - Support the "Partitioned" cookie attribute.

### LINKED ISSUE #10891: Support the "Partitioned" cookie attribute
**Jetty version(s)**
10+

**Enhancement Description**
A proposal for a new cookie attributed called `Partitioned` is underway, with plans from Chrome and Firefox to support it in the near future.

See https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies (and related links).

This is a server-side only change, as `HttpClient` does not have the concept of a "top-level context" (i.e. a web page) under which other requests are made, and the current behavior of the client-side `HttpCookieStore` is equivalent to `SameSite=Strict`, i.e. cookies set by a domain are only sent with requests for the same domain.

### PR DESCRIPTION
**Pull request by sbordet**
Added support in oej.http.HttpCookie.
Bridged support for Servlet cookies via the cookie Comment attribute.

### CODE REVIEW

**Review by joakime — COMMENTED** [review]
The partitioned spec also has this weird `__Host*` attribute behavior documented.

Do we have test cases where have verified our code can handle those new attribute types?

Take the example ...

```
Set-Cookie: __Host-example=34d8g; SameSite=None; Secure; Path=/; Partitioned;
```

Can our server Set-Cookie logic generate that?
Can our client Set-Cookie parser parse that? (and can we get that information out from the Set-Cookie)?

**Comment by sbordet** [comment]
@joakime it's not an attribute, it's the name of the cookie.
Applications control that, we can't change it or mangle it otherwise.
The draft RFC has not mention of this, so I don't think we should care... seems more a suggestion to application developers to name their cookies in a particular way, not sure why.

**Comment by joakime** [comment]
> @joakime it's not an attribute, it's the name of the cookie.

Ah, good point.

> Applications control that, we can't change it or mangle it otherwise.

True, but we should at least make sure we support that.
I vaguely recall we have some checks on appropriate cookie name syntax.

> The draft RFC has not mention of this, so I don't think we should care... seems more a suggestion to application developers to name their cookies in a particular way, not sure why.

The mozilla documentation mentions it - https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies   
The draft spec does not mention it - https://datatracker.ietf.org/doc/html/draft-cutler-httpbis-partitioned-cookies  
But the draft update for RFC6265 does mention it, as "Cookie Name Prefix" - https://www.ietf.org/archive/id/draft-ietf-httpbis-rfc6265bis-13.html#section-4.1.3

**Review by janbartel — APPROVED** [review]

**Comment by sbordet** [comment]
@joakime good scavenging work on the update to RFC 6265, I'll open a new issue for that, as it is orthogonal to this one.
See https://github.com/jetty/jetty.project/issues/10905.

**Comment by arsenalzp** [comment]
Hello,
Is this issue suitable as "good first issue" for newcomers?

**Comment by sbordet** [comment]
@arsenalzp this issue has been implemented already.

Feel free to look for other, open, "Help Wanted" labelled issues.
Thanks!

**Comment by arsenalzp** [comment]
> @arsenalzp this issue has been implemented already.
> 
> Feel free to look for other, open, "Help Wanted" labelled issues. Thanks!

Yeah, I messed it with #10905.
Sorry, it was my fail!

**Pull request merged**
