### PR TITLE
fix typo and grammar

### PR DESCRIPTION
**Pull request by KangZhiDong**
Signed-off-by: KangZhiDong <worldkzd@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
I've done a bit of research and "HTTP" is technically called an "initialism" - not an acronym.
Initialism are pronounced letter by letter, while acronym are read normally (e.g. NASA is an acronym because you don't pronounce it letter by letter).
Because "H" is "aitch" it begins with a vowel ("a"), so the right article in front of it is "an" - as this PR suggests.
The PR also fixes 3 other cases where "an" was used in front of words beginning with "u" where instead "a" should be used.
While it is a large PR, it really just changes those articles in front of words that are or begin with "http".

**Comment by sbordet** [comment]
@WalkerWatch I'll defer to you the merging, but LGTM.

**Comment by lachlan-roberts** [comment]
It is also correct to pronounce the letter "H" as "haitch", so the phrase "a HTTP request" is correct as well.

**Comment by sbordet** [comment]
@lachlan-roberts do you have a reference? Because I could not find in online dictionaries what you mention - "H" is always "aitch".

I find myself more saying "an aitch-tee-tee-pee request" than "a haitch-tee-tee-pee request".

**Comment by lachlan-roberts** [comment]
@sbordet I would normally say "haitch", but apparently it is less common. But Wikipedia seems to think its a legitimate variant. [link](https://en.wikipedia.org/wiki/H):

> The haitch pronunciation of h has spread in England, being used by approximately 24% of English people born since 1982,[7] and polls continue to show this pronunciation becoming more common among younger native speakers. Despite this increasing number, the pronunciation without the /h/ sound is still considered to be standard in England, although the pronunciation with /h/ is also attested as a legitimate variant.[3]

**Comment by WalkerWatch** [comment]
Both forms are grammatically correct, though "an HTTP" is generally more used based on the preponderance of English-speakers pronouncing "H" as "aitch" versus "haitch".

**Pull request merged**
