### PR TITLE
Troubleshooting Guide

### PR DESCRIPTION
**Pull request by WalkerWatch**
Ongoing work for the suggested Troubleshooting Guide.

I've split it into three main sections ---- Diagnose, Analyze, and Report. I've written most of the Report chapter, and have also moved over our existing troubleshooting guides as well as our information on the Jetty Dump Tool. Looking for Guidance in how you all would like to see Diagnose and Analyze set up.

### CODE REVIEW

**Comment by gregw** [comment]
@WalkerWatch ,  can you point me to some asciidoc-for-dummy instructions as to how I can generate/view the documentation in this PR?

**Comment by jmcc0nn3ll** [comment]
@gregw you can click View on the whole file and github will render a decent look at the asciidoc.  Beyond that, it is currently mounted in the normal documentation at the moment so checkout branch and build jetty-documentation. Then open target/docbkx/html/index.html in browser, new section is at the bottom, VI. Jetty Troubleshooting Guide.  Some day I'll get around to making this all easier, hopefully soon.

**Comment by WalkerWatch** [comment]
@gregw I just build it locally from the `jetty-documentation` directory. View `index.html` in `target->docbkx->html` after that. Currently, this work sits in section VI.

**Comment by gregw** [comment]
There is a lot of reorganization in this PR.... I'm not sure if we want to do that.
Rather I think we need a separate chapter (or document) about how to triage jetty that indexes into the current document.

**Comment by gregw** [comment]
let's take a different approach

**Pull request closed without merging**
