### PR TITLE
Update jaas index.adoc

### PR DESCRIPTION
**Pull request by karstenhusberg**
There is no ee10-jaas module, or ee8-jaas or ee8-jaas as far as I can see and module 'jaas' made it work in my ee10 set-up.

### CODE REVIEW

**Comment by janbartel** [comment]
@karstenhusberg can you also add one more change to this PR? The `jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JaasConfiguration.java` class refers to the package `org.eclipse.jetty.ee10.jaas` which doesn't exist, at this line: https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/JaasConfiguration.java#L38`

**Review by janbartel — CHANGES_REQUESTED** [review]
Please see my comment about making one extra little change.

**Comment by karstenhusberg** [comment]
@janbartel I've updated as per your request. Unfortunately I never got what I intented to do to work and now I must hurry on to other tracks. I was supposed to JNDI-publish a jakarta.mail.Session as described here https://jetty.org/docs/jetty/12/operations-guide/jndi/index.html#mail but when looking it up from within my application I only got a MailSessionReference object not a Session. Probably me doing some obvious error :-)

**Review by janbartel — APPROVED** [review]

**Comment by janbartel** [comment]
Thanks @karstenhusberg, I've merged your changes.

**Pull request merged**
