### PR TITLE
Jetty 12.0.x revert accidental io util server changes

### PR DESCRIPTION
**Pull request by joakime**
The e2abdeaf9037e9012e98895becfcb0b63f01f864 commit accidentally reverted some important changes in `jetty-util`, `jetty-io`, and `jetty-server` (legacy) when moving content over from the (now) `jetty-12.0.x-gregwOLD` branch.

This fixes the bad commit with the following steps ...

1. Make patch of changes from jetty-11.0.x HEAD to jetty-12.0.x-gregwOLD HEAD (of those 3 modules)
     Patch-bcf362cbd57fb2fe17edb04e9e8b83a04528b421-d479e39344348c10b6d54e978a16a5bf876338f0.patch
2. Make patch of changes from jetty-12.0.x (e2abdeaf9037e9012e98895becfcb0b63f01f864 to HEAD) (of those 3 modules)
     Patch-e2abdeaf9037e9012e98895becfcb0b63f01f864-8797322a5ead380830d533719eef982461a65ca4.patch
3. Revert bad commit e2abdeaf9037e9012e98895becfcb0b63f01f864 (restoring `jetty-11.0.x` version for those 3 modules)
4. Apply 11 to 12.0.x-old patch
5. Apply 12-recent-changes patch

### CODE REVIEW

**Comment by joakime** [comment]
To see what files were impacted by the bad commit e2abdeaf9037e9012e98895becfcb0b63f01f864 ...

```
git diff-tree --no-commit-id --name-only -r e2abdeaf9037e9012e98895becfcb0b63f01f864
```

**Review by gregw — APPROVED** [review]
LGTM

**Comment by joakime** [comment]
Set to draft, as I'm unhappy with the changes in commit f686162a7fca88423035848590e385251b1b0553
I want to review that last patch

**Comment by joakime** [comment]
Fixed in PR #7651 instead.

**Pull request closed without merging**
