### PR TITLE
Ability to handle multiple sessions against the same web service

### PR DESCRIPTION
**Pull request by veselinandreev**
Dealing with cookies on per request basis in order to maintain multiple
sessions against the same web service.

Signed-off-by: Veselin Andreev <veselin.andreev@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
Veselin, thanks for this pull request ! 

However, I'm not sure I understand this change.

If I understand well, you would create one (or more) external CookieStore, and then pick the right CookieStore and attach it to the request you want to make.

The way this could already be done right now is to instantiate multiple HttpClients (that could share executor and scheduler), and then pick the right HttpClient to perform the request.

Picking a CookieStore or picking a HttpClient seems equivalent, so I would stick with picking the HttpClient - which has the benefit of no additional code.

Do I miss something ?

**Comment by veselinandreev** [comment]
Hi Simone,
  yes, the idea behind is to attach the desired CookieStore to a particular request.

I'm having to deal with thousands of requests, and instantiating an HttpClient per session compared to a CookieStore ain't the same. Let alone, connection pools are maintained on per client basis, and I don't see how this would be resolved given that each HttpClientTransport holds a reference to its HttpClient.

Kind Regards,
Ves.

**Comment by sbordet** [comment]
Veselin, I'm not convinced.

If you are simulating different users, then typically they have a different CookieStores, different connection pools, different everything, and hence different HttpClients.

For example, it is difficult to simulate two different users with the same browser instance; most of the times you need two browser windows, or even two different browsers.

I'm not sure a server-side service that uses client IP to implement stickyness would be happy to see requests from different users using the same connection.

I cannot pinpoint the problem, but I have the gut feeling that allowing different users on the same connection is not a good thing.

The only thing that comes to my mind is NTLM authentication, which is connection-based. Sure, currently HttpClient does not implement NTLM, but if it will in the future, then sharing connections among users will be fatal.

Historically, HttpClient was designed to be an API to "simulate" a browser, and hence the suggestion that for two users you want two HttpClient instances.
Over time, it accommodated various other use cases; the one you're presenting here is a new one that does not fit the original design, so I am very cautious.

**Comment by veselinandreev** [comment]
Hi Simone,
  in my case, the service acts as middle layer, so reusing connection pools comes quite handy.

With regards to your point about the stickiness, not an expect on LB, but I do agree that LB can be configured to forward all subsequent requests on particular connection to the same back-end without checking the cookie(s). That said two separate HttpClient's can end up creating connections to the same back-end server, so it really boils down to the use case.

Use case here is mainly connections to API feeds, and connection persistence spares continues SSL handshakes, and having to deal with large base of users its simply inefficient to have separate connection pools.

Proposed changes does not alter the behaviour of the client, it only adds optional functionality, thus letting the choice to whoever use the HttpClient to decide how to handle cookies sounds reasonable no ?

Thanks for raising your concerns, its a fruitful conversation, and did made me think through a few additional aspects.

Kind Regards,
Ves.

**Comment by veselinandreev** [comment]
Hi Simone,
  did you had time to review this further ?

Kind Regards,
Ves.

**Comment by sbordet** [comment]
Veselin,

I am thinking to give you an overridable method in `HttpClient` when a cookie is received.

In this way, you just need to override that method and put the cookie in the `CookieStore` you want.

On the request side, `Request.cookie(HttpCookie)` will allow you to send them from the `CookieStore` you want.

This will minimize the changes needed, not add new methods to `Request`, and cover your use case with more or less the same code.

Would that work for your use case ?

**Comment by veselinandreev** [comment]
Hi Simone,
  I'm not sure I fully understand the proposed solution, worth mentioning that I'm dealing with parallel requests to the same destination.

  How would I be able to distinguish between different requests ? Does that mean the default cookie store has to be different than Empty instance to make this work ? If so, I assume Request would completely ignore the cookie store ? How would redirects work with this ?

P.S I was also looking at having authentication store in similar fashion as the cookie store.

Kind Regards,
Ves.

**Comment by sbordet** [comment]
This is the idea:

```java
HttpClient httpClient = new HttpClient() {
  protected void storeCookie(Request request, HttpField cookieHeader) {
    // This is the default implementation that you can override.
    getCookieManager().put(request.getURI(), toMap(cookieHeader));
  }
};
```

What you need to do is to override that method and choose a `CookieManager` based on the request you get passed. Perhaps I can pass directly the `Map` that `CookieManager` requires rather than `HttpField`.

Your implementation would be something like:

```java
HttpClient httpClient = new HttpClient() {
  protected void storeCookie(Request request, HttpField cookieHeader) {
    CookieManager cm = selectCookieManager(request.getURI());
    if (cm != null) {
      cm.put(request.getURI(), toMap(cookieHeader);
    } else {
      super.storeCookie(request, cookieHeader);
    }
  }
};
```

This new mechanism impacts only the way cookies are stored. Whether the default cookie store is the `Empty` instance or whether there are redirects would be irrelevant.

On the request side, you can pull your own `CookieStore` from the `CookieManager` depending on the URI you are sending the request to, and then just do:

```java
CookieManager cm = selectCookieManager(request.getURI());
if (cm != null) {
  CookieStore store = cm.getCookieStore();
  List<HttpCookie> cookies = store.get(uri);
  Request request = ...;
  cookies.forEach(request::cookie);
  ...
  request.send();
} else {
  ...
}
```

Works for you ?

**Comment by veselinandreev** [comment]
Hi Simone,
  what you are proposing wouldn't really work out for me, simply because the URI would be the same. I would need some identifier of the request. The whole point of me having separate cookie jars is to handle multiple sessions against the same destination.

Kind Regards,
Ves.

**Comment by sbordet** [comment]
You have the request in the new method, if that's what you need.

**Comment by veselinandreev** [comment]
Oh, I see what u meant, so I will have to implement my own version of the HttpRequest to accommodate this. Well in that case, sure. What about auth store ?

**Comment by sbordet** [comment]
Why you need your own `HttpRequest` ? I don't think you need.

Let's solve this first and then open another issue about the authorization store.

**Comment by veselinandreev** [comment]
I have to keep the cookie jars independently, so how do u suggest they are managed ? Consider the following example, you are submitting API calls to the same end-point, the only difference is the payload (the XML command to be performed), so this means there's nothing unique in the request that I can use to identify the session into which cookies are to be stored.

**Comment by sbordet** [comment]
The `Request` object is unique and cannot be reused.

```java
CookieManager simonCM = ...;
CookieManager veselinCM = ...;

// Log in Simon.
Request simonLogin = ...;
this.requests.put(simonLogin, simonCM); // a Map
simonLogin.send();
// Server sends back a cookie, new method `HttpClient.storeCookie()` gets called.
  void storeCookie(Request request, ...) {
    CookieManager cm = requests.remove(request);
    ...
  }
// Now you have the cookie for Simon stored in simonCM.
Request simonAPICall = ...;
simonCM.getCookieStore().get(simonAPICall.getURI()).forEach(simonAPICall::cookie);
simonAPICall.send();

// As you can see from above, simonCM is for requests for Simon only.

// Log in Veselin.
Request veselinLogin = ...;
// like above, just with veselinCM.
```

What above allow you to submit API calls to an endpoint on behalf of different users, concurrently, without mixing the cookies.

If that's not what you're doing, then I did not understand what you're trying to achieve.

**Comment by veselinandreev** [comment]
I see what you meant now, sure, it can be achieved like that, also `HttpClient.copyRequest()` needs to be overridden to accommodate the additional logic of carrying over the cookieS and attaching the new instance to the same cookie jar. What concerns me is that I will have a concurrent map for no reason. Anyway this is more of implementation approach, so its irrelevant in this discussion.

What you have proposed as alternative is usable and should suit my needs.

Many thanks.

Kind Regards,
Ves.

**Comment by gregw** [comment]
closing as there is a solution.  thanks for the PR and reopen if you think something more is needed

**Comment by sbordet** [comment]
Reopening since the solution I proposed may not work for redirects and authentications.

**Comment by joakime** [comment]
@sbordet did you file an issue regarding this pull request?

**Comment by sbordet** [comment]
See #799.

**Comment by veselinandreev** [comment]
I think, I have the authentications code prepared for commit, well it was designed in a similar way as the cookies, so not sure you would agree with it :)

**Comment by gregw** [comment]
Closing this PR and leaving #799 open for further discussion

**Pull request closed without merging**
