### PR TITLE
Factory method for constructing ConnectorServer listening on localhost only

### PR DESCRIPTION
**Pull request by bjorncs**
This PR adds a factory method to `ConnectorServer` to construct an JMX/RMI endpoint that is only accessible through the loopback interface. This is not straight-forward and requires overriding the server socket factory of both the RMI registry and RMI connector server + overriding the _"java.rmi.server.hostname"_ property.

### CODE REVIEW

**Comment by bjorncs** [comment]
@sbordet How does this look?

**Comment by sbordet** [comment]
`ConnectorServer` needs a lot more love. It is supposed to start 2 servers, the RMI registry and the RMI server that listens to remote JMX calls. Your patch seems to address only starting the RMI registry on the loopback interface, but not the RMI server. 

Furthermore, we may want to expand `ConnectorServer` to run over TLS as well.

@bjorncs what is exactly the purpose of this PR for you ? You want that JMX is only available on the loopback interface for security reasons ?

**Comment by bjorncs** [comment]
The intention of the PR is to provide a factory method to `ConnectorServer` that initiates both the JMX connector server and RMI registry. Both are sharing a server socket instance that listens to loopback interface only (for security). The goal is to have a setup where no RMI-related services are available through anything but the loopback interface.

By _RMI server_, do you mean the connector server created by `JMXConnectorServerFactory.newJMXConnectorServer`?

**Comment by sbordet** [comment]
@bjorncs so the real need is to listen _only_ on loopback interface for both the RMI registry and the RMI server.

> By RMI server, do you mean the connector server created by `JMXConnectorServerFactory.newJMXConnectorServer` ?

Yes. Your test case does not test that this RMI server is on the loopback interface too, and RMI has its own weird way to export stubs, so I am not sure of what it is actually done.

I don't like that a global system property is set in the `ConnectorServer` code - that should be done at the command line.

I understand your use case, but this PR is not optimal. Can you please open an issue that details the need that this PR is supposed to solve ?
I will use that issue number to implement a solution.

Thanks !

**Comment by sbordet** [comment]
@bjorncs see #1517.

**Comment by bjorncs** [comment]
Thanks :)

**Comment by sbordet** [comment]
@bjorncs work on #1517 is completed, it now supports loopback interfaces and TLS.

**Comment by bjorncs** [comment]
Thank you!

**Pull request closed without merging**
