### PR TITLE
Bugfix for #920 (disable bundle plugin)

### PR DESCRIPTION
**Pull request by olamy**
fix for #920  simply disable bundle plugin as we don't need it here.

### CODE REVIEW

**Comment by joakime** [comment]
Wow!  looks real comprehensive.
Need some time to digest it.

**Comment by olamy** [comment]
well if you prefer something easier and only related to this issue, just keep the last commit with the skip=true for the jetty-runner module

**Comment by olamy** [comment]
@joakime I took the lazy approach and remove commits which generate failure (not sure about investigate so much changes for 9.2.x would make sense...)
So I simply skip the bundle plugin for jetty-runner :-)

**Comment by olamy** [comment]
well not sure unit test failure is related...

**Comment by janbartel** [comment]
Thanks @olamy

**Pull request merged**
