### PR TITLE
Updating Websocket documentation for Jetty 10 per #1165

### PR DESCRIPTION
**Pull request by WalkerWatch**

### CODE REVIEW

**Comment by WalkerWatch** [comment]
@lachlan-roberts on #1165 you mentioned that the sendByFuture calls are now deprecated but I was not entirely sure about how to replace them. Can you review that section and re-work the examples as needed? Alternately, we can collab on it.

**Comment by lachlan-roberts** [comment]
@WalkerWatch we might need to collab on it, my IDE is giving me a hard time trying to change certain things in the documentation without breaking it. Besides I think most of those async examples are redundant when using `WriteCallback`, I think it could be simplified to a single example.

**Comment by lachlan-roberts** [comment]
@WalkerWatch I replaced the `sendByFuture` examples with an explanation of the `WriteCallback` methods with an example. There is now also async methods with `WriteCallback` for pings and pongs so I added that as well. Can you review/edit the changes.

**Comment by WalkerWatch** [comment]
@lachlan-roberts Updated some grammar. Please review and approve. Feel free to squash/merge as well if you'd like.

**Pull request merged**
