### PR TITLE
Don't shut down output after sending a GOAWAY frame

### PR DESCRIPTION
**Pull request by swankjesse**
https://github.com/eclipse/jetty.project/issues/2788

### CODE REVIEW

**Comment by olamy** [comment]
@swankjesse Thanks but you need first to sign the Eclipse Contributor Agreement (ECA) please refer to https://www.eclipse.org/jetty/documentation/9.4.20.v20190813/contributing-patches.html

**Comment by sbordet** [comment]
@swankjesse your PR removes altogether the `shutdownOutput()` and relies on the idle timeout to close the underlying `EndPoint` - we cannot rely on that because people may configure very large idle timeouts and clients are waiting for the -1 to close themselves.
We cannot rely on clients sending back the `GOAWAY`, nor on clients closing TCP connections properly.

We really need a graceful close timeout different from the idle timeout.

**Comment by swankjesse** [comment]
Perhaps there’s room for a new API, `HTTP2Connection.noNewStreams()` to send a GOAWAY frame and initiate graceful shutdown? That leaves `Connection.close()` as-is for an urgent shutdown.

**Comment by sbordet** [comment]
@swankjesse I'm going to close this PR. We will be working on having GOAWAY being more graceful as the specification hints, perhaps with some configurable timeout. Thanks!

**Comment by swankjesse** [comment]
👍🏻. Thanks!

**Pull request closed without merging**
