### PR TITLE
Updating osgi documentation

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
@janbartel looks like the osgi docs are out of date.

We could use an update, I've started this on the `osgi-doc-update` branch, but the there's a bunch of tables of dependencies for bundles that seem off (such as a reference to `aries-util` which isn't referenced by the included bundles or maven poms for spifly 1.1)

**Comment by janbartel** [comment]
Spifly needs aries-util at runtime.

**Comment by joakime** [comment]
Do we need to update the reference in the documentation? perhaps just the version?
Oddly, the spifly-1.1 pom has no reference to `aries-util`

**Comment by joakime** [comment]
Otherwise, if you are ok with this PR, feel free to merge it. (or tell me it's good to merge)

**Pull request closed without merging**
