### PR TITLE
Allow headers size extend to maxRequestHeadersSize in http client

### PR DESCRIPTION
**Pull request by shaoxt**
PR for https://github.com/jetty/jetty.project/issues/12436

### CODE REVIEW

**Comment by sbordet** [comment]
@shaoxt make sure you comply with the Eclipse ECA, see https://github.com/jetty/jetty.project/blob/jetty-12.0.x/CONTRIBUTING.md, otherwise we cannot accept this contribution.

**Comment by shaoxt** [comment]
Screenshot 2024-10-29 at 1 01 29 PM

**Comment by shaoxt** [comment]
Screenshot 2024-10-29 at 1 03 30 PM

**Comment by shaoxt** [comment]
Had PR merged before.  And resigned the ECA again.  

> @shaoxt make sure you comply with the Eclipse ECA, see https://github.com/jetty/jetty.project/blob/jetty-12.0.x/CONTRIBUTING.md, otherwise we cannot accept this contribution.

**Comment by joakime** [comment]
Your various commits on this PR have 3 different email addresses associated with it.

Example:

* https://github.com/jetty/jetty.project/commit/6306d175d499c0c5f9715cc6989fc032f882b608.patch - gmail address
* https://github.com/jetty/jetty.project/commit/d49a07a27c337743d91b36c18cc3843046dfa1bc.patch - intuit address

Squash (or rebase) all of these commits and make it a single commit with just your registered gmail address.

**Comment by shaoxt** [comment]
Close this PR for the invalid authors.

**Pull request closed without merging**
