### PR TITLE
Issue #12185 implementation/test of max suspended requests in QoSHandler

### LINKED ISSUE #12185: QosHandler suspend queue limit
**Jetty version(s)**
12.0.11

**Jetty Environment**
ee10

**Java version/vendor** `(use: java -version)`
java 21.0.3 2024-04-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)

**OS type/version**
Ubuntu  22.04

**Description**
We are using QoSHandler to protect app from being flooded with requests, but had an incident with a combination slow backend  and sudden big increase in requests causing suspend queue to grow without a limit and finally OOM:ed. AWS auto scaling could not scale out quick enough, all instances died.

Suggestion is to have similar limit check to suspended requests as already exists for max active requests to prevent this scenario.

Happy to provide a PR if you consider this a valid feature of QoSHandler.

### PR DESCRIPTION
**Pull request by LarsKrogJensen**

### CODE REVIEW

**Comment by sbordet** [comment]
@LarsKrogJensen please read https://github.com/jetty/jetty.project/blob/jetty-12.0.x/CONTRIBUTING.md

In particular, be sure you have signed the Eclipse ECA, otherwise we cannot accept your contribution.

If you don't want to sign it, let us know, and we'll take over (but we'll close this PR).

Thanks!

**Comment by LarsKrogJensen** [comment]
created account and signed ECA

**Comment by LarsKrogJensen** [comment]
unit test fails on Jenkins, works locally, any ci gotchas to be aware of?

Edit: I suspect Stream.parallel(..) is dependent on underlying cores

**Comment by LarsKrogJensen** [comment]
@sbordet ECA signed and tests _mostly_ fine, some unrelated test fails for java 22

**Review by sbordet — APPROVED** [review]

**Comment by sbordet** [comment]
@LarsKrogJensen thanks!

I have limited the max number of suspended requests to 1024, and simplified your test case.

**Comment by LarsKrogJensen** [comment]
@sbordet Sounds like a reasonable limit, but I didn't want a behavioral change and went with max int.

**Comment by sbordet** [comment]
> Sounds like a reasonable limit, but I didn't want a behavioral change and went with max int.

Yes, and it was a fair decision.

Looking more carefully though, the heuristics for `maxRequestCount` is a pretty small number, in the 10-100, so 1024 queued seems more reasonable, and less of a hassle for security reviews.

For larger requests/s, developers would have to change `maxRequestCount`, and so they can increase `maxSuspendedRequestCount` as well.

**Comment by sbordet** [comment]
### Behavior Change

The number of suspended requests is now limited by default by `QoSHandler`, which may result in more 503 responses than before.
Applications must explicitly call `QoSHandler.setMaxSuspendedRequestCount()` if they want a larger than default number of suspended requests.

**Pull request merged**
