### PR TITLE
use maven feature with version using revision token

### PR DESCRIPTION
**Pull request by olamy**
so we can deploy branch snapshots with a dedicated version number

Signed-off-by: olivier lamy <oliver.lamy@gmail.com>

### CODE REVIEW

**Comment by sbordet** [comment]
I tried for ages to use a property on the `parent.version` element, but I don't think Maven supports it.

The build has failed for that reason.

Unless there is some hidden Maven magic, this will not work.

**Comment by joakime** [comment]
I think this is because the POM has to resolve all parents before attempting to parse the pom.
So you can't have something in the pom involved in the parent resolution.

I bet if you declared the version on the command line it would work.

aka.  `$ mvn clean install -Drevision=9.4.12-FOO`

as now that information comes from outside of the pom itself.

**Comment by sbordet** [comment]
But `revision` to me is the wrong name. Can't we just call it `project.version` as standard Maven?

@olamy frankly I don't understand why we are doing this.
What is the use case where we need to change the `project.version`?

**Comment by joakime** [comment]
Actually, the version `9.4.12-2836-SNAPSHOT` would be invalid per OSGi rules and would be rejected by the enforcer plugin configuration.
So the revision/version would likely have to be `9.4.12.2836-SNAPSHOT` instead.

**Comment by olamy** [comment]
@sbordet the feature is since 3.5.0-beta-1 read https://maven.apache.org/maven-ci-friendly.html
The use is the one explained by @joakime 
we may have to change a bit the release script.
the failure was due to building jetty-all-compact3 using the maven command -f instead of -pl option so the property revision was not read correctly.

**Comment by janbartel** [comment]
@olamy  @sbordet @joakime what are we doing with this PR, is it going forward?

**Comment by sbordet** [comment]
@janbartel waiting for @olamy to fix this.
@olamy can you please rebase this on top of the current 9.4.x branch?

**Comment by olamy** [comment]
@sbordet @janbartel  merged but I figured out there is an issue with the bom so not yet ready for merge

**Comment by joakime** [comment]
This concept has a low need. 

With this in place, we have the means for testing non-mainline jetty branches against 3rd party projects that use jetty before being merged back into mainline jetty.

Eg:  we have a branch testing a fix for a bug reported in spring, we can build that jetty branch as `9.4.13.spring-issue-4444-SNAPSHOT`, which spring can use from the jetty-snapshots repository.

**Comment by olamy** [comment]
rebase done

**Comment by olamy** [comment]
my goal was to be able to deploy snapshot of branches with different versions to be able to do load testing on the branches and without having to write complicated build scripts to get the jars to test.
if you don't like this change just drop the pr and voila.

**Pull request closed without merging**
