### PR TITLE
Set source encoding of build-resources module to UTF-8

### PR DESCRIPTION
**Pull request by lorban**
Fixes https://github.com/eclipse/jetty.project/issues/5891

### CODE REVIEW

**Review by olamy — APPROVED** [review]

**Review by gregw — APPROVED** [review]

**Comment by joakime** [comment]
Why did this build fail?

**Comment by joakime** [comment]
I'll kick the tires ...

**Comment by lorban** [comment]
It fails on `DistributionTests.testLog4j2ModuleWithSimpleWebAppWithJSP` with a timeout on an assertion. @olamy have you seen this test failing recently, because my first assumption is that the build machine is just a bit too slow?

I'm going to try to raise the timeout from 5s to 10s as an experiment, but this requires some deeper investigation.

**Comment by lorban** [comment]
@olamy increasing the timeout to 10 seconds made the build pass. Should we assume the build servers are too slow and commit this larger timeout or investigate further?

**Comment by olamy** [comment]
I would say merge it. This issue happened only once in every build we do. if it happened more frequently it will worth investigation but not for only one glitch compared to the number of daily execution of this test :)

**Pull request merged**
