### PR TITLE
add a configuration field to MavenServerConnector to be able to force reUsePort

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <oliver.lamy@gmail.com>

### CODE REVIEW

**Comment by janbartel** [comment]
@olamy what's the motivation for the change? I guess I'm ok with it, but I just want to know why you've added it?

**Comment by joakime** [comment]
> @olamy what's the motivation for the change? I guess I'm ok with it, but I just want to know why you've added it?

I think his work on the jakarta tck with arquillian is the motivation.

**Comment by olamy** [comment]
> > @olamy what's the motivation for the change? I guess I'm ok with it, but I just want to know why you've added it?
> 
> I think his work on the jakarta tck with arquillian is the motivation.

 I remember some issues with dependabot build few weeks ago (sorry but I cannot find it) and a build failing because of the famous  already in use message

**Comment by janbartel** [comment]
> 

OK, but it's not the jetty builds that are failing right? We should always be choosing random ports.

**Comment by janbartel** [comment]
@olamy nudge? This was needed for the tck, not for the jetty builds, correct?

**Comment by olamy** [comment]
nope. TCK is not using maven plugin but Arquillian 
the problems are due to some IT tests (distro forked if I remember correctly) are using hardcoded port such 8080.
and sometimes those tests fail to start as a previous one was using the port already.

**Review by janbartel — APPROVED** [review]

**Pull request merged**
