### PR TITLE
Issue #5254 List/Show modules

### PR DESCRIPTION
**Pull request by gregw**
For #5254

 * simplified --list-modules output
 * added --show-module

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by gregw** [comment]
I believe the CI failures are unrelated

**Comment by gregw** [comment]
@sbordet @joakime bump

**Review by sbordet — APPROVED** [review]
LGTM. However, while we are at it, we should really fix all the first lines of all the modules.
There are some that are 2 sentences on the same like (should be 1), or 1.5 sentences (should be 1), and we should be consistent (like in javadocs) in using the 3rd person, i.e. not "Enable the Server thread pool." but "Enable**s** the Server thread pool."

Alternatively, we should open a new issue for fixing the descriptions.

**Comment by gregw** [comment]
I've had an initial go at improving the modules, but I think I'll  start another process to have all the module descriptions improved.

**Comment by joakime** [comment]
> I've had an initial go at improving the modules, but I think I'll start another process to have all the module descriptions improved.

As a separate PR? or in this one?

**Comment by gregw** [comment]
I've done an initial pass in this PR.   But I think the full cleanup needs to be passed to the doco team to :
 + ensure the same voice is used for all descriptions.
 + it ties into the doco with same descriptions
 + the links are correct etc.

So i don't want it to hold back this issue.

**Pull request merged**
