### PR TITLE
Update Notice

### LINKED ISSUE #1311: Eclipse Handbook recommends "and others" in license header block.
See https://www.eclipse.org/projects/handbook/#ip-copyright-headers

This was brought up by @waynebeaton in PR #1303

### PR DESCRIPTION
**Pull request by gregw**
Signed-off-by: Greg Wilkins <gregw@webtide.com>

Fixes #1311

### CODE REVIEW

**Comment by gregw** [comment]
@jmcc0nn3ll @waynebeaton nudge for review.  We have a release coming out in the next few weeks, so a good opportunity to get the updated language out there.

**Review by waynebeaton — APPROVED** [review]
LGTM.

Please add a plan item to update the project from EPL-1.0 to EPL-2.0. Ideally, in time to be included with the next formal release of Eclipse Jetty.

**Review by jmcc0nn3ll — APPROVED** [review]
Works for me.

**Comment by gregw** [comment]
I've created #4426.  We should go EPL-2.0 for jetty-10 immediately, but I'm not sure that changing license in a dot release of jetty-9.4.x is the right thing to do.  Perhaps if we have to do a 9.5 release with the jakarta naming, then it can be done there.

**Pull request merged**
