### PR TITLE
Added Unit Tests

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added Unit Tests to increase code coverage.

### CODE REVIEW

**Comment by TheRealHaui** [comment]
Created an Eclipse account and accepted the EULA.

**Comment by TheRealHaui** [comment]
Actually, the license headers exist in both test classes I created.

**Comment by olamy** [comment]
@TheRealHaui the pom is outdated using `<copyright-range>${project.inceptionYear}-2017</copyright-range>` 
You should rebase your branch/pr with the current content of jetty-9.4.x and push it so a build will validate again the project and your eca.

**Comment by janbartel** [comment]
@TheRealHaui  did you sign your commits using the same identity that you used to sign the Eclipse ECA? From the failures reported by the ip checker, looks like either you didn't sign the commits, or you signed them with the wrong identity ...

**Comment by TheRealHaui** [comment]
@janbartel,
thanks for your response!
I have to admit I had issues with the Eclipse page after creating my credentials.
I couldn't login as it said to me it does not know me.
After congratulating me via eMail that I am a member now.
I am going to re-verify this.

**Comment by TheRealHaui** [comment]
Eclipse legal stuff done now for sure.
Going to add an additional commit to re-trigger checks execution again.

**Comment by TheRealHaui** [comment]
Okay, we have several problems here:
- I cannot rebase nor merge the pull request onto the desired branch easily as git has too many issues due to the sheer amount of changed file between the two branches.
- I cannot easily make the Eclipse EULA check to verify my commits as all of them need the sign-off footer.

Therefore I am going to close this pull request and am going to make a new pull request with all the mentioned problems solved.

**Pull request closed without merging**
