### PR TITLE
http-spi test improvement

### PR DESCRIPTION
**Pull request by charuvijay**
Dear Team,

This pull request is focused on http-spi module.
Code coverage is measured using JaCoCo. This pull request increases code 
coverage of the whole project by 90%.

Metric             | Before| After
------------------|----------|-------

Coverage%    |0%     |90%

Lines Covered|0      |317

Total Lines      |349     |349
   

Please let me know if you have any questions.

Vijay
DevFactory - Code Quality Team.

commit ca9227e961ca074d4bfa42d801d7aeb810af98b4
Author: Charu <Charu>
Date:   Wed Dec 23 20:58:54 2015 +0530

    Added Review Comments

commit ff30f698bfacd769b96f74c8c2a3a621900b5239
Author: Charu <Charu>
Date:   Wed Dec 23 09:56:07 2015 +0530

    Unit tests for http-spi UTS-60

### CODE REVIEW

**Comment by gregw** [comment]
Charu ,

Awesome to get a PR that is so well tested!    

I'll look at this over the next day or two.  However, we need to get you to e-sign a contributors license. So you need to create an account on bugzilla and click the IP tick next to your name.

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Jetty

**Comment by gregw** [comment]
Oh and a little quibble... it would be great if you could reformat with our coding style - which can be found: http://git.eclipse.org/c/jetty/org.eclipse.jetty.admin.git/tree/

**Comment by mfarid** [comment]
@gregw I have already signed the CLA but the same is not reflected in the ip-validation check. 

Can you please help me fix this issue.

**Comment by joakime** [comment]
CLA now verified via https://projects.eclipse.org/user/cla/validate

**Comment by jmcc0nn3ll** [comment]
Bumping to check the CLA on file.

**Comment by gregw** [comment]
Manual IP validation shows you have signed the CLA.  So I'll merge one way or another...

**Pull request merged**
