### PR TITLE
Jetty 9.4.x 2014 unixsocket client fix tests

### PR DESCRIPTION
**Pull request by olamy**
PR of a branch to test on ci so cannot be merged until all unix socket tests pass.
include merge of jetty-9.4.x to make this pr mergeable

### CODE REVIEW

**Comment by olamy** [comment]
@gregw only 2 test fail now see https://jenkins.webtide.net/job/jetty.project/view/change-requests/job/PR-2096/ but might relatively border line with unix socket..
thoughs? (are they really relevant in case of unix socket?)

**Comment by gregw** [comment]
@olamy this PR appears to be all screwed up and mixed with other PRs

**Comment by olamy** [comment]
the main issue is branch jetty-9.4.x-2014-unixsocket-client contains merges from jetty-9.4.x.
IMHO we should use rebase only for short live branches (bugfix or new features branches)

**Comment by olamy** [comment]
I will create an other branch/pr with the fixes

**Comment by olamy** [comment]
replaced by #2106

**Pull request closed without merging**
