### PR TITLE
Applied skeletal implementation to interface migration automated refactoring

### PR DESCRIPTION
**Pull request by khatchad**
This is a semantics-preserving automated refactoring that migrates existing method implementations in classes to the corresponding implemented interface methods as `default` methods. The tool **does not** add new code; it only rearranges *existing* code.

- We are evaluating a research prototype automated refactoring Eclipse plug-in called [Migrate Skeletal Implementation to Interface](https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring). We have applied the tool to your project in the hopes of receiving feedback.
- The approach is very conservative. Specifically, it only performs a migration if the target interface is unambiguous. That may mean that not all changes that can be made were made. Please feel free to continue the refactoring manually if you wish.
- We only migrated methods declared in abstract classes. We believe such methods to be likely suitable default methods in corresponding interfaces.
- The source code should be semantically equivalent to the original.

Thank you for your help in this evaluation! Any feedback you can provide would be very helpful. In particular, we are interested if *each* of the proposed changes are helpful or not.

### CODE REVIEW

**Comment by sbordet** [comment]
There is recent [evidence](http://www.scala-lang.org/blog/2016/07/08/trait-method-performance.html) that `default` methods degrade performance.

**Comment by khatchad** [comment]
@sbordet, yes, we've seen that article. It doesn't seem that it is a foregone conclusion. Also, the article did mention that the problem exhibits itself in situations where classes implement many interfaces. That doesn't seem to be the case in the changes we've posted here.

**Comment by gregw** [comment]
@sbordet my reading of that article is that it could well just be a JIT bug rather than a fundamental problem.

@khatchad Could you remake this PR against our master branch (Jetty-10.0.x) as this kind of API change is not appropriate for 9.3.x and is probably too late for 9.4.x

We have a lot of instances of the pattern `interface FooBar` with a matching `abstract class AbstractFooBar implements FooBar`.    I'm not sure that splitting the abstract implementation between default methods on the interface and the abstract class is the right thing to do for those, although I can see that it has completely removed the Abstract class in some instances.

**Comment by khatchad** [comment]
@gregw:

> @khatchad Could you remake this PR against our master branch (Jetty-10.0.x) as this kind of API change is not appropriate for 9.3.x and is probably too late for 9.4.x.

Sure.

> We have a lot of instances of the pattern interface FooBar with a matching abstract class AbstractFooBar implements FooBar. I'm not sure that splitting the abstract implementation between default methods on the interface and the abstract class is the right thing to do for those, although I can see that it has completely removed the Abstract class in some instances.

Right, sometimes, we're able to remove the entire skeletal implementation class. Reasons for not being able to do so all the time is two fold:

1. Java 8 default methods are very stringent. For example, interfaces cannot have instance fields, thus, we can't refactor skeletal implementation methods that access those.
2. Our approach is very conservative. It may be possible to refactor more methods after using our tool. I've attached a [report of the precondition failures](https://github.com/eclipse/jetty.project/files/385110/failed_preconditions.csv.zip). You are also welcome to use the tool yourselves. However, we need to release an update version of the tool. Please let us know if that route is of interest and we'll deploy a new version.

In the case that the entire skeletal implementation class cannot be removed, we argue that it is still beneficial to perform the migration for the following reasons:

1. It possibility makes the interface easier to implement as all implementing classes may not need skeletal implementations for every method. For example, if they just need the default implementations in the interface, they can forgo extending the skeletal implementation class.
2. Default methods are particularly useful for optional operations, which may not be all the methods in the interface. They are self documenting, implementers can clearly see what the expected behavior will be if the operation is not implemented.
3. It may make the interface easier to maintain as there is less coupling between the abstract skeletal implementation class and the interface. For example, adding an annotation to an interface method need only occur in the interface.

**Comment by khatchad** [comment]
I've opened another pull request off of master at https://github.com/eclipse/jetty.project/pull/775. However, there seems to be conflicts but I can't find them. Please let me know if I should redo it

**Pull request closed without merging**
