### PR TITLE
change WebSocketRemoteEndpoint private method to proteced method allow user extension this class

### PR DESCRIPTION
**Pull request by leonchen83**
we want send bytebuffer as TextFrame directly. for example
```
public class XWebSocketRemoteEndpoint extends WebSocketRemoteEndpoint {
	
	public XWebSocketRemoteEndpoint(LogicalConnection connection, OutgoingFrames outgoing) {
		super(connection, outgoing);
	}
	
	public XWebSocketRemoteEndpoint(LogicalConnection connection, OutgoingFrames outgoing, BatchMode batchMode) {
		super(connection, outgoing, batchMode);
	}
	
	public void sendString(ByteBuffer text) throws IOException
	{
		lockMsg(MsgType.BLOCKING);
		try
		{
			WebSocketFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendString with {}", BufferUtil.toDetailString(frame.getPayload()));
			}
			blockingWrite(frame);
		}
		finally
		{
			unlockMsg(MsgType.BLOCKING);
		}
	}

	public void sendString(ByteBuffer text) throws IOException
	{
		lockMsg(MsgType.BLOCKING);
		try
		{
			WebSocketFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendString with {}", BufferUtil.toDetailString(frame.getPayload()));
			}
			blockingWrite(frame);
		}
		finally
		{
			unlockMsg(MsgType.BLOCKING);
		}
	}

	public Future<Void> sendStringByFuture(ByteBuffer text)
	{
		lockMsg(MsgType.ASYNC);
		try
		{
			TextFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendStringByFuture with {}", BufferUtil.toDetailString(frame.getPayload()));
			}
			return sendAsyncFrame(frame);
		}
		finally
		{
			unlockMsg(MsgType.ASYNC);
		}
	}

	public void sendString(ByteBuffer text, WriteCallback callback)
	{
		lockMsg(MsgType.ASYNC);
		try
		{
			TextFrame frame = new TextFrame().setPayload(text);
			if (LOG.isDebugEnabled())
			{
				LOG.debug("sendString({},{})", BufferUtil.toDetailString(frame.getPayload()), callback);
			}
			uncheckedSendFrame(frame, callback == null ? NOOP_CALLBACK : callback);
		}
		finally
		{
			unlockMsg(MsgType.ASYNC);
		}
	}
}
```
add an extra method `public void sendString(ByteBuffer text)` to avoid create new string and avoid byte array copy, 
and we know that `ByteBuffer` contains utf-8 byte array.
so could jetty change `private method` to `protected` that allow us to extension this class?

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
@leonchen83 Thanks for the PR, you need to sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) and sign your commits with the same email before your commits can be accepted.

**Comment by lachlan-roberts** [comment]
I feel like making these methods protected probably isn't a good idea as it's encouraging people to become dependent on what should be the internal implementation.

The reason you can only send TEXT frames with Strings is to ensure that the frame payload is properly UTF-8 encoded.

Perhaps we could add some new methods to allow the sending of unchecked text data, or which could verify the `ByteBuffer` contains valid UTF-8 without converting to `String` and back before sending. Thoughts @joakime?

**Comment by sbordet** [comment]
@lachlan-roberts I agree with the reason you mention.

@leonchen83 can you explain why you need to send a `ByteBuffer` as text? How do you know it's properlyUTF-8 encoded? How do you know it's not split in the middle of a UTF-8 byte sequence?

**Comment by joakime** [comment]
Sending raw ByteBuffer as a TEXT frame is in violation of the WebSocket protocol.

Per spec, we MUST validate the buffer to be UTF-8 compliant before we send it.

Leave this closed.

**Pull request closed without merging**
