### PR TITLE
#246 - fixes the wrong version of org.eclipse.jetty.alpn import

### PR DESCRIPTION
**Pull request by ANierbeck**
Signed-off-by: anierbeck <bcanhome@googlemail.com>

### CODE REVIEW

**Comment by joakime** [comment]
@ANierbeck you'll need to submit a signed CLA (Contributor License Agreement) to eclipse in order for us to accept this pull request.
See [CONTRIBUTING.md](https://github.com/eclipse/jetty.project/blob/master/CONTRIBUTING.md) for details

**Comment by sbordet** [comment]
@ANierbeck can you explain in more detail why this is needed ? The ALPN API jar is _never_ used alone, so I find strange that you have to modify its manifest in any way.

**Comment by ANierbeck** [comment]
@joakime, Just did submit a CLA
@sbordet, please also take a look at #246, as Jetty OSGi ALPN Fragment exports the package org.eclipse.jetty.alpn in Version 1.1.2, while the apln-server bundle imports this package in version 9.3.6
It's used and fails to run in the Pax-Web Project, while with a patched version it does work: 
https://github.com/ops4j/org.ops4j.pax.web/tree/PAXWEB-945

**Comment by janbartel** [comment]
@ANierbeck  sorry, just realized that I've actually fixed this issue from a duplicate bug request #263  - didn't see your pull request :(

**Comment by ANierbeck** [comment]
no problem at all, at least the issue is fixed :)

**Pull request closed without merging**
