### PR TITLE
Update Request.java

### PR DESCRIPTION
**Pull request by pethers**
Add extra nullcheck for _metadata

Scenario where the browser is closed, causes exception in combination with vaadin/atmosphere 

2016-01-13 20:12:11,976 [qtp233021551-17] ERROR c.v.s.c.PushAtmosphereHandler - Exception in push connection
java.lang.NullPointerException: null
	at org.eclipse.jetty.server.Request.extractQueryParameters(Request.java:371) ~[jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:357) ~[jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.Request.getParameter(Request.java:989) ~[jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.atmosphere.cpr.AtmosphereRequest.getParameter(AtmosphereRequest.java:456) ~[atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at com.vaadin.server.VaadinService.hasParameter(VaadinService.java:740) [vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:702) [vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:668) [vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:527) [vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.communication.PushHandler.connectionLost(PushHandler.java:327) ~[vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.communication.PushAtmosphereHandler$AtmosphereResourceListener.onDisconnect(PushAtmosphereHandler.java:110) ~[vaadin-server-7.6.1.jar:7.6.1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.onDisconnect(AtmosphereResourceImpl.java:714) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:617) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:597) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:465) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:77) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:312) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:169) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:170) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075) [atmosphere-runtime-2.2.7.vaadin1.jar:2.2.7.vaadin1]
	at com.vaadin.server.communication.PushRequestHandler.handleRequest(PushRequestHandler.java:247) [vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409) [vaadin-server-7.6.1.jar:7.6.1]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364) [vaadin-server-7.6.1.jar:7.6.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835) [jetty-servlet-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685) [jetty-servlet-9.3.7.RC0.jar:9.3.7.RC0]
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200) [javamelody-core-1.58.0.jar:1.58.0]
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178) [javamelody-core-1.58.0.jar:1.58.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [jetty-servlet-9.3.7.RC0.jar:9.3.7.RC0]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:162) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) [spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) [spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [jetty-servlet-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [jetty-servlet-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.Server.handle(Server.java:517) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [jetty-util-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.7.RC0.jar:9.3.7.RC0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.7.RC0.jar:9.3.7.RC0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

All the best.

### CODE REVIEW

**Comment by gregw** [comment]
Pethers. thanks for that.

If you want to get the commit karma (ie your name against the commit), you need to use the same email and sign a CLA on eclipse ([create a bugzilla](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Jetty) for this issue then click the CLA button next to your name.
That will make future contributions easier.

Otherwise we'll just recreate rather than merge this.

Note also, I think there might also be some other getters on the request object that really need the same protection.

**Comment by pethers** [comment]
Happy enough that it get fixed, so please recreate it.

**Comment by gregw** [comment]
reopening as a reminder to fix this and others....

**Comment by pethers** [comment]
```
 @Override
    public String getContentType()
    {
        String content_type = _metadata.getFields().get(HttpHeader.CONTENT_TYPE);
```

Also needed null check for _metadata.

**Comment by joakime** [comment]
Reading the stacktrace ...

So the request is async and suspended, then a disconnected listener kicks in, then you attempt to access the request object?  

Seems that its already far to late to be accessing the request object.

While we can fix the NPE, there's still seems to be a bug in the vaadin/atmosphere side with regards to honoring the lifespan of a request.  If the request is disconnected, then access to the parameters is no longer possible/reliable. (as there's no longer a request object)

**Comment by pethers** [comment]
Ok, thanks for all the help. 

Will check with vaadin/atmosphere projects instead, not a real issue since the browser is closed but still annoying to get stacktraces in the log.

**Comment by gregw** [comment]
reopening again.... I  still want to add the NPE checks.

**Pull request closed without merging**
