### PR TITLE
Read JAVA_OPTIONS in jetty.sh

### LINKED ISSUE #8152: jetty.sh does not read JAVA_OPTIONS anymore
**Jetty version(s)**

Jetty 10.x since commit c89866682c14ca1da0ce482eeca0953375b25da8, ie 

git tag --contains=c89866682c14ca1da0ce482eeca0953375b25da8                                   
jetty-10.0.8
jetty-10.0.9
jetty-11.0.8
jetty-11.0.9

**Java version/vendor** `(use: java -version)`

Any

**OS type/version**

Any

**Description**

Since commit c89866682c14ca1da0ce482eeca0953375b25da8, `JAVA_OPTIONS` is not read anywhere in `jetty.sh` script. 
I believe the goal of the refactoring was to add `JETTY_SYS_PROPS` and then add `JAVA_OPTIONS` in `RUN_ARGS`, but it was not done

### PR DESCRIPTION
**Pull request by fanf**
Fixes https://github.com/eclipse/jetty.project/issues/8152

### CODE REVIEW

**Comment by joakime** [comment]
This is not necessary, as the JAVA_OPTIONS carries over to the JVM itself without reference on the command line.

Also, since a forked JVM is highly possible, it's recommended that you put what used to be in JAVA_OPTIONS is now in your `${jetty.base}/start.d/exec.ini` (once you have the `--add-module=exec` called)

**Comment by fanf** [comment]
Oh. The paramaters where not taken into account anymore without that change. 
But OK, there must be something else happening. I will look at the `exec.ini` option. 
Thanks, and sorry for the noise then

**Comment by joakime** [comment]
Don't worry about it.
This feels like a harmless addition to `jetty.sh`, so I'm leaning towards merging it.
Just testing a few different scenarios where the `$JAVA_OPTIONS` and `${jetty.base}/start.d/exec.ini` conflict and see what happens.

**Comment by joakime** [comment]
@fanf we need you to have a valid Eclipse ECA so we can merge this.

**Comment by fanf** [comment]
Sorry for the delay, it is now done

**Comment by fanf** [comment]
Hum, no, email inconsistency, let me do that again

**Comment by fanf** [comment]
OK, done for real

**Review by joakime — APPROVED** [review]

**Pull request merged**
