### PR TITLE
Fix typo in DefaultServlet

### LINKED ISSUE #952: If 'If-None-Match' value ends with '--gzip', Jetty always sends back: 304 - Not Modified
Check this line:
https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java#L770

```java
if (etag.equals(ifnm) || ifnm.endsWith(ETAG_GZIP_QUOTE) && ifnm.indexOf(',')<0 && etag.equals(removeGzipFromETag(etag)))
```
`removeGzipFromETag` - removes `--gzip` suffix from etag, so it must return true.
Looks like a typo.

Shouldn't there be `etag.equals(removeGzipFromETag(ifnm))` at the end of if? :)

PJ

### PR DESCRIPTION
**Pull request by btd**
Fixes #952

### CODE REVIEW

**Comment by sbordet** [comment]
Can you please add a test case in `DefaultServletTest` ?

**Comment by btd** [comment]
Yes, will do

**Comment by btd** [comment]
@sbordet could you please assist me a bit. [This](http://github.com/btd/jetty.project/blob/a12ad8c4772a81705a9c64678e91aa8e47c2452e/jetty-servlet/src/test/java/org/eclipse/jetty/servlet/DefaultServletTest.java#L816-L818) test assertion passes because now `etag.equals(removeGzipFromETag(ifnm))` always return true. After fix this is still passed but correctly. I just not sure what to test.

**Comment by joakime** [comment]
@btd I think the test should produce an http request with a valid etag.

Probably start by requesting the resource once normally, get the ETag produced.
Then request a second time, but with the ETag from the first in the request's `If-None-Match` header.

That header value should also include the extra `--gzip` suffix that your patch fixes.

Then assert that the response status code (and headers?) on this second request indicate that the resource is unchanged (status code `304 Not Modified`) with no body content.

**Comment by gregw** [comment]
LGTM

**Pull request merged**
