### PR TITLE
Fixes some spelling mistakes, see issue #4160

### PR DESCRIPTION
**Pull request by gouessej**
Fixes some spelling mistakes in the very beginning of the section "Aliased Files and Symbolic links"

### CODE REVIEW

**Comment by WalkerWatch** [comment]
Your commits do not satisfy the Eclipse Legal requirement for a signed ECA. (See details of commit checks)
We are unable to merge without a signed ECA.
See https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by gouessej** [comment]
@WalkerWatch Thank you for the reminder, I'll fill the form tomorrow.

**Comment by gouessej** [comment]
@WalkerWatch It should be ok now, I've just filled the form.

**Comment by joakime** [comment]
Last check failed, but not for ECA, but lack of `Signed-off-by` git commit footer, as indicated in the [CONTRIBUTING.md](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/CONTRIBUTING.md)
See: https://accounts.eclipse.org/legal/eca/validation/15875 for details.

**Pull request closed without merging**
