### PR TITLE
migrate documentation to Antora (jetty-11.0.x)

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by olamy** [comment]
we might not need this as it's already done with #11739 
we usually merge `jetty-10.0.x` to `jetty-11.0.x`

**Comment by mojavelinux** [comment]
I strongly advise that you do not try to merge across branches in this case. There are subtleties in the migration of the content that cannot be captured by forward porting the PR. It will introduce irreversible and difficult to track problems. Each PR needs to be merged independently.

**Comment by joakime** [comment]
That's not how we do things.
Jetty 10 gets merged to 11.
11 gets merged to 12.0.0
And soon 12.0.0 to 12.1.0

**Comment by mojavelinux** [comment]
Well, it's asking for trouble. That's because this isn't a normal code change. We are taking files in a branch, migrating them to a different structure and rewriting references, then putting them back into the branch in the new location. If you want to try to merge across branches, I can't stand in the way, but I also can't be responsible for the result.

**Comment by joakime** [comment]
I'm totally on board with "be careful" (the "don't do it" option isn't even on the table IMO)

**Comment by mojavelinux** [comment]
Sorry, but you are just not understanding.

**Review by sbordet — APPROVED** [review]

**Pull request merged**
