### PR TITLE
Issue #4123 - add documentation for OpenID to 9.4.x

### PR DESCRIPTION
**Pull request by lachlan-roberts**
**Issue #4123**

cherry-picked back to 9.4.x the documentation for OpenID added in #4610.

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
@WalkerWatch I had to remove the links for Google and Amazon OpenID documentation as it was causing a build error.

**Comment by lachlan-roberts** [comment]
@WalkerWatch I don't think that link for amazon sign in was actually talking about an amazon "OpenID Connect" provider, although its very similar using OAuth 2.0, but I don't think it will be directly compatible with our OpenID Connect authentication mechanism.

I think we should remove that example or replace it with another example.

**Review by WalkerWatch — APPROVED** [review]

**Comment by WalkerWatch** [comment]
@lachlan-roberts I think removing the links is fine. I feel like providers are going to vary greatly from implementation to implementation, and our OpenID compatibility is just there to plug in with that - we don't have a preferred provider, so no real need to provide links that ultimately may change anyway.

**Comment by lachlan-roberts** [comment]
@WalkerWatch well as long as they implement OpenID Connect (OIDC) then we will be compatible with them. Turns out you can create an OIDC Identity provider in the AWS Console so I think its fine to leave amazon there. 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html

**Pull request merged**
