### PR TITLE
Issue #2123 Rename apache-jsp to jetty-apache-jsp and apache-jstl to jetty-apache-jstl

### PR DESCRIPTION
**Pull request by janbartel**

### CODE REVIEW

**Comment by gregw** [comment]
As this is going in a dot release, I think we should retain a deprecated `apache-jsp` module that all it has is a pom with a dependency on `jetty-apache-jsp`

**Comment by joakime** [comment]
Wouldn't it have been easier to just adjust the META-INF/MANIFEST.MF to include the "jetty-" prefix instead?

That way the pom, maven coordinates, and artifact are all still where they were before, but are prefixed for java 9?

IIRC (have to look this up), we could go with ...

```
Automatic-Module-Name: org.eclipse.jetty.apache-jsp
```

or something similar.

**Comment by joakime** [comment]
If we are going to do this, we should go through all of Jetty and pick stable module names for all of our artifacts, not just these 2 artifacts in this PR.

Other open source projects are going with `<groupId>.<artifactId>` as their names.
Eg: ReactiveX/RxJava#5618

**Comment by janbartel** [comment]
@gregw  pointed out that we probably shouldn't be calling the module apache-jsp because quite correctly it is not us co-opting apache's jasper, just jetty integrating it, so jetty-apache-jsp is in fact a better descriptive name. I also renamed apache-jstl for the same reason.

**Comment by joakime** [comment]
I'd vote for "jetty-jsp" and "jetty-jstl" without the word "apache" in the name, as that's just confusing.
(Is this an eclipse project or an apache project?)

The org.mortbay version could easily be "mortbay-jsp" as an example.

**Comment by jontro** [comment]
Thanks for looking into this, any ideas on what would be a good work around until this is fixed?

**Comment by gregw** [comment]
I'm not sure there is a perfect solution in jetty-9.4:
1. The status quo is broken
2. Just setting the Automatic-Module-Name gives us a `foobar.jar` that is internally named `jetty-foobar.jar`: mvn==jar!=module
3. We could just rename the artifact produced by the current maven coordinates, so it would match the module name: mvn!=jar==module
4. We could rename the module and leave a pom at the old mvn coords: old_mvn!=new_mvn==jar==module

I think Jan is aiming for 4.  If that's not acceptable, then my next preference is 3., then 2.

Note, I don't think we are yet ready to turn all our jars into modules. That will happen, but not in 9.4.x.

**Comment by sbordet** [comment]
@joakime, JDK 9 (automatic) module names must have dots, not dashes.

And more importantly, they cannot be related to the Maven artifact name, see http://blog.joda.org/2017/04/java-se-9-jpms-modules-are-not-artifacts.html and 
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by gregw** [comment]
-1 for dropping `apache` from the name.   Imagine if somebody took `jetty-server` and provided it to their users as `acme-server`.    I'm sure this happens, but it is not a good look.   Jetty does not have a JSP implementation, we adapt apache-jsp and use it.

**Comment by joakime** [comment]
Just for the record, `Automatic-Module-Name` is the JPMS version of OSGi's `Bundle-SymbolicName`, its just a name that the specific artifact wants to be known as.

The existence of the name doesn't mean its a module/bundle, just that it is named.

OSGi has the same `mvn == jar != Bundle-SymbolicName` relationship now.

**Comment by janbartel** [comment]
The other option is that I rename and re-release the mortbay apache-jsp module to mortbay-apache-jsp, that way we don't have to touch much in jetty, just the artifact name of the dependency on mortbay apache-jsp.

**Comment by joakime** [comment]
Another point towards the metadata approach.

Currently, the jar filename is the extreme fallback for the name of the artifact.

Then we have metadata for other names.

* Old school Java has META-INF/MANIFEST.MF entries such as Implementation-Name, Implementation-Version, etc..
* Maven has META-INF/maven/*/pom.properties which point to <groupId>.<artifactId>.<version>
* OSGI has META-INF/MANIFEST.MF entries such as Bundle-SymbolicName, and Bundle-Version
* Java JPMS has META-INF/MANIFEST.MF entry for Automatic-Module-Name (no version)

Right now, before this change, we have a situation where there are 4 sources for the name, and they all have different information.  Adding JPMS will make it 5 sources for the name.

**Comment by gregw** [comment]
Having read (ok skimmed) those blogs that @sbordet linked to, I'm now in favour of option 2 (`mvn==jar!=module`) where we just set a Automatic-Module-Name.

I think we should do this on BOTH mortbay and jetty JSP jars.

So the big question remains, what is the module naming scheme we will go with?

`org.eclipse.jetty.apache.jsp` ?? although there is one class in the `org.eclipse.jetty.jsp` package?  

`jetty.apachejsp` ??  It is short and does get away from package!=module issues.

`jetty.jsp` I'm really against dropping the apache from the name of such a major component.

I do like fully qualified names to avoid confusion.  Also having long names does allow for a hierarchy of modules to be created as the `jetty.foobar` naming scheme does imply a flat structure.

So my preferences are  `org.eclipse.jetty.apache.jsp`  and  `org.mortbay.apache.jsp`

**Comment by gregw** [comment]
@jontro a work around would be to add a Automatic-Module-Name to one of the jars yourself.  You could even do this in maven, making a new artifact using the dependency plugin.

**Comment by gregw** [comment]
Actually, change that... my preferences are now to firstly do just the Mort Bay release with `Automatic-Module-Name`s:

 - `org.mortbay.apache.jasper`
 - `org.mortbay.apache.el`

Then maybe do the jetty jar with `Automatic-Module-Name` :

 - `org.eclipse.jetty.apache.jasper`

**Comment by janbartel** [comment]
@jontro what tool are you using to do your build and run? I guess you could always manually change the name of the mortbay jar (yuk) or repackage it locally with a modified manifest (marginally less yuk).

**Comment by sbordet** [comment]
FTR, I like better what Spring has done, so `jetty.something` and `mortbay.something` rather than prefixing with `org` or `org.eclipse` that gives zero additional information and they are longer to read and type, especially when we will use real `module-info.java` files.

**Comment by joakime** [comment]
@sbordet "Spring" is the both the name of the project and the rights holder name.
We would need to do, at least, `eclipse.jetty.*`

And the recommendations at the Eclipse OSGi side is to use `org.eclipse.*` for the `Automatic-Module-Name`.

* See commit links at https://bugs.eclipse.org/bugs/show_bug.cgi?id=527855

**Comment by janbartel** [comment]
So what's the consensus here?

Shall I only touch the mortbay project and simply add  Automatic-Module-Names for the apache-jsp and apache-el jars to be:

* org.mortbay.apache.jasper
* org.mortbay.apache.el

That way I don't have to touch jetty at all, and thus we can discuss and decide on a definitive approach to jetty java9 module naming.

?

**Comment by gregw** [comment]
@janbartel there you go again... talking crazy talk like this project is a democracy :)

I think just updating mortbay for now is the best because it is minimal and doesn't commit us to module names style yet.

I think the fully qualified names are best:
- org.mortbay.apache.jasper
- org.mortbay.apache.el

**Comment by janbartel** [comment]
I've raised https://github.com/jetty-project/jasper-jsp/issues/4 for this change. I'll be dropping this PR.

**Pull request closed without merging**
