### PR TITLE
Use already calculated _resource.length()

### PR DESCRIPTION
**Pull request by dlazerka**

### CODE REVIEW

**Comment by gregw** [comment]
Thanks for this PR.   Can you click through on the IP validation links on this issue to e-sign an ECA (eclipse contributor licence).  I can then merge and give you the commit karma.

**Comment by dlazerka** [comment]
@gregw Thanks, I'd do it, but it seems that commit author was recorded as noreply@github.com, probably because I just used GitHub interface for creating the PR:
```
The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.
noreply@github.com

The following users have invalid Signed-off-by footers. Please use the Signed-Off-By (git commit -s) mechanism to confirm the origin of the submission. The identity in the Signed-off-By must match the Author or the Committer.
noreply@github.com
```
I probably need to create a new PR from my own account to fix this, right?

**Comment by joakime** [comment]
@dlazerka there's 2 things wrong.

See: https://github.com/eclipse/jetty.project/pull/1649/commits/cfe174e48cea2836b6d3b63a1bfa1d9686cd208b

- [ ] Author is correct (your email address).
- [x] Committer is wrong (noreply@github.com)
- [x] `Signed-Off-By` (git commit -s) is not present

**Comment by gregw** [comment]
Applied manually

**Pull request closed without merging**
