### PR TITLE
Issue #6464 - fix logging capture modules

### LINKED ISSUE #6464: Wrong files/lib definitions in certain *-capture.mod files?
**Jetty version(s)**
- 10.x
- 11.x

**Description**

I just tried to create a jetty-base using all of the logging *-capture modules and ended up with a jar file on the root of jetty-base. That seemed weird so I looked into the files and found the following sections which seem to be broken.

---

https://github.com/eclipse/jetty.project/blob/dc21b2d73cafd78a56e8e532cf50863739bd7027/jetty-home/src/main/resources/modules/logging-jcl-capture.mod#L16-L20

The file should be downloaded to `lib/logging/jcl-over-slf4j-${slf4j.version}.jar`, right?

---

https://github.com/eclipse/jetty.project/blob/dc21b2d73cafd78a56e8e532cf50863739bd7027/jetty-home/src/main/resources/modules/logging-log4j1-capture.mod#L16-L20

Here `jcl-over-slf4j-${slf4j.version}.jar ` is also downloaded to the root of jetty-base but `lib/logging/log4j-to-slf4j-${slf4j.version}.jar` is put on classpath. So `log4j-to-slf4j-${slf4j.version}.jar` should have been downloaded in the first place and put into `lib/logging/`, right?

### PR DESCRIPTION
**Pull request by joakime**
+ Adding distribution tests for logging module combinations.

Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
@janbartel @gregw @lachlan-roberts I think this is useful to merge into the pending release. WDYT?

**Review by gregw — APPROVED** [review]
LGTM .
Ask @lachlan-roberts as release manager if this can sneak in.

**Review by olamy — APPROVED** [review]

**Comment by lachlan-roberts** [comment]
No problem for this to make the current release.

**Comment by joakime** [comment]
I'll merge it into 10 and then forward to 11.

**Comment by joakime** [comment]
@lachlan-roberts done, and merged all the way thru to Jetty 11.0.x

**Pull request merged**
