### PR TITLE
`NullPointerException` at `AsyncMiddleManServlet.onContinue()`

### PR DESCRIPTION
**Pull request by garydgregory**
org.eclipse.jetty.proxy.AsyncMiddleManServlet.onContinue(AsyncMiddleManServlet.java:177) #8538

https://github.com/eclipse/jetty.project/issues/8538

### CODE REVIEW

**Review by joakime — CHANGES_REQUESTED** [review]
This needs a test case to prevent regression.

**Comment by garydgregory** [comment]
> This needs a test case to prevent regression.

I should be able to update the PR in the next couple of days I hope (traveling).

**Comment by joakime** [comment]
> > This needs a test case to prevent regression.
> 
> I should be able to update the PR in the next couple of days I hope (traveling).

_bump_ ?

**Comment by garydgregory** [comment]
> > > This needs a test case to prevent regression.
> > 
> > 
> > I should be able to update the PR in the next couple of days I hope (traveling).
> 
> _bump_ ?

Sorry about the delay, I'll look in the AM.

**Pull request closed without merging**
