### PR TITLE
Fix race condition in `ArrayByteBufferPool.clear()`

### LINKED ISSUE #10703: Fix race condition in `ArrayByteBufferPool.clear()`
**Jetty version(s)**
12.0.x

**Description**
`HttpClientTLSTest.testEncryptedOutputBufferRepoolingAfterNetworkFlushThrows` randomly fails with:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.io.RetainableByteBuffer.capacity()" because the return value of "org.eclipse.jetty.util.Pool$Entry.getPooled()" is null
	at org.eclipse.jetty.io@12.0.3-SNAPSHOT/org.eclipse.jetty.io.ArrayByteBufferPool.lambda$clearArray$5(ArrayByteBufferPool.java:363)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.eclipse.jetty.io@12.0.3-SNAPSHOT/org.eclipse.jetty.io.ArrayByteBufferPool.clearArray(ArrayByteBufferPool.java:359)
	at org.eclipse.jetty.io@12.0.3-SNAPSHOT/org.eclipse.jetty.io.ArrayByteBufferPool.clear(ArrayByteBufferPool.java:351)
	at org.eclipse.jetty.io@12.0.3-SNAPSHOT/org.eclipse.jetty.io.ByteBufferPool$Wrapper.clear(ByteBufferPool.java:89)
	at org.eclipse.jetty.client@12.0.3-SNAPSHOT/org.eclipse.jetty.client.HttpClientTLSTest.testEncryptedOutputBufferRepoolingAfterNetworkFlushThrows(HttpClientTLSTest.java:1000)
```

See https://jenkins.webtide.net/job/jetty.project/job/jetty-12.0.x/1602/testReport/junit/org.eclipse.jetty.client/HttpClientTLSTest/Parallel_Stage___Build___Test___JDK21___testEncryptedOutputBufferRepoolingAfterNetworkFlushThrows_boolean__1_/

### PR DESCRIPTION
**Pull request by lorban**
Fixes #10703

### CODE REVIEW

**Review by sbordet — CHANGES_REQUESTED** [review]
The change looks good, but can you please check all the places where we can `entry.remove()`?

For example, `evict()` may have the same problem.

**Comment by lorban** [comment]
@sbordet `evict()` is the only other place where `Entry.remove()` is called, and in that case the code already is safe because the entry is returned by `findOldestEntry()` which already does a null check on `Entry.getPooled()`.

**Review by sbordet — CHANGES_REQUESTED** [review]
Please check the releaser, as buffers are never removed from the pool.

**Review by sbordet — CHANGES_REQUESTED** [review]
@lorban in light of the releaser fix, I would like a test case.
We must ensure that the pool entry is really removed when we evict.

**Comment by lorban** [comment]
@sbordet actually, there was no leak as the buffers are not multiplexed. Not checking the returned boolean of `release` and calling `remove` when the boolean is false is against the Pool contract but it's harmless in this case.

if `remove` is called by `evict` before `release`, the entry is immediately removed as the multiplex counter goes from 1 to 0, it is marked as removed (-2) and then it is removed from the pool. The thread using the evicted buffer then has a "floating" buffer that is still on heap but out of the pool.

In that case, `release` returns false which asks for `remove` to be called but `remove` is then a no-op as it notices the entry's state is -2 so it returns false too.

**Review by gregw — APPROVED** [review]

**Review by sbordet — APPROVED** [review]

**Pull request merged**
