### PR TITLE
Add unit tests two

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added Unit Tests to increase code coverage.

### CODE REVIEW

**Comment by TheRealHaui** [comment]
@gregw,
thanks for your update!
I have incorporated the changes and pushed it.

However, one question: I have specifically employed the formatting XML you can find here: https://git.eclipse.org/c/jetty/org.eclipse.jetty.admin.git/tree/jetty-eclipse-java-format.xml
Isn't that enough?
Furthermore, I have corrected the line indents in my Intellij IDE manually.
However, an idea regarding the EOLN after the last curly bracket?

**Comment by gregw** [comment]
The XML format should have been sufficient... but we have had some problems with IDEA merging styles with existing styles.  We are currently working on a definitive style guide.
Thanks for fixing manually.  You appear to have fixed the EOLN as well.  Hmmm now the ECA is broken... investigating....

**Comment by gregw** [comment]
ah you skipped the signoff on one commit.
Sorry to be a pain, can you reset, commit and force push:
```
get reset origin/jetty-9.4.x
git add -A
git commit -sm 'your new commit message'
git push -fu origin add-Unit-Tests-two
```

thanks

**Comment by TheRealHaui** [comment]
@gregw,
had some issues with the blank line at the end, merged some commits therefore which is the reason why at least one sign-off message was missing.
Now it's working.

**Thanks for the proper git commands!**

**Comment by gregw** [comment]
thanks

**Pull request merged**
