### PR TITLE
try to fix #4577

### LINKED ISSUE #4577: request getPathInfo returns null
**Jetty version**
9.4.26.v20200117

**Java version**
1.8.0_191

**OS type/version**
Windows 10 1909

**Description**
I use IPAccessHandler for restricting ip and url access. My config file is something like belows.
```xml
<?xml version="1.0"?><!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<!-- =============================================================== --><!-- Configure the test-jaas webapp                                  --><!-- =============================================================== -->
<Configure id='wac' class="org.eclipse.jetty.webapp.WebAppContext">

  <Set name="contextPath">/auditlog</Set>
  <Set name="resourceBase">/d:/log/</Set>
  
  <Call name="insertHandler">
    <Arg>
      <New class="org.eclipse.jetty.server.handler.IPAccessHandler">
        <Call name="addWhite">
          <Arg>127.0.0.1|/*</Arg>
        </Call>
      </New>
    </Arg>
  </Call>

</Configure>
```

But when I browser http://127.0.0.1:8080/auditlog/, it always give me 403 error. After go through the code, I find it was `baseRequest.getPathInfo()` returned null instead of `/auditlog/`, so the validator logic failed.

image

### PR DESCRIPTION
**Pull request by liudonghua123**
Fix #4577 request getPathInfo returns null

### CODE REVIEW

**Comment by sbordet** [comment]
@liudonghua123 please see https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md for instructions about how to contribute to Jetty.

Also, I don't think your fix is correct.

Let's continue the discussion in the issue and you can contribute a good fix after the discussion.

**Comment by liudonghua123** [comment]
@sbordet Hi, I have read the https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/CONTRIBUTING.md, signed the ECA, amend the commit and force push again.

**Comment by sbordet** [comment]
@liudonghua123 thanks for the ECA and PR, but the fix only consider the `contextPath` and that is not correct.

**Comment by liudonghua123** [comment]
@sbordet Hi, I don't quite understand, we just need to consider the ip and path part of request url in the IPAccessHandler. What else do I need to consider?

**Comment by gregw** [comment]
replaced by #4580

**Comment by joakime** [comment]
@liudonghua123 note: `IPAccessHandler` is deprecated, you should be using the replacement `InetAccessHandler`

https://github.com/eclipse/jetty.project/blob/jetty-9.4.26.v20200117/jetty-server/src/main/java/org/eclipse/jetty/server/handler/InetAccessHandler.java

**Pull request closed without merging**
