### PR TITLE
Use updated setuid with clearSupplementalGroups

### PR DESCRIPTION
**Pull request by gregw**
See https://github.com/eclipse/jetty.toolchain/issues/6 & https://github.com/eclipse/jetty.toolchain/pull/28

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by gregw** [comment]
@jesse can you finish this one once the setuid stuff is built

**Comment by jmcc0nn3ll** [comment]
@gregw LGTM

**Review by jmcc0nn3ll — APPROVED** [review]
All good, *.jar isn't my favorite but this is a narrow case and should be fine.

**Comment by joakime** [comment]
> All good, *.jar isn't my favorite but this is a narrow case and should be fine.

I agree. as `lib/setuid/*.jar` will load all jars from both `${jetty.home}/lib/setuid/*.jar` and `${jetty.base}/lib/setuid/*.jar` (and any intermediary base directories too, but that's advanced usage)

**Pull request merged**
