### PR TITLE
Provide a more helpful TimeoutException message

### PR DESCRIPTION
**Pull request by garydgregory**
- One cannot tell what endpoint is at fault in a non-trivial configuration, for example, using an `AsyncMiddleManServlet`, is it the origin or the client?
- The `TimeoutException` message now contains the endpoint causing the timeout

### CODE REVIEW

**Comment by sbordet** [comment]
@garydgregory I have doubts that we can accept this, as we need to be _very_ careful about exposing IP addresses (even internal ones) in exception messages that may be seen by remote users.

In `AsyncMiddleManServlet` you have `onClientRequestFailure()` and `onProxyResponseFailure()` to determine whether it is the client or the server.

@joakime @gregw @lorban opinions about disclosing the IP in the exception?

**Comment by garydgregory** [comment]
Hi all,

In the failure methods, I cannot tell from the throwable which endpoint threw the exception. 

Would you rather the TimeoutException point to the endpoint that created it? This could only be done in a new custom TimeoutException subclass.

**Comment by sbordet** [comment]
@garydgregory the failure methods have the request objects, and you can call e.g. `HttpServletRequest.getRemoteAddr()`.
Did you try and it's not working?

**Comment by garydgregory** [comment]
> @garydgregory the failure methods have the request objects, and you can call e.g. `HttpServletRequest.getRemoteAddr()`. Did you try and it's not working?

Hello @sbordet 

Thank you for your suggestion. I'll try using the 'remote' methods in our servlet and see what get in our logs... TY!

**Comment by garydgregory** [comment]
FYI I still have some testing to do and reviewing of our logs.

**Comment by sbordet** [comment]
@garydgregory do you have an update? I'm inclined to close this, as the "remote" methods should be enough for your use case?

**Comment by garydgregory** [comment]
@sbordet 
Yes, sorry about the delay. I'll close this.

**Pull request closed without merging**
