### PR TITLE
Issue #4228 - remove default keystore passwords not from test-keystore.mod

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Signed-off-by: Lachlan Roberts <lachlan@webtide.com>

#4228

### CODE REVIEW

**Comment by sbordet** [comment]
@lachlan-roberts so they line you are adding back was removed by @gregw for #1615 in 748d582994ddb68adf9113e377f773ce9a2a8cab.

I don't think this line is meant to be back... there was a reason to remove it.

@gregw?

**Comment by joakime** [comment]
How hard would it be to run a few command on the command line to generate a new test keystore on install of the module?

**Comment by lachlan-roberts** [comment]
@joakime i could do something like this called by the xml for the `test-keystore` module.

```java
String javaHome = System.getenv("JAVA_HOME");
String command = javaHome + "bin/keytool -genkey -keyalg RSA -keystore keystore -alias jetty-test-keystore -dname O=jetty -storepass password -keypass password";
Runtime.getRuntime().exec(command);
```

Not sure if this would still work for other operating systems like windows.

**Comment by sbordet** [comment]
@lachlan-roberts I don't understand this PR... it only removes the default passwords from the XML files, but I don't see any other change?
Is it complete?

**Comment by joakime** [comment]
@sbordet this is just cleanup from 748d582994ddb68adf9113e377f773ce9a2a8cab

The [test-keystore.mod](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x-4228-demoKeystore/jetty-server/src/main/config/modules/test-keystore.mod) has the passwords now, the defaults in the XML should have been removed on that older commit, but were missed.

**Pull request merged**
