### PR TITLE
Added test case for HTTP proxy tunneling authorization failure

### PR DESCRIPTION
**Pull request by dhirajsb**
Signed-off-by: Dhiraj Bokde <dbokde@redhat.com>

### CODE REVIEW

**Comment by dhirajsb** [comment]
Added git --signoff to commit

**Comment by joakime** [comment]
Don't forget to submit a CLA at Eclipse.

https://www.eclipse.org/legal/CLA.php

**Comment by joakime** [comment]
Don't forget about submitting your CLA to the Eclipse Foundation.

https://www.eclipse.org/legal/CLA.php

**Comment by dhirajsb** [comment]
I've submitted the Eclipse CLA and added my github account id.

**Comment by joakime** [comment]
@sbordet this pull request is legally allowed to be applied now.

**Pull request merged**
