### PR TITLE
Re-enable ResourceHandlerTest for range requests and fix.

### PR DESCRIPTION
**Pull request by janbartel**
The `ResourceHandlerTest` had range requests disabled; re-enabled them and fixed test as necessary.

### CODE REVIEW

**Comment by janbartel** [comment]
@joakime @gregw this test was checking for the presence of a `Content-Length` header even when the request specified multiple ranges. Based on previous jetty behaviour, and code comments eg https://github.com/jetty/jetty.project/blob/jetty-11.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java#L792 it looks like it is incorrect to expect a `Content-Length` header, so I removed those checks.

**Comment by joakime** [comment]
> @joakime @gregw this test was checking for the presence of a `Content-Length` header even when the request specified multiple ranges. Based on previous jetty behaviour, and code comments eg https://github.com/jetty/jetty.project/blob/jetty-11.0.x/jetty-server/src/main/java/org/eclipse/jetty/server/ResourceService.java#L792 it looks like it is incorrect to expect a `Content-Length` header, so I removed those checks.

Yeah, remove it for Jetty 12.
I think the response buffering in Jetty 11 helped make this particular response have a Content-Length header.

**Comment by joakime** [comment]
Interesting, JDK23 timed out at 3 hours 30 minutes for this PR.

https://jenkins.webtide.net/blue/organizations/jenkins/jetty.project/detail/PR-12418/1/pipeline/

I kicked off rebuild, lets see what happens.

**Review by gregw — APPROVED** [review]
I think jenkins is dead or dying

LGTM

**Pull request merged**
