### PR TITLE
Resolves #2152 by adding new artifacts with 'sources' classifier whic…

### LINKED ISSUE #2152: Produce jetty-home-source artifacts for Eclipse Jetty source jars
Update the assembly plugin to produce a new `<classifier>src</classifier>` object that has a similar `${jetty.home}/lib/` structure, but with `-source.jars` only.

Various tool implementors have expressed an interest in this.

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
…h contains the -sources artifacts for jetty classes under lib (only)

Signed-off-by: Jesse McConnell <jesse.mcconnell@gmail.com>

### CODE REVIEW

**Comment by jmcc0nn3ll** [comment]
I think we were planning on just closing this out since I think the core need disappeared based on what @gregw was saying.  It had been working though so I must have missed something when I pushed it over to another machine to make a PR, was having signing issues at the time.

**Comment by gregw** [comment]
I think the core requirement is back!  So let's see if we can make this work.

**Comment by gregw** [comment]
@joakime it builds the source bundle in jetty-home not jetty-distribution

@jmcc0nn3ll This appears to be working for me for the top level jars (eg $JETTY_HOME/lib/jetty-http-9.4.9-SNAPSHOT-sources.jar), but not for nested libraries (eg $JETTY_HOME/lib/http2/http2-hpack-9.4.9-SNAPSHOT.jar)

@olamy hold your work on bazel build for now, as I think this approach may be simpler and more correct for the client

**Comment by olamy** [comment]
look at https://github.com/eclipse/jetty.project/pull/2208 to replace this pr

**Pull request merged**
