### PR TITLE
HttpExchange retained by HttpSenderOverHTTP which caused memory leak

### PR DESCRIPTION
**Pull request by shaoxt**
HttpExchange retained by HttpSenderOverHTTP which caused memory leak

Screenshot 2024-05-10 at 9 54 02 PM

Since the HttpSenderOverHTTP retained by HttpChannelOverHTTP and HttpConnectionOverHTTP.
The HttpConnectionOverHTTP has to be timed-out in the CyclicTimeouts. If the connection timeout set too long.
The HttpRequest and HttpResponse also retained too long.

### CODE REVIEW

**Comment by shaoxt** [comment]
PR for https://github.com/jetty/jetty.project/issues/11781

**Comment by shaoxt** [comment]
ECA is signed, but the github didn't detect.

**Comment by sbordet** [comment]
@shaoxt the change is good.

Can you please close this PR, and #11780, and make a new PR with the same changes against branch `jetty-10.0.x`?
We will take care of merging it forward to Jetty 11 and 12.

Thanks!

**Comment by shaoxt** [comment]
@sbordet  Here it is https://github.com/jetty/jetty.project/pull/11782

Thank you!

**Pull request closed without merging**
