### PR TITLE
jetty-p2 module back

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by joakime** [comment]
Looks like the generated `artifacts.xml` produces entries only for our artifacts.

``` xml
<!-- $ cat artifacts.xml | grep "<artifact" | sort -->
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.alpn.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.alpn.conscrypt.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.alpn.conscrypt.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.alpn.java.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.alpn.java.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.alpn.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.demos.demos' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.deploy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.annotations' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.apache-jsp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.cdi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.demos.async.rest.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.demos.async.rest' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.demos.demo-mock-resources' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.demos.demo-servlet-container-initializer' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.demos.embedded' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.demos.spec.fragment' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.fcgi.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.glassfish.jstl' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.jndi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.jspc.plugin' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.maven.plugin' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.osgi.alpn.fragment' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.osgi.boot.jsp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.osgi.boot' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.plus' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.quickstart' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.security.jaspi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.servlets' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.servlet' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.client.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.jakarta.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.jakarta.client.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.jakarta.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.jakarta.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee10.websocket.servlet' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.annotations' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.apache-jsp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.demos.async.rest.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.demos.async.rest' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.demos.ee8-demo-mock-resources' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.demos.ee8-demo-servlet-container-initializer' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.demos.spec.fragment' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.glassfish.jstl' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.jndi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.jspc.plugin' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.maven.plugin' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.openid' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.osgi.boot.jsp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.osgi.boot' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.plus' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.quickstart' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.security.jaspi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.security' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.servlets' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.servlet' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.api' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.client.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.javax.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.javax.client.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.javax.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.javax.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee8.websocket.servlet' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.annotations' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.apache-jsp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.cdi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.demos.async.rest.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.demos.async.rest' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.demos.ee9-demo-mock-resources' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.demos.ee9-demo-servlet-container-initializer' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.demos.embedded' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.demos.spec.fragment' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.fcgi.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.glassfish.jstl' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.jndi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.jspc.plugin' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.maven.plugin' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.openid' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.osgi.boot.jsp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.osgi.boot' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.plus' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.quickstart' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.security.jaspi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.security' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.servlets' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.servlet' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.api' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.client.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.jakarta.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.jakarta.client.webapp' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.jakarta.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.jakarta.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee9.websocket.servlet' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.ee' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.fcgi.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.fcgi.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.fcgi.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.gcloud.session' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.hazelcast' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http2.client.http' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http2.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http2.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http2.hpack' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http2.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http3.client.http' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http3.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http3.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http3.qpack' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http3.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http.spi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http.tools' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.http' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.infinispan.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.infinispan.embedded.query' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.infinispan.remote.query' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.io' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.jmx' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.jndi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.keystore' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.logging' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.maven' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.memcached.session' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.nosql' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.openid' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.osgi' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.plus' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.proxy' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.quic.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.quic.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.quic.quic-quiche-common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.quic.quic-quiche-jna' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.quic.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.rewrite' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.security' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.session' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.start' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.unixdomain.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.util.ajax' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.util' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.api' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.core.client' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.core.common' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.core.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.websocket.server' version='12.0.12.SNAPSHOT'>
    <artifact classifier='osgi.bundle' id='org.eclipse.jetty.xml' version='12.0.12.SNAPSHOT'>
  <artifacts size='164'>
```

**Comment by joakime** [comment]
And the `context.xml` produces requirements against our different EE versions too.

``` xml
<!-- $ cat content.xml | grep "jakarta.servlet" | sort | uniq -c -->
     12         <provided namespace='osgi.serviceloader' name='jakarta.servlet.ServletContainerInitializer' version='0.0.0'/>
      5         <required namespace='java.package' name='jakarta.servlet.annotation' range='[5.0.0,6.0.0)'/>
      4         <required namespace='java.package' name='jakarta.servlet.annotation' range='[6.0.0,7.0.0)'/>
      4         <required namespace='java.package' name='jakarta.servlet.descriptor' range='[5.0.0,6.0.0)'/>
      3         <required namespace='java.package' name='jakarta.servlet.descriptor' range='[6.0.0,7.0.0)'/>
     17         <required namespace='java.package' name='jakarta.servlet.http' range='[5.0.0,6.0.0)'/>
     14         <required namespace='java.package' name='jakarta.servlet.http' range='[6.0.0,7.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp.el' range='[3.0.0,4.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp.el' range='[3.1.0,4.0.0)'/>
      2         <required namespace='java.package' name='jakarta.servlet.jsp.jstl.core' range='2.0.0' optional='true' greedy='false'/>
      2         <required namespace='java.package' name='jakarta.servlet.jsp.jstl.fmt' range='2.0.0' optional='true' greedy='false'/>
      2         <required namespace='java.package' name='jakarta.servlet.jsp.jstl.sql' range='2.0.0' optional='true' greedy='false'/>
      2         <required namespace='java.package' name='jakarta.servlet.jsp.jstl.tlv' range='2.0.0' optional='true' greedy='false'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp' range='[3.0.0,4.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp' range='[3.1.0,4.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp.resources' range='[3.0.0,4.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp.resources' range='[3.1.0,4.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp.tagext' range='[3.0.0,4.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.jsp.tagext' range='[3.1.0,4.0.0)'/>
     23         <required namespace='java.package' name='jakarta.servlet' range='[5.0.0,6.0.0)'/>
     20         <required namespace='java.package' name='jakarta.servlet' range='[6.0.0,7.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.resources' range='[5.0.0,6.0.0)'/>
      1         <required namespace='java.package' name='jakarta.servlet.resources' range='[6.0.0,7.0.0)'/>
      2         <requiredProperties namespace='osgi.serviceloader' match='(osgi.serviceloader=jakarta.servlet.ServletContainerInitializer)' min='0' greedy='false'>
```

**Comment by joakime** [comment]
Attaching the generated p2-site.zip (that this PR/branch produced) for @laeubi to look at.

[p2-site.zip](https://github.com/user-attachments/files/16144814/p2-site.zip)

**Comment by laeubi** [comment]
This looks all fine to me
grafik

**Review by janbartel — CHANGES_REQUESTED** [review]
If we don't publish the `demos` to maven, should we be putting them in `p2`?

**Comment by laeubi** [comment]
> If we don't publish the `demos` to maven, should we be putting them in `p2`?

Actually not, but if it is too much trouble to exclude them it won't harm that much (it will just fail to install).

**Comment by laeubi** [comment]
Thinking twice, this might be because it is not a deployment, in case of deployment, all modules that are not deployed will be skipped.

**Comment by joakime** [comment]
> Thinking twice, this might be because it is not a deployment, in case of deployment, all modules that are not deployed will be skipped.

Yeah, the testing I've been doing on this branch has been using `mvn clean install` (no `deploy`)

**Comment by joakime** [comment]
@olamy can you address @janbartel question about demos?
And can you fix the build error?

**Comment by olamy** [comment]
> @olamy can you address @janbartel question about demos? And can you fix the build error?

@janbartel @joakime 
As far as I can see demos are deploying to central https://repo.maven.apache.org/maven2/org/eclipse/jetty/ee9/demos/ or https://repo.maven.apache.org/maven2/org/eclipse/jetty/ee10/demos/ 
should we stop deploying them?

**Comment by janbartel** [comment]
OK, if the demos are on maven central we're all good.

**Review by janbartel — APPROVED** [review]

**Pull request merged**
