### PR TITLE
Jetty could not running on MacOS Catalina(10.15)

### PR DESCRIPTION
**Pull request by KyongSik-Yoon**
MacOS 10.15 has different mount path with previous version.
So AllowAliasCheck module deny all kind of resources has alias.

Signed-off-by: Kyoung Sik Yoon <sam1287@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
MacOS Catalina (10.15) is currently in beta.
This change will have to be reviewed once 10.15 is final and publicly available. (non-beta)

**Comment by joakime** [comment]
Out of curiosity, can you check if the changes in PR #4001 improve things for you?
The `SameFileAliasChecker` might accomplish the same end goal for you.

**Comment by KyongSik-Yoon** [comment]
I'll try check it give me same result or not.

**Comment by KyongSik-Yoon** [comment]
@joakime 
Great. I checked changes in PR #4001 could accomplish compatibility of changes on MacOS Catalina. You can close this issue and my PR #3855 
Thanks.

**Pull request closed without merging**
